### PR TITLE
Updates on language elements

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**
Updates language elements...

**Fix**
- Correct typo in language selection

**Changes**
- Sort Languages alphabetically
- Merge DE translations with DE ones in POEditor

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by m-seker** [comment]
Dank je wel !

**Comment by brindosch** [comment]
Did you merged the POEditor translations over the repo translations? The POEditor translations for DE aren't that mature or in sync with later repo updates?

**Comment by Lord-Grey** [comment]
> Did you merged the POEditor translations over the repo translations? The POEditor translations for DE aren't that mature or in sync with later repo updates?

@brindosch 

1. I downloaded POEditor DE as json
2. I downloaded DE.json
3. I sorted both files per element
4. I compared each element one by one and chosen the latest/better translation
5. I checked in the merged File in Git
6. I uploaded the merged file into POEditor

i.e. I did a two way manual merge, currently both files should now be in sync.

**Comment by brindosch** [comment]
Thank you for clarification. Just wanted to make sure we don't trash here strings :)
> btw. I saw that there is a Git Plugin in POEditor

Do you mean "Integrations" Github? It's just for syncing and the options are very limited.

**Pull request merged**
