### PR TITLE
fix amlogic flatbuffer library

### PR DESCRIPTION
**Pull request by Portisch**
**1.** Tell us something about your changes.
With this change the flatc compiler will be found on amlogic
**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by Portisch** [comment]
Also here is a patch to add libarys to fix compiling for amlogic. But I am sure this will be device specific and can't be include with a pull request, isn't it?
https://gist.github.com/Portisch/1926ffab6b543d72792cf32da9e1cbb9

**Comment by RickDB** [comment]
Not sure if it's possible to make the CMAKE file selective for certain platforms as pretty sure it will break other platforms if we include just the extra-linking-libraries.patch.

**Comment by Portisch** [comment]
I am also not sure. If it will not be accepted I add a local patch file.
I just tried the newest Hyperion version without any config change and it didn't work. So more testing is required.

**Comment by RickDB** [comment]
Want me to merge this one already and optionally that patch in a separate PR later?

**Comment by Portisch** [comment]
Without this patch it won't compile on Coreelec anyway.

**Comment by RickDB** [comment]
Gonna ping @Paulchen-Panther then to check if there's way to include this patch.

**Comment by RickDB** [comment]
What you could do in the meantime is include the patch in this PR, Travis will let's know if it compiles properly and can do local testing afterwards as an additional check.

**Comment by Paulchen-Panther** [comment]
> Also here is a patch to add libarys to fix compiling for amlogic. But I am sure this will be device specific and can't be include with a pull request, isn't it?
> https://gist.github.com/Portisch/1926ffab6b543d72792cf32da9e1cbb9

Yes, it's possible
```
if (ENABLE_AMLOGIC)
target_link_libraries(${PROJECT_NAME} pcre16 dl z)
endif ()
```

**Comment by Portisch** [comment]
I have done a new "compile fix" PR: https://github.com/hyperion-project/hyperion.ng/pull/536

**Pull request closed without merging**
