### PR TITLE
Cap flag at end

### PR DESCRIPTION
**Pull request by Portisch**
1. Tell us something about your changes.
First commit will remove ge2d support from amlogic device as it is not needed anymore.
The second commit will fix the video slow down issue on amlogic devices. The amvideocap driver needs to support the CAP_FLAG_AT_END method.

2. If this changes affect the .conf file. Please provide the changed section
removed 2 settings as they are not needed anymore: amlogic_grabber & ge2d_mode

3. Reference an issue (optional)
The existing video slow down issue since hyperion got ported to arm/amlogic
Note: For further discussions use our forum: forum.hyperion-project.org

More infos about the video slow down:
https://discourse.coreelec.org/t/slow-down-of-hyperion-ng/341

### CODE REVIEW

**Comment by tpmodding** [comment]
chmod fix didnt work?

**Comment by Portisch** [comment]
Where, I am not used to travis...

**Comment by RickDB** [comment]
Something odd broke during pull or rights of the folder the project is located, current Travis logs shows this error:

https://travis-ci.org/hyperion-project/hyperion.ng/jobs/517766826

**Comment by Portisch** [comment]
I changed too much chmod of the project. I need to redo the commits. Sorry, but I think the best is to close the pr again until I have time to fix it!

**Comment by RickDB** [comment]
No problem and just let me know when it’s ready to merge 👍🏻

**Pull request closed without merging**
