### PR TITLE
Logging leds

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
migrate leddevices to new logger.

still todo:
LedDeviceWS2812b
LedDeviceWs2812SPI

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)
#25

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Nice!
There is something strange, this PR has partly the same code change like the previous. How could this be?

**Comment by penfold42** [comment]
Because he has done it more completely for more led device drivers.
He also instantiated the logger at the parent class which is much cleaner!

**Comment by redPanther** [comment]
I made the pr from the same branch as Iusef for my prior pr. This pr is just in addition.

After you merged. I forget to git fetch and merge to sync our repos. Thatswhy github shows my prior and new commits .instead of new one only.
Thats not harmful, because git detect that during merge and do the right thing.

BTW thx for settiing up CI. An additional osx build would be cool

**Comment by redPanther** [comment]
... forgott to say, with this comit we can start without configured led device. If no led device configured, then dummy device is selected (dummy means - file device with output /dev/null )

**Comment by brindosch** [comment]
nice on, currently i added the file device with output /dev/null as default. I will do soon a PR to update our current .json and add a new one without comments which should be used if you perform a "reset this configuration to default" at the webinterface :)

**Pull request merged**
