### PR TITLE
merge adalight and adalightapa102

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
if you want to use adalightapa102 driver, select adalight and set
`lightberry_apa102_mode : true`
in device config. Default is standard adalight

device adalightapa102 is not needed anymore and removed

**2.** If this changes affect the .conf file. Please provide the changed section
new option for device:
`lightberry_apa102_mode : true`

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
FYI @tociek

**Comment by tociek** [comment]
I will test it within few days

**Comment by tociek** [comment]
I compiled and run hyperion today. I wanted to use (really cool) web interface to configure device, however when I want to save the settings (i.e. device type) I get 
Error while parsing json: unterminated string at Line: 0, Column: XXXX (XXXX is a number which changes depending on device type chosen)

**Comment by brindosch** [comment]
Does the log throw a "too long json message" message and the ui reloads?

**Comment by redPanther** [comment]
BTW currently it's good to use the save way - take default config and edit to you needs with plain old boring text editor. The led layout can be taken from your old hyperion.config

**Comment by Paulchen-Panther** [comment]
Also ich hab das ja auch schon mal versucht die config ab zu speichern. Bis jetzt funktioniert das ganze. Abgesehen von der color correction section.  Wenn man da alle Optionen entfernt wird das komplette object aus der config entfernt. Das heißt Hyperion startet nicht mehr. Aber den Fehler "to long json message" hatte ich bis jetzt noch gar nicht. Alles zu beschreiben sprengt jetzt aber den Rahmen.

**Comment by brindosch** [comment]
@Paulchen-Panther 
Meine 122 leds will er nicht, verringere ich die Anzahl geht es wieder :)
@ all
https://github.com/hyperion-project/hyperion.ng/issues/292

**Comment by tociek** [comment]
I get [HYPERIOND JSONCLIENTCONNECTION] <ERROR> Someone is sending very big messages over several frames... it's not supported yet from hyperiond process. I haven't define anything in webui except for device type and clicking save

**Comment by redPanther** [comment]
this is  #292
this is known and in progress ... thats why it is currently better to edit manually

**Comment by tociek** [comment]
I confirm, it works fine.

Thanks

**Pull request merged**
