### PR TITLE
every input sources trackes now its priority and ID to hyperion core

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
now every input sources trackes it's priority with a name. collisions are also detected.
ATM protoconnections arn't tracked yet.

collison example:
`[HYPERIOND Core] <WARNING> Input source 'V4L2' uses same priority channel (900) as 'Boblight'.`

**2.** If this changes affect the .conf file. Please provide the changed section
no
**3.** Reference a issue (optional)
#28

Note: For further discussions use our forum: forum.hyperion-project.org

ATM all input sources except inputs via proto are tracked

### CODE REVIEW

**Comment by penfold42** [comment]
I was think about this earlier - can we include the source up when we add proto connections ?
Proto@10.0.0.207

**Comment by redPanther** [comment]
Of course, proto is missing here. What I want is: proto:X11@ip. Therefore I have to extend proto interface

**Comment by redPanther** [comment]
I will merge it tomorrow, before I want to move the un/register to start/stop method.
And query via json is,missing too.

If you have further hints, let me know.

**Comment by redPanther** [comment]
now register/unregister of grabber prio is moved to start/stop
owner of a prio channel is shown in json serverinfo

hyperion-remote example:
```
   "priorities" : [
      {
         "duration_ms" : 999,
         "owner" : "unknown",
         "priority" : 800
      },
      {
         "duration_ms" : 988,
         "owner" : "Boblight",
         "priority" : 900
      },
      {
         "owner" : "EFFECT: /usr/share/hyperion/effects/mood-blobs.py",
         "priority" : 2147483646
      }
   ],

```

**Comment by redPanther** [comment]
now proto is integrated in priority register. It will show up as proto@ip in priority list

**Comment by brindosch** [comment]
you may be interested in using "Squash and merge" to get a cleaner commit history.

**Comment by redPanther** [comment]
thx for the hint

**Pull request merged**
