### PR TITLE
per effect smoothing

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
this pr adds ability to set per effect smooting settings.
Smoothing settings are written in effect json file.
As default all effects without smoothing params in json config have smoothing disabled.

Currently I added smoothing settings only to effect "candle" and "random".
(others should follow, but I don't feel in a artistic mood today. Feel free to post settings for a specific effect as comment to this pr.)

new candle.json
```
{
	"name" : "Candle",
	"script" : "candle.py",
	"args" :
	{
		"sleepTime" : 0.20,
		"brightness" : 100,
		"color" : [ 255, 138, 0 ],
		"candles" : "all",
		"smoothing-custom-settings" : true,
		"smoothing-time_ms" : 500,
		"smoothing-updateDelay" : 0,
		"smoothing-updateFrequency" : 20.0,
		"smoothing-pause" : false
	}
}
```

Additionaly:
- refactored some qt vs. stl stuff (mainly std::min/max to qMin/Max).
- fixed fade.py effect (crashed with div by zero)

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)
#447

### CODE REVIEW

**Comment by penfold42** [comment]
Perfect !

Great work

**Comment by brindosch** [comment]
Very cool!
You can hide options by adding a dependency
```
			"options": {
				"dependencies": {
					"smoothing-custom-settings": true
				}
			},
```
So this option won't be shown until smoothing-custom-setting is true

**Comment by redPanther** [comment]
cool I always wanted such option :-) it's integrated now

**Comment by redPanther** [comment]
testbuild complete. from my side ready to merge. We can add custom smoothing settings to other effects later on ...

**Comment by brindosch** [comment]
I have a question, is there a real diff between "enabled" and "pause" during usage? If you disable it, it is on kind of pause anway?

**Comment by redPanther** [comment]
pause is internal for effects and enable is for the user. 
technically pause feeds the smooth device and enabled does it not.

We can rename 'pause' in 'enabled' in effects json ... this would look a bit nicer for users.

**Comment by brindosch** [comment]
So it does simply the "same". I think a merge is useful to reduce size!

**Pull request merged**
