### PR TITLE
webui: enhance led config

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- split content and js
- tune leds config: now with tabs and custom config edit (save not working yet)
- add connection lost detection

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
impressive!
well, the editor is a little bit laggy if you scroll down the first time (afterwards it is something like "cached?")

**Comment by redPanther** [comment]
call for a good connection lost page. Be aware that all things must be loaded on startup, because when connection lost, you can't get any data from server.

automatic check if server is reachable and then redirect to server would be nice
file: content/connection_lost.html

**Comment by brindosch** [comment]
Well, adding a picture with Hyperion and a broken connection to browser logos would be easier than fiddling around with font awesome and would make the message more clear.

Workaround: add img to index.html and set it to display:none, now you could access the picture via css (background-image) even if websever is down. To change picture sizes depending on screen size use @media property

**Comment by redPanther** [comment]
... see #226

**Comment by brindosch** [comment]
It is still mandatory to load the picture once

**Comment by redPanther** [comment]
of course ... there is a hidden div where we put all connection los data

**Pull request merged**
