### PR TITLE
Color Adjustment 2.0

### PR DESCRIPTION
**Pull request by Funatiq**
**1.** Tell us something about your changes.
See [forum post](https://hyperion-project.org/threads/color-adjustment-2-0.552/).

**2.** If this changes affect the .conf file. Please provide the changed section
See config files below.

To do:
Hyperion remote needs to be updated for the new colors: black, white, cyan, magenta, yellow

### CODE REVIEW

**Comment by brindosch** [comment]
Looks promising, some thoughts. As you see the color area is still very untouched in comparison to current stable and needs a 'refactoring'. The way we have chosen how to connect ui and and config files is neat but has also some limits.

 - I think it's suitable to use a colorpicker to modify each color?
 - you could rename pureR/G/B accordingly. We break regurlarly the configs anyway :)
 - The "black" could be removed from config? (Any downside possible?)
 - Did you succesfully tested this with good results (overall)?

If we use colorpicker (i think it's the best way), i would prefer arrays
json schema example: https://github.com/hyperion-project/hyperion.ng/blob/master/effects/schema/candle.schema.json#L20-L33

@redPanther what do you think? Any concerns?

Also related https://github.com/hyperion-project/hyperion.ng/issues/276

**Comment by redPanther** [comment]
I also vote for arrays and color picker.
can we change config to something more compact and easier version
```
{
"red" : [255,0,0],
"green" : [0,255,0],
"blue" : [0,0,255],
"black" : [0,0,0],
"white" : [255,255,255],
"cyan" : [0,255,255],
"magenta" : [255,0,255],
"yellow" : [255,255,0]
}
```

**Comment by penfold42** [comment]
Now if we could visualise it or find a cubic 3D colour picker like https://i-msdn.sec.s-msft.com/dynimg/IC726000.png it would be cool

**Comment by brindosch** [comment]
Hehe http://codepen.io/pierre-luc/full/GqyxqG
But the handling is slighty fiddling. i think our current is a good start. You configure with a assistant each part step by step to prevent a 'overextension' the first time.

I wonder if it is possible to create something like a osd overlay (color picture) in current video stream for calibration. (a overlay of the current content) @redPanther is this possible?

**Comment by Funatiq** [comment]
Yes, the array versions looks much cleaner. Color picker is nice, but I always like to fine tune the RGB values myself. 3D color picker is not very handy and I would prefer a flat one. A 3D visualization of the modified color cube would be cool though :)

I would like to keep the "black corner" and rather remove the blacklevel (and whitelevel) from the transform if we want to merge them anyway.

I only tested if the changes work with hypersim. I will do tests with my actual LEDs when I find some time.

**Comment by brindosch** [comment]
> I would like to keep the "black corner" and rather remove the blacklevel (and whitelevel) from the transform if we want to merge them anyway.

Sounds good. Yes, i think the merge is necessary, cause you are going crazy to configure multiple calibrations with 2 arrays each. Rename and break whatever is suitable for a clean(er) code and removing task duplicates (whitelvl, ...).
> but I always like to fine tune the RGB values 

Our current one fulfill this. Edit the values -> cp updated, change cp -> update values.
unbenannt
More over this could be done - later (Or if someone is motivated - now) :)

Looking forward for more :)

**Comment by redPanther** [comment]
If you can merge the color stuff and tidy up we would be very happy! Did you want to do this in this pr, or should we merge and you make a new one?

**Comment by Funatiq** [comment]
I can update this PR, but it may take some time.

**Comment by redPanther** [comment]
a suggestion: update at first only the config thing, this shouldn't be a big thing.
 Then we merge. After that we can think about merging transform and adjustment.

**Comment by Funatiq** [comment]
Sounds good to me.

**Comment by brindosch** [comment]
fixed typo...

**Comment by redPanther** [comment]
Cool thing :-)

**Comment by oberstmueller** [comment]
Hi, wenn ich bei der neuen Color Adjustment 2.0 die Werte ändere kann ich nur bei den Werten Schwarz und Weiß eine Veränderung feststellen. Bei den Farben ändert sich nichts.

Trotz meiner veränderten Config sehen rot, grün und blau unverändert aus
                                    {
                                                  "id"   : "default",
                                                  "leds" : "*",
                                                  "black"   : [0,0,0],
                                                  "white"   : [255,255,255],
                                                  "red"     : [255,30,0],
                                                  "green"   : [60,255,0],
                                                  "blue"    : [30,0,255],
                                                  "cyan"    : [0,255,255],
                                                  "magenta" : [255,0,255],
                                                  "yellow"  : [255,255,0]
                                    }

**Comment by Funatiq** [comment]
Sorry, mein Fehler. Hab beim umbenennen was vergessen.
Hier der fix #357

**Comment by oberstmueller** [comment]
Super vielen Dank für die extrem schnelle Hilfe. Jetzt passt es wieder!

**Comment by brindosch** [comment]
@Funatiq 
Vorschläge für max gamma? Das steht gerade auf 100,0. Ich dachte da an 3,0. Ich hab auch noch nie jemand gesehen, der ein gamma von mehr als 2,9 hatte.

**Comment by redPanther** [comment]
5 should be a good value

**Comment by Funatiq** [comment]
5 sounds good to me and should definitely be enough

**Pull request merged**
