### PR TITLE
Update webui

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
 - New: classic led layout corner gap. corner gap and edge gap respects 16:9 accordingly. Click on labels points to input elements. All values are now rounded before they hit the textfield.
 - led preview now with led numbers to take on or off
 - device list: each device is now sorted into optgroups
 - editor: uses now html attribute "number" for integer and numbers with min/max/step (step default is 1 (if unknown) so you are not forced to bloat the schemas)
 - editor: checkboxes now with (bigger) design (bootstrap toggles removed due to issues)
 - effconfigurator now with working onChange trigger for colorpicker thanks to @Paulchen-Panther 
 - remote: optgroups, effevts sorted between user created and provided effects
 - bootstrap: adds new layout option col-xxl-* which triggers at 1500px
 - better dashboard layout across diff screen sizes
 - removed some crap
 - other minor adjustments

**2.** If this changes affect the .conf file. Please provide the changed section
nope
**3.** Reference an issue (optional)
nope

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
Du wirst noch zum HTML und JS Experte. Hut ab. :+1:

**Comment by brindosch** [comment]
Nur langsam :)
aber danke!

please don't merge
Just noticed the optgroup :)
http://www.w3schools.com/tags/tag_optgroup.asp

**Comment by brindosch** [comment]
opt groups available, i hope it works accordingly also with non Pi systems.

**Comment by redPanther** [comment]
Impressive changes!!

**Comment by tpmodding** [comment]
you are too fast :D cant dl and compile so fast as you update things :) nice progres!

**Comment by redPanther** [comment]
ready to merge?

**Comment by brindosch** [comment]
One moment :)

**Comment by brindosch** [comment]
Good to go :)
Have fun

**Pull request merged**
