### PR TITLE
New Json Editor

### PR DESCRIPTION
**Pull request by b1rdhous3**
**1.** Tell us something about your changes.

New Json Editor (https://github.com/jdorn/json-editor)
At the moment generic translation for JSON forms is not working. Need to find another solution. But we want look for a new language lib anyway.

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
if you add new params in json schema (format) you have to add it in source code for the checker to0:
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/utils/jsonschema/QJsonSchemaChecker.cpp#L111

**Comment by brindosch** [comment]
nice, please merge the current index.html state :)

**Comment by b1rdhous3** [comment]
Oh i think i misclicked at the conflict resolvment haha ;)
Will do that and the .cpp changes this afternoon.

**Comment by b1rdhous3** [comment]
done

**Pull request merged**
