### PR TITLE
Transit translation system

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
 - As we are using html tags and js based translation i changed the lib to this one https://github.com/wikimedia/jquery.i18n
 - Created an en.json with ALL english strings, this is necessary for a proper working fallback
 - alle schemas no longer use hardcoded titles and appends, instead everything runs through the translation step
 - "edt_dev" = led device related, "edt_conf" = config related, "edt_eff" = effect schemas related, "edt_append" = all unit stuff, "edt_msg" = all internal validaten messages of editor + buttons.
 - all editor elements translated to DE
 - Currently the lib use your bowser language for translation
 - you could no longer change your language during runtime as the js based stuff is done when it's done, a browser reload would be the minimum task to enable it again and store the language in a cookie or in html5 local storage.
 - effconfigurator optimizations from @Paulchen-Panther . Buttons are now disabled if you shouldn't click them and all schemas are loading properly now
 - inside i18n/qqq.json you find a first part of a translation string docu. i consider to use https://translatewiki.net/ for translation or a similar service
 - logging page reworked with log level setting and auto scrolling enable/disable
 -  enjoy

### CODE REVIEW

**Comment by redPanther** [comment]
impressive changes!!!

**Comment by brindosch** [comment]
Thank you, i have already an idea how to implement language selection very smooth.
the default setting is "auto" when auto, it uses your browser locale. If this won't work for you or you want another language you could set it to "en", "de".... A Dialog "set your language" isn't necesssary anymore.

**Comment by redPanther** [comment]
as storage I would prefere webstorage http://www.w3schools.com/HTML/html5_webstorage.asp
(as long as we have only a few ui settings - currently only language and settings level (easy/expert) )

**Comment by brindosch** [comment]
I am not the greatest fan of this, cause if you switch device you need to re configure it again (if not "auto"). So i thought rather storing this in webConfig part to ship around this. You are always just one hyperion restart beside.
Simple comfort problem anyway.

**Comment by b1rdhous3** [comment]
So we need new "general settings" schemes?

**Comment by brindosch** [comment]
I don't think so. Hide danger settings in "expert" and you are fine to show webConfig part without the chance of messing around.

**Comment by b1rdhous3** [comment]
And add language and "view mode" to the webConfig settings?

**Comment by brindosch** [comment]
Did so.
unbenannt

**Comment by b1rdhous3** [comment]
Very nice!

**Comment by brindosch** [comment]
After i tested a little bit and thought about pro/con. I will just use html storage. The impact of loading time is high to wait until hyperion response and a hybrid solution doesn't work across diff browsers.

**Comment by redPanther** [comment]
browser storage rulz :-) then I can have different settings on desktop and tablet :-)

**Pull request merged**
