### PR TITLE
Travis osx support

### PR DESCRIPTION
**Pull request by WoLpH**
**1.** Changes

 - Improved build scripts for Travis
 - Fixed small coding error for non-linux platforms

Note that it doesn't fully work yet. The spidev issue is fixed but now it's stalling at v4l. Should I try modifying the cmake files to automatically skip v4l support when it's not available?

### CODE REVIEW

**Comment by redPanther** [comment]
v4l shouldn't be compiled ... only dummy in hyperiond. v4l = video for linux ... and it's only for linux as name said ...

In cmakelists for osx: SET ( DEFAULT_V4l2 OFF ) so this should be disabled. can you describe the problem a bit more?

**Comment by redPanther** [comment]
ok I see the problem, some cmake issue .. will look into it later. v4l shouldn't be compiled on osx

**Comment by WoLpH** [comment]
Ok, I've found the problem. Apparently the CMakeLists.txt said V4l2 instead of V4L2 (note the case)

**Comment by redPanther** [comment]
... I updated my message and in the moment I press update you wrote ;-)

**Comment by WoLpH** [comment]
Haha :)

Well, the next problem is the compilation of the main hyperiond source. Another non-linux issue. prctl.h is only available on linux as well

**Comment by redPanther** [comment]
good that we will see such things in future much faster ... did you have a clue how to solve?

**Comment by WoLpH** [comment]
I'm looking into a solution. I don't think there's a cross-platform solution available so I'll have to resort to a few macros I guess. Although Qt might have something. I'm investigating :)

**Comment by redPanther** [comment]
ifdef __APPLE__ is ok, we aren’t so strict in coding rules

**Comment by WoLpH** [comment]
Several solutions... none ideal. Do you have any preference?
http://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits

**Comment by redPanther** [comment]
number 9. I know kqueue from freebsd coding ... this should be the cleanest way. The pipe thingy looks interessting, but a bit more than a hack ;-)

**Comment by penfold42** [comment]
What's the zeroconf problem ?

**Comment by penfold42** [comment]
The code came from https://doc.qt.io/archives/qq/qq23-bonjour.html

And has this on the page;

Aside from the changes to the code above, we also need to link to the Bonjour library on platforms other than Mac OS X. This can be done by adding the following line to the profile.

!mac:LIBS += -ldns_sd

**Comment by redPanther** [comment]
great! big thx!!!!
and compiler warnings showed a bug:
https://travis-ci.org/hyperion-project/hyperion.ng/jobs/150435004#L737
I'll fix it in my next commit. :-)

**Comment by WoLpH** [comment]
Awesome! Great to have it all fixed and merged :)

**Comment by brindosch** [comment]
What a monkey work hehe. Thank you for fixing!

**Pull request merged**
