### PR TITLE
Rgbw fixes

### LINKED ISSUE #525: Error during make: invalid use of incomplete type
Hello,
unfortunately I'm getting an error when trying to build hyperion.ng

I used these command to build:
```
cmake -DPLATFORM=x86-dev -DCMAKE_BUILD_TYPE=Release ..

make -j5
```

This is the output of the error during make:
```
In file included from /home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/mocs_compilation.cpp:2:
/home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/EWIEGA46WW/moc_JsonClientConnection.cpp: In static member function ‘static void JsonClientConnection::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)’:
/home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/EWIEGA46WW/moc_JsonClientConnection.cpp:86:48: error: invalid use of incomplete type ‘class QJsonObject’
         case 1: { qint64 _r = _t->sendMessage((*reinterpret_cast< QJsonObject(*)>(_a[1])));
                                               ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/qt/QtCore/qobject.h:54,
                 from /usr/include/qt/QtCore/QObject:1,
                 from /home/wisp/hyperion.ng-git/src/hyperion.ng/include/utils/Logger.h:4,
                 from /home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/EWIEGA46WW/../../../../../libsrc/jsonserver/JsonClientConnection.h:8,
                 from /home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/EWIEGA46WW/moc_JsonClientConnection.cpp:9,
                 from /home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/mocs_compilation.cpp:2:
/usr/include/qt/QtCore/qmetatype.h:1970:1: note: forward declaration of ‘class QJsonObject’
 QT_FOR_EACH_STATIC_CORE_CLASS(QT_FORWARD_DECLARE_STATIC_TYPES_ITER)
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/EWIEGA46WW/moc_JsonClientConnection.cpp:9,
                 from /home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/mocs_compilation.cpp:2:
/home/wisp/hyperion.ng-git/src/hyperion.ng/build/libsrc/jsonserver/jsonserver_autogen/EWIEGA46WW/../../../../../libsrc/jsonserver/JsonClientConnection.h:31:9: note:   initializing argument 1 of ‘qint64 JsonClientConnection::sendMessage(QJsonObject)’
  qint64 sendMessage(QJsonObject);
         ^~~~~~~~~~~
```

On Arch Linux someone mentioned that it's because of a more recent version of cmake. I'm using cmake 3.13.1
https://aur.archlinux.org/packages/hyperion.ng-git/

### LINKED ISSUE #526: SK6812 Issue. strange colors and missing led
Hi,
I desperately need your help. That really makes me desperate right now.

I removed my old WS28xx from my TV to replace it with nice SK6812 RGBW. 
I connected the SK6812 to GPIO 18.

First of all the colors don't seem to be right. See photo.
And LED's are missing. I have 224 LED's in the setup and 55 of the LED's are not addressed.

Can anyone help me here?

Video:
https://youtu.be/KmLhOLSSFE0
Screenshots:
https://abload.de/img/dsc006904rcgv.jpg (Colors are not correct)
https://abload.de/img/screenshot2018-12-29ayqevh.png (Hyperion.ng configuration)

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Fix #525 compile error
Fix #526 rgbw config parsing bug
Add warm white white_algorithm for RGBWW leds

**2.** If this changes affect the .conf file. Please provide the changed section
```
    "device": {
        "whiteAlgorithm": "sub_min_warm_adjust"

```

**3.** Reference an issue (optional)
Fix #525 compile error
Fix #526 rgbw config parsing bug

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by RickDB** [comment]
Hi @penfold42 ,

Any chance you can rebase this on current master branch?

**Comment by penfold42** [comment]
Done - I think.

Travis is happy

**Comment by RickDB** [comment]
This does create a fairly large commit changelog as it also contains the whole rework, could you create a new PR from a fresh pull with these changes add after perhaps?

**Comment by penfold42** [comment]
Where are you seeing this ?

The commits tab on my phone looks clean

**Comment by tpmodding** [comment]
yep, mine too...

**Comment by RickDB** [comment]
On desktop it lists this one as a change:

https://github.com/hyperion-project/hyperion.ng/commit/d2628c39f9faf0323640c29764a60df5138997cf

git_log

**Comment by tpmodding** [comment]
image

**Comment by penfold42** [comment]
@RickDB - as a single merge commit i’d be ok with it if it were my repo
It’s a true reflection of the history - the actual files changes and the diff still Shows just what was changed.

Having said that, the rebase on master was quick so there’s another pull request in now.

Untested in real life as that was all done on the phone but should be fine if Travis is happy

**Comment by RickDB** [comment]
Ah I see now in the overview (was thrown off by the diff message), will close this one and check the other.

**Pull request closed without merging**
