### PR TITLE
H801

### PR DESCRIPTION
**Pull request by WoLpH**
**1.** Added support for the H801 ESP8266 based module: https://www.aliexpress.com/store/product/rgb-strip-WiFi-controller-1-port-control-15-rgb-lights-communicate-with-Android-phone-to-dim/1487659_32301423622.html

**2.** Do we have a .conf file?

**3.** As discussed earlier on slack :)

### CODE REVIEW

**Comment by brindosch** [comment]
Cool! Thank you. Need to buy one, just for fun :)

**Comment by WoLpH** [comment]
It's a fun little device. I'm not sure how stable it is yet but I'm going to find out soon. 

If it turns out to be rubbish I'll just flash it with the atmoorb firmware. 

Ps: I should note that this pull request includes #251

**Comment by redPanther** [comment]
Uups I overlooked your ps. Can you merge with master?

**Comment by redPanther** [comment]
.. I resolved the merge ...

**Comment by WoLpH** [comment]
Thanks @redPanther :)

I didn't get to it yet. I'll give it a testrun to see if everything it still working.

**Comment by WoLpH** [comment]
Works perfect :)

Thanks for the help

**Comment by starkillerOG** [comment]
Looks cool, I am planning on buying a H801 ESP8266 based module with a 5m led strip to mount under my couch as addition to my Hyperion (lightberry HD) behined my TV.
Would it be easy for me to manually add this code to the stable latest version of hyperion (that i am running), or does it have a lot of depandancies?
Do you have any idea when this code will be implemented in a new stable build?
(I would rather not update to the dev version because I am running my hyperion 24/7 on my Pi and don't want to have issues).

**Comment by WoLpH** [comment]
After testing the code a bit more I'm not recommending this code and the H801 with stock firmware anymore.

This code is sadly not 100% stable it seems but that's not the biggest problem. The H801 doesn't have a stable/reliable connection if you keep the stock firmware. I reflashed mine with a custom version of the AtmoORB (which is supported by all current hyperion versiosn btw): https://github.com/ambilight-4-mediaportal/AtmoOrb/tree/master/ESP8266/ESP8266_H801

It does require a tiny bit of soldering to get the headers on and reflash the thing, but it's the only way I've managed to get it to stay reliable. The alternative is power cycling the H801 once a day.

**Comment by penfold42** [comment]
The firmware from http://forkineye.com/espixelstick/ works well.

I've built half a dozen and used them with both DMX/e.131 protocol and also with udp raw (if you use my fork)

**Comment by starkillerOG** [comment]
@WoLpH thank you for your verry quick reply and for the heads up!
I have no experiance with reflashing things like this, but I will learn soon enough.
Am I correct i will need to buy a "USB to TTL Serial Cable" and can I just buy a 40Pin Male header strip and cut out the 4pin and 2pin lenght i would need?

Do you recommand using this H801, or is there a simpler way to achieve what I want: bassically just a led strip I can wirelessly connect to my hyperion on my Pi. (Philips Hue lightstrip would bassicaly be it, but I think the colors of an APA102 Led strip are better especially the green and i think the response time of a Philips Hue will be slower).

**Comment by starkillerOG** [comment]
@penfold42  Did you use that firmware on the ESPixelStick itself or on the H801?

**Comment by penfold42** [comment]
Home made hardware.

It might not be suitable for you - I just noticed the h801 seems to be designed for discrete multi channel leds - the espixelstick is designed for ws2811 led strips.
There is initial support recently added for spi based led strips but I don't think the apa102 is there yet.

**Comment by WoLpH** [comment]
@starkillerOG the H801 hardware is unbeatable for that price and has been really reliable for me so far. 

The only downside is that you need to solder the headers yourself, but that's a small price to pay I think. 

And yes, a simple usb to ttl cable will work. Just look for usb serial or usb ftdi on AliExpress.

**Comment by penfold42** [comment]
I just ordered one to play with - this might become my standard general purpose esp8266 project board/case.

It looks like all the right pins are easily available for both spi based led strips and ws2812 style leds.

**Comment by WoLpH** [comment]
@penfold42 which pin would you use for the SPI based led strips? While not impossible, it doesn't appear too easy to hook up SPI based led strips (unless you want to repurpose the status leds on the board itself as SPI pins).

If you're simply looking for something to control SPI than I'd go for a Wemos board (https://wiki.wemos.cc/products:d1:d1_mini) instead, optionally with a WS2812B RGB shield for easy debugging: https://wiki.wemos.cc/products:d1_mini_shields:ws2812b_rgb_shield
Those are cheaper and easier to use if you don't need the mosfets

**Comment by penfold42** [comment]
Thanks for the suggestion - I've build lots of boards with esp-01 and esp201 modules in the past but the case and power supply make this nicer!

I need to see how easy it is to replace the hc245 with an hct245 at 5v - there's your level shifter done.

SPI is on gpio 12,13 and 14 which are easily accessible on the blue, green and white1 mosfets.

Gpio2 (for ws2812) is the serial1 TX (labelled as RX on the header I believe)

**Comment by WoLpH** [comment]
Ah, like that. Yes you can circumvent the mosfets fairly easy if you wish and it's indeed a nice total package which can handle quite a bit of power :)

Replacing the HC245 is not impossible but you'll probably need a hot-air rework station to do it:
https://eryk.io/wp-content/uploads/2015/10/IMG_2347.jpg

**Comment by starkillerOG** [comment]
@WoLpH & @penfold42 Thanks a lot for your help, I am going to buy this H801 and I think it will be a fun project.

Do you recommend a specific RGB LED strip you know is good for this controller?
I was looking to buy one of these two 5050 led strips:
[5M IP65 RGB](https://nl.aliexpress.com/item/5M-RGB-RGBW-5050-LED-strip-Light-Waterproof-IP20-65-67-DC12V-SMD-60Leds-M-300/32672613969.html?spm=a2g0z.10010108.1000013.1.NcXVdp&traffic_analysisId=recommend_2088_1_82199_new&scm=1007.13339.82199.0&pvid=ebb3800e-8db4-4dc1-bec7-ebac2257ca01&tpp=1)
[RGB Waterproof](https://nl.aliexpress.com/item/5M-Black-PCB-RGB-5050-LED-tape-White-Warm-White-Blue-LED-Strip-SMD-5050-DC12V/32717254787.html?spm=a2g0z.search0104.3.108.kpdb66&ws_ab_test=searchweb0_0,searchweb201602_4_10152_10065_10151_10068_10130_10209_10084_10308_10083_10080_10082_10081_10301_10110_10178_10137_10111_10060_10112_10113_10155_10114_10154_438_10056_10055_10054_10310_10182_10059_100031_10099_10078_10079_10103_10073_10102_5360020_10052_10053_10142_10107_10050_10051,searchweb201603_16,ppcSwitch_5&btsid=20d44607-5e2a-447a-ba32-9693e865a5fb&algo_expid=7ef1f8bf-5698-458e-aeb2-f063f7918e7a-12&algo_pvid=7ef1f8bf-5698-458e-aeb2-f063f7918e7a)

Thanks again for all your help!

**Comment by penfold42** [comment]
Note that the h801 as shipped is NOT designed to drive addressable strips (where each led can be a different colour).

If you're soldering skills and general electronics are at least modest, it doesn't look hard to modify from the photos.

**Comment by WoLpH** [comment]
Personally I would go for 24v led strips because it allows you to use much longer strips without visible differences in color between the begin and the end of the strip due to power loss.

Beyond that... it depends what you're going to use them for. As far as I know we don't have any properly working Hyperion code to actually use an RGBW/RGBWW strip so it will use RGB only for Hyperion, but if you're going to use it as regular lighting as well than RGBW/RGBWW might still be convenient.

**Comment by penfold42** [comment]
The sk6812 driver supports RGBW mode but it's pretty crude.
There are 2 transforms :
- white off. just sets W=0
- subtract_min which sets W=min(r,g,b) and then subtracts that from each channel.

Ideally the internal colour adjustments would do this in a smarter logarithmic and gamma aware way, but internally Hyperion uses a simple RGB888 colour space so it won't happen any time soon.

**Comment by WoLpH** [comment]
Ah, I stand corrected :)

I would vote for HSV, that would make dithering much easier as well

**Comment by penfold42** [comment]
It's unlikely we'd move away from RGB as all display capture is RGB and we'd possibly waste a lot of cycles.

I would like to move to 16bit RGBW internally - more precision for the colour manipulation and then the temporal dithering would be cool for the leds that support a good refresh rate

**Comment by starkillerOG** [comment]
@WoLpH & @penfold42 I have been looking into a second project to control hyperion with a color wheel remote to make it easier to use as ambient lighting when i don't watch a movie. I think it would be reletively easy to implement.

I have placed a post on the [Hyperion forum](https://hyperion-project.org/threads/hyperion-remote-control.207/). Maybe one of you is intrested?

**Comment by WoLpH** [comment]
@rickdb might be interested as well, he's created a few android apps to
control his lights as well.

**Comment by RickDB** [comment]
@WoLpH 

Actually @BioHaZard1 has created an android app already, in alpha but works well with hyperion.ng :

https://hyperion-project.org/threads/hyperion-hypercon-android-development.244/page-4#post-6999

**Comment by starkillerOG** [comment]
@WoLpH & @RickDB thanks for the quick responds!

To be clear, I am talking about implementing a physical hardware color wheel remote and not a software application. But of course if you already created a software application this schould be a lot easier.

for conveniance this is the post i placed on the hyperion forum:

_I have been looking to control my hyperion system with a colorwheel remote for a while.
When I watch movies the system performs outstanding, but I also want to use it as ambiant lighting if my TV is off._

_I found that Milight makes nice 2.4GHz color wheel remotes that are sold separately for about $8,- ([AliExpress](https://nl.aliexpress.com/item/Mi-Light-Wireless-2-4G-4-Zone-RGBW-Touchtone-remote-control-for-led-strip-RF-Wifi/32636110125.html?spm=a2g0z.search0104.3.2.8m3Uxp&ws_ab_test=searchweb0_0,searchweb201602_4_10152_10065_10151_10068_10130_10209_5430020_5410020_10307_10301_10137_10060_10155_10154_10056_10055_10054_10059_100031_10099_5400020_10103_10102_10052_10053_10142_10107_10050_10051_5380020_5390020_10084_10083_5370020_10080_10082_10081_10178_10110_10111_5420020_10112_10113_10114_10312_10313_10314_10315_10316_10078_10079_10073,searchweb201603_19,ppcSwitch_5&btsid=458a4471-e936-42eb-94c7-60eb89e0bc2a&algo_expid=dda13335-cc53-49c8-b7eb-9c4fd0800145-0&algo_pvid=dda13335-cc53-49c8-b7eb-9c4fd0800145&transAbTest=ae803_2))
I also found this github project: [esp8266_milight_hub](https://github.com/sidoh/esp8266_milight_hub/wiki/Using-Milight-Remote-with-HomeAssistant), that is able to listen to the remote signals using a cheap NodeMCU + ESP8266 and a NRF24L01+ (together about $4,-) and decode the signals and sent them to HomeAssistant. (some more about the signal structure can be found in [this blog](http://blog.christophermullins.net/))._

_I think it would be possible to edit the relevant parts of the esp8266_milight_hub project code and use it to receive the signals from the remote and send commands to hyperion to turn on/off, to change color and to change the brightness._

_Unfortunately I am completely new to using electronic boards like esp's and NodeMCU's and am not familiar with how to program them.
Maybe there is someone who would like to give this a go?_

milight remote

**Comment by WoLpH** [comment]
Personally I think adding a milight to hyperion bridge might be the easiest solution here. Simply receive and parse the milight commands and forward to hyperion. 

If it's not too hard (I'm unfamiliar with the milight protocol) we could even add this to hyperion naively.

**Comment by RickDB** [comment]
@WoLpH Have the latest miilight kit here running for cheap outdoor lights combined with Domiticz, lemme know if you want to play around with it instead of going by the spec sheets :)

Miilight stuff is great and while the Chinese vendors all call them that there can be subtle difference in implementation but nothing to serious so seems good for long term, native Hyperion support would definitely be very nice and we might be able to borrow some domoticz code for this to save time as that is C++ as well.

**Comment by penfold42** [comment]
My H801 arrived last week and I've nearly finished adding PWM support to ESPixelStick.
So, if you want to use single colour strips that have RGB inputs, this will work with Hyperion.

The HC245 has a bit less than 5v on its VCC so should work as is for a level shifter for SPI strips. I don't own any so I can't directly test.

On the physical colourwheel:
I have a branch of ESPixelStick that has a rotary encoder on it. Right now it has 7 modes to adjust R, G, B, H, S, V (and off/use network data)
It wouldn't be hard to make it send json to Hyperion.

**Comment by starkillerOG** [comment]
@WoLpH & @RickDB do you have time to look into this milight remote?

Thank you @penfold42 my H801 and a RGB single color stip are already under way, I ordered them a few weeks ago. I think I will try the AtmoOrb software first but if that does not work I will certainly try the ESPixelStick software.

**Comment by starkillerOG** [comment]
I found [this Github project ](https://github.com/MrBramme/Mqtt-Hyperion-Remote) that already implemented an MQTT hyperion remote. The [esp8266_milight_hub
](https://github.com/sidoh/esp8266_milight_hub/wiki/Using-Milight-Remote-with-HomeAssistant) project also uses MQTT to pass the received commands from the milight remote through to third party software. So these two projects might be linked together to control Hyperion with the milight remote based on the MQTT protecol instead of the JSON interface.

Do you think that might work @WoLpH & @RickDB?

**Comment by starkillerOG** [comment]
@WoLpH Finally got time to implement and stated working on these projects.
I got the Milight remote working with Hyperion and it works verry nice.
I can set color (set Hue set Sat and set Lum), turn 5 diffrent groups of lights (5 diffrent Hyperion instances) on/off and change between HDMI grabbing mode and solid color mode on the hardware remote.

I used the esp8266_milight_hub software to get the remote signals, used Mosquitto as the MQTT broker to communicate the messages and used Eventghost with some phython code to translate the messages to Hyperion commands that I sent to the JSON interface to control Hyperion.

More information is in [this discussion](https://github.com/sidoh/esp8266_milight_hub/issues/107).

The only disadvantage is that I now need an extra device (in this case windows PC) that is running Mosquitto and eventghost to work as a bridge between the milight hub and hyperion.
I do not know how much work it would be to translate my phython code to integrate it in Hyperion, but it would be verry need to get rid of that extra device running Mosquitto and eventghost.

If your intrested in my phython code, just sent me a message and I will clean it up a bit and translate my comments to englisch.

Thanks for all your help!

**Comment by WoLpH** [comment]
For some reason I didn't see the earlier notifications here, sorry about that.
Glad to see you got it working :)

With MQTT it's failry easy to attach all sorts of devices, you can probably even link it up to something like homekit-bridge to add apple homekit support

**Comment by starkillerOG** [comment]
@WoLpH I just posted my [code I used here](https://github.com/sidoh/esp8266_milight_hub/issues/107)

Would be great if you would have time to see if this could be implemented in hyperion to run everything on the rasberry Pi.

**Comment by WoLpH** [comment]
@starkillerOG looks good :)
A quick google actually got me this as well: https://github.com/MrBramme/Mqtt-Hyperion-Remote

But native mqtt support for hyperion would be a very nice feature, not sure how feasible it is. I'm using mqtt within my own home quite a lot but I'm far from an expert on the matter

**Comment by penfold42** [comment]
Let’s continue discussion at #483

**Comment by starkillerOG** [comment]
@WoLpH I am now trying to get the H801 working with the [atmo orb firmware](https://github.com/ambilight-4-mediaportal/AtmoOrb/tree/master/ESP8266/ESP8266_H801).

I have some trouble connecting the H801 with my wifi router. How does that work?
Are you supposed to fill in the SSID and the password of the wifi you want to connect to in the firmware itself?

This is the relevant code of the firmware I thought I was supposed to fill in the ssid and password:

```
// Network settings
const char* ssid = "ssid"; // WiFi SSID
const char* password = "password"; // WiFi password
const IPAddress multicastIP(239, 15, 18, 2); // Multicast IP address
const int multicastPort = 49692; // Multicast port number
```

Thank you for your help!

**Comment by WoLpH** [comment]
Yes, you're correct. That's currently the only option to set your wifi ssid and password. Only the first 2 need to be changed.

I've done a little bit of work to make this configurable through a web interface but I've found SPIFFS to be unreliable on cheap ESP8266 chips with limited memory.

You could try and merge in this EEPROM settings storing code though: https://github.com/chriscook8/esp-arduino-apboot/blob/master/ESP-wifiboot.ino

**Comment by penfold42** [comment]
I added PWM support to espixelstick firmware and this works great on the h801

**Comment by starkillerOG** [comment]
@WoLpH Thanks, I got it all working perfectly.

The only thing I noticed is that the ESP is still broadcasting its own "wifi network". It shows up in my available wifi networks as ESP_xxxxxx where xxxxxx is the ID number of my ESP. But it is alreay connected to my wifi network and also shows up in my router and has its own IP adress. I can also connect to this unsecured ESP_xxxxxx "wifi network".

Why is it still broadcasting its own network?
Can I disable this somewhere in the code?

**Comment by starkillerOG** [comment]
Found the solution for the ESP broadcasting it's own network.

Just symply add this line in the code for the H801:
`WiFi.mode(WIFI_STA);`
I placed this line just above the already existing line:
`WiFi.begin(ssid, password);`

This sets the wifi mode of the ESP to "workstation" instead of the default "workstation + acces point".
(The 3 available modes are: WIFI_AP, WIFI_STA, or WIFI_AP_STA, [see this discussion](https://www.reddit.com/r/esp8266/comments/3cx2xh/esp826601_broadcasting_ssid_after_programmed_with/))

**Comment by WoLpH** [comment]
I never even knew it did that to be honest :P

Good to know, that should be part of the firmware package at some point, as soon as time is a less limiting factor that is

**Comment by starkillerOG** [comment]
@WoLpH I already made a [Pull request](https://github.com/ambilight-4-mediaportal/AtmoOrb/pull/5) to add this line for the ESP H801 AtmoOrb firmware.
I think you can simply accept the pull request, but not sure how this works, I am fairly new to GitHub.

**Comment by WoLpH** [comment]
Yes, I see. Awesome, I've merged it :)

**Comment by starkillerOG** [comment]
@WoLpH @RickDB I improved my initial python code for the Hyperion color wheel remote to include an internal MQTT listener based on the paho python module.
Therefore Eventghost is no longer needed for this Hyperion color wheel remote.
I have the python script running on the same rasberry pi that runs my hyperion instances and is running openelec.

The code respondse pretty fast and works nice in my oppinion.
For the milight color wheel remote it works greath, but it could probablly also be used for other ways of controlling Hyperion through MQTT.

[My code is posted here.](https://github.com/sidoh/esp8266_milight_hub/issues?utf8=%E2%9C%93&q=hyperion)

Maybe it is also usefull for someone else.

**Comment by WoLpH** [comment]
Nice @starkillerOG, that looks quite good :)

I think you wanted to link to this instead btw: https://github.com/sidoh/esp8266_milight_hub/issues/107

**Pull request merged**
