### PR TITLE
Introduce Dark Mode

### LINKED ISSUE #744: Dark Mode
## Feature request
A toggle to have a Dark-Mode would be nice

#### What problem does this feature solve?
My crying eyes at night
#### What does the proposed API look like?
none
#### How should this be implemented in your opinion?
With a toggle 
#### Are you willing to work on this yourself?
Nooo maybe @b1rdhous3 or @brindosch

### PR DESCRIPTION
**Pull request by b1rdhous3**
**Summary**

Introducing new Dark Mode. You can switch with a button on top. The value if dark mode is set or not is stored in localStorage on Client Browser. 
Resolves #744 

Some OS (iOS or Mac OS e.g.) can give the browser an information if system wide dark mode is set or not. If the OS shares this information, webui is set automatically to the mode. Manual overwrite is still possible by pressing button on the webui. This is valid as long the session in the client is open.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

Bildschirmfoto 2020-03-29 um 13 54 43

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by b1rdhous3** [comment]
I can't assign someone for review. Can someone please assign @tpmodding?

**Comment by Paulchen-Panther** [comment]
Merge?

**Comment by b1rdhous3** [comment]
Someone tested? 
@tpmodding eg?

**Comment by Paulchen-Panther** [comment]
I couldn't find any problems.

**Comment by tpmodding** [comment]
nope, hau raus...im notfall gibtsn fix :-)

**Pull request merged**
