### PR TITLE
Razor Chroma Support - Initial version

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

Razor Chroma Support - Initial version.
Note: Currently only the first LED is mapped to the Razor device.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@HutchMD Thank you very much for testing and providing detailed feedback!

> I found that multiple LED's inside my Mouse were mapped as one single LED.

Yes. currently only the first LED is send to the Razer device.
I originally asked @tpmodding to pass this message...
Nevertheless, what is the need from a Razer user perspective?
Is one color for one area of screen enough or does it provide value to reflect multiple areas of the screen to the Razer device.
I would not like spending effort for detailed mappings, if no one would see benefit for it (and is happy with one color).

> found that although the colors responded correctly on my mouse, sometimes, it would flicker blue

Unfortunately, I do not have a Razer device myself and only testing with a Razer provided emulator.
I tried multiple things, but was not able to reproduce on my end.
Maybe we find additional Razer users which might test on a different  setup.

If I put a background in Synapse via Chroma Visualiser, either the background is shown (no hyperion) or hyperion (no background). Do you have the order of apps the following way (hyperion before Chroma Visualisier)?

image
or do you run a different setup?

In addition, did you have this symptom only while playing videos via the WebInterface-capture or
did you see the effect while running static colors or effects?

If you play e.g. the effect "Led Test", does the problem occur, too?

image

Many thanks in advance!

**Comment by HutchMD** [comment]
> Nevertheless, what is the need from a Razer user perspective?
> Is one color for one area of screen enough or does it provide value to reflect multiple areas of the screen to the Razer device.
> I would not like spending effort for detailed mappings, if no one would see benefit for it (and is happy with one color).

Personally, I don't really use Razer Chroma for any exciting lighting, I mainly have a blue 'breathing' pattern, or sometimes a blue static (solid) color. (I only have 1 Razer Mouse)

If someone were to use Hyperion and had both a Razer Chroma full keyboard and mouse, I would imagine that it would be nice for the mouse to be mapped to one LED for the bottom-right corner of the screen (maybe 15% of the bottom-right corner?), where as the keyboard would be a gradient mapped for maybe 85% of the remaining bottom of the screen to give that ambient lighting effect that Hyperion was made for.


> 
> If I put a background in Synapse via Chroma Visualiser, either the background is shown (no hyperion) or hyperion (no background). Do you have the order of apps the following way (hyperion before Chroma Visualisier)?
> or do you run a different setup?
> 

I have the default Synapse driver , but unfortunately I do not have any of the Chroma Modules such as Chroma Connect/Studio/Visualizer.

In the Mouse settings, there are 'quick effects' that I use for Breathing, or Static (solid color).
I don't use the Advanced Effects tab that require the Chroma Studio Module.

Synapse Mouse

Synapse Mouse Quick Lighting


> In addition, did you have this symptom only while playing videos via the WebInterface-capture or
> did you see the effect while running static colors or effects? 
> If you play e.g. the effect "Led Test", does the problem occur, too?
> 

Correct, The flickering symptom happens mainly when the colors on screen are changing, or if the screen is black. This happened with videos, games, as well as the LED Test in the webGUI as you pictured. It doesn't happen for every single color change, it's more like it flickers to the Razer Default once every... 10-15 seconds? Hard to give a specific time-frame, but it looks like it's conflicting with my default Razer setting.

**Comment by Lord-Grey** [comment]
@HutchMD Thanks for sharing additional insights!
Let me check, if I could disable the effect configured for the mouse (temporarily) before sending hyperion data.
As the emulator does not provide customization screens for the individual device types (as per your screenshot),
I might need your help again...

For the one or multiple LED mappings, let me think about it what is possible and (easily) configurable.

**Comment by HutchMD** [comment]
> I might need your help again...
Let me know what I can help with, I only have 1 Chroma Mouse.

> For the one or multiple LED mappings, let me think about it what is possible and (easily) configurable.
For multiple LED mappings, you're going to need someone else who has a Razer Chroma-capable Keyboard AND Mouse to help you test.

**Comment by juanesf** [comment]
hello, how can i get the test package for windows i can't compile it.

**Comment by Lord-Grey** [comment]
> hello, how can i get the test package for windows i can't compile it.

I just merged the master which kicked-off a build for the PR test packages.

You can access all test builds here via the artifacts
https://github.com/hyperion-project/hyperion.ng/pull/1054/checks?check_run_id=1524189547

The latest Windows one you find here:
https://github.com/hyperion-project/hyperion.ng/suites/1635723950/artifacts/30234338

**Comment by juanesf** [comment]
hi again, i am trying to use hyperion with WraithPrism on Razer with no success. here captures and log:
[hyperion-razer-log.txt](https://github.com/hyperion-project/hyperion.ng/files/5673545/hyperion-razer-log.txt)
[system_information-hyperion-razer.txt](https://github.com/hyperion-project/hyperion.ng/files/5673546/system_information-hyperion-razer.txt)
razer-devices
razer-apps
hyperion-control

**Comment by juanesf** [comment]
i changed the razer device from chromalink to keyboard then back to chromalink but the hyperion log still shows keyboard:

` 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:148:LedDevice::init()) deviceConfig: [{}]
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:407:LedDevice::setLatchTime()) LatchTime updated to 0ms
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:428:LedDevice::setRewriteTime()) Refresh interval = 1000ms
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:434:LedDevice::setRewriteTime()) RewriteTime updated to 1000ms
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:57:LedDeviceRazer::init()) DeviceType   : unspecified
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:58:LedDeviceRazer::init()) LedCount     : 1
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:59:LedDeviceRazer::init()) ColorOrder   : RGB
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:60:LedDeviceRazer::init()) LatchTime    : 0
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:61:LedDeviceRazer::init()) RefreshTime  : 1000
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:67:LedDeviceRazer::init()) Hostname     : localhost
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:68:LedDeviceRazer::init()) Port         : 54235
 2020-12-10T14:59:14.758Z [hyperiond LEDDEVICE] (DEBUG) (LedDeviceRazer.cpp:72:LedDeviceRazer::init()) Razer device : keyboard
 2020-12-10T14:59:15.118Z [hyperiond COMPONENTREG] (DEBUG) (ComponentRegister.cpp:36:ComponentRegister::setNewComponentState()) LED device: enabled
 2020-12-10T14:59:17.105Z [hyperiond WEBSOCKET] (DEBUG) (JsonAPI.cpp:1054:JsonAPI::handleLoggingCommand()) log streaming activated for client ::1`

**Comment by Lord-Grey** [comment]
@juanesf Thanks for testing.  It looks like that there is a problem with this build.
I would need to have a closer look.

**Comment by Lord-Grey** [comment]
@juanesf I did some corrections. Could you try again?

Latest build you find here:

https://github.com/hyperion-project/hyperion.ng/pull/1054/checks?check_run_id=1533169908

**Pull request merged**
