### PR TITLE
Update submodule references - rpi_ws281x to @hyperion-project fork

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Update submodule references - rpi_ws281x to @hyperion-project fork
It looks like I also bumped the protobuf to a later commit with some cmake fixes

**2.** If this changes affect the .conf file. Please provide the changed section
nope

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
ah of course the changes from redpanther

**Comment by penfold42** [comment]
I've tested briefly with sk6812rgbw PWM on pi3

**Comment by penfold42** [comment]
Also tested with ws2812 on pi3

**Comment by brindosch** [comment]
As far as i remember Pi1 was criticial with ws281x device

**Pull request merged**
