### PR TITLE
Fix issues #1022, #1019, #997, #993, #992, #976, #969, #964, #980

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

As mentioned in the title.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
Fixes: #1022, #1019, #997, #993, #992, #976, #969, #964, #980

### CODE REVIEW

**Comment by dermotduffy** [comment]
WOAH @Paulchen-Panther . Thank you!

Doing a test build right now and will attempt to verify each fix (may take a while...).

**Comment by dermotduffy** [comment]
Hello all -- Any chance we can get this reviewed and/or merged in? This fixes quite a range of API usability issues in a single PR, so very much looking forward to it!

**Comment by Paulchen-Panther** [comment]
Since you have confirmed the functionality in every issue, I just put myself first in the PR list and merge. 😄

**Comment by dermotduffy** [comment]
Thanks again @Paulchen-Panther !

**Pull request merged**
