### PR TITLE
Use QNetworkAccessManager to handle Kodi requests

### PR DESCRIPTION
**Pull request by gismo2004**
Kodi does not allow to send "commands" via method GET and using javascript leads to "Access-Control-Allow-Origin", thus create a proxy to handle our requests.

**1.** Tell us something about your changes.
I'm no coder ;-)

**2.** If this changes affect the .conf file. Please provide the changed section
-
**3.** Reference an issue (optional)
https://github.com/hyperion-project/hyperion.ng/issues/490

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Thank you for your PR. It seems you are a coder - now :)
Sad that kodi does no longer accept these request. While i created this it was more a bonus. Using Hyperion as forwarder is possible, but i dislike it. Another idea is to use Kodis Websocket capabilities which is implemented at all browsers (http://kodi.wiki/?title=JSON-RPC_API#WebSocket)

That way you can send json formatted messages to Kodi without any restrictions from the ui (http://kodi.wiki/view/JSON-RPC_API/v8)

May you probably have a look?

Thank you
brindosch

**Comment by gismo2004** [comment]
That sounds like a new challenge :-D --> will definitely try to get this working. 

But it will take some time, because of family work and so on. So if it is no matter of time, i will push a new PR some day...

BTW: i'm from Austria, so if you prefere to write Deutsch... 
cheers

**Comment by brindosch** [comment]
Great, time doesn't matter.
If you have questions or need hints just ask. We can switch to german, in case it's getting too technical :)

Thank you
brindosch

**Comment by MartB** [comment]
I used the kodi websocket in the past it is pretty powerful im wondering if we should implement it into hyperion to get additional informations like playback start/stop events without the need for the kodi addon ?

**Comment by brindosch** [comment]
Well, the situation is this

- kodicheck has been removed from Hyperion, because there is no reason to provide a _optional_ part at the core which can be simply controlled now via API
- The replacement for this is available now as Kodi Addon and will be pushed to the kodi repository during release https://github.com/hyperion-project/hyperion.ng/issues/474
- However, Kodi is not the only software that wants to be used together with Hyperion. It is currently impossible to install optional services that build a bridge between your wanted service and Hyperion or any other simple eventing like time based triggers. If think it's out of discussion to blow up the core for every task the user wishes. Which is the reason why i implemented a simple plugin system. You've probably seen it at my rework branch.

This pr wants to implement a picture pusher to be used together with the ui calibration wizard.

**Comment by MartB** [comment]
We could technically merge the kodi img grabber and your addon from #474 in a later stage when the reworks on the server are done. However about that websocket part, i have an implementation lying around for this from an old project that i could adapt.

However the websocket api seems to not display the next image until the user manually presses the right mouse button (whatever that action is in kodi).

@gismo2004 did you encounter the same issue ?

**Comment by gismo2004** [comment]
Hi,

sorry for the late response. I had some time to play around with WS. 
It works in principle.

But the current implementation is definitely not the final one. I need to find a way to create a kind of semaphore, since all that stuff is async and i don't want to block the scripts with the requests to Kodi.

Please let me know, what you think about the current stuff, and feel free to blame everything you don't like. as i said, I'm no coder, and i just learn how to work with stuff like that :-)

Cheers

**Comment by MartB** [comment]
That does look like a solid start already but yeah we need to do this in a event driven way.

I adapted some old scripts of mine for hyperion ng they are not the best but maybe they inspire you to something new haha.

https://github.com/MartB/hyperion.ng/commit/4c7ccb756ebb0fe86314ce69882736e63300f5c4

**Comment by gismo2004** [comment]
@MartB i would say i don't need a inspiration --> looks like pushing your commit makes much more sense and less work ;-)
Is there a reason why not using yours?

**Comment by MartB** [comment]
@gismo2004 i didnt want to steal your pull request 🙈 
The connection logic is a bit wonky (error handling) and it could probably use some further testing.
If you see any room for improvement go ahead and comment on my code and when i have time i will get to it.

**Comment by gismo2004** [comment]
@MartB My pull request has been created with the knowledge: Kodi is not working. Now that i see you already have a very nice implementation, and i am far away from creating cool stuff like this, you definitely not stealing something :-D 
Means, that i hope you are pushing your stuff, because it works as expected. There is just one thing i have seen, and i have commented on your commit.

If all agree with MartB's implementation i would like to close this PR?

cheers

**Comment by RickDB** [comment]
@gismo2004 just to be sure we can close this one without merging?

**Comment by gismo2004** [comment]
@RickDB YES sir :-)

**Pull request closed without merging**
