### PR TITLE
Release preparation

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
I know this is the PR section and not the forum but I wanted to start talking about it.
With these changes, we can create releases in Azure and release them on GitHub as needed. Now for my questions. Which version number do we want to start with? Which tags do we want to create? Who and when should the builds be created? Only binary files or just packed? Which platforms and which operating systems? ......

We should inquire with talking!

### CODE REVIEW

**Comment by RickDB** [comment]
Yeah the sooner we get the release ironed out the better 👍 

**Which version number do we want to start with?** 

Would start with 1.0

**Which tags do we want to create?** 

`Beta `tag I think as we passed the `Alpha `stage already, `release ` tag for when it's production ready.

**Who and when should the builds be created?** 

If possible tag based, for instance when we add a `Release` tag it autobuilds and publishes so that we don't have to worry about updating mirrors like with our current Sourceforge system.

**Only binary files or just packed?**

Would only do binary packs as that is most used.
Right now for Hyperion vanilla we have the auto install scripts so we can re-purpose these for installers if needed:

https://hyperion-project.org/wiki/Installation-with-command-line

**Which platforms and which operating systems?**

Raspberry 1-3
X86
OSX
Certain Docker images

That are the mayor ones I think which use Hyperion we can always expand of course :)

**Documentation and site info updates**

We also need some sort of quick start manual to get people going, with the web interface everything is much more clearer so would be the first steps:

run installer -> point them to web ui -> couple pointers for every section

Most of the config and naming logic stayed the same so should be ok for existing users.

Site wise the forum hasn't got a lot of attention so we discuss how we want to present it, as in move the Hyperion Vanilla to a less prominent area etc..
New forum sections for sure as to make a clear distinction between vanilla and .ng

**Comment by b1rdhous3** [comment]
> Yeah the sooner we get the release ironed out the better 👍

This is also my opinion. The current state is fine for beta.

> 
> **Which version number do we want to start with?**
> 
> Would start with 1.0

Would also start with 1.0beta. I would like to keep the .ng in the name as it stands for the "complete new" version of hyperion. 

> 
> **Which tags do we want to create?**
> 
> `Beta `tag I think as we passed the `Alpha `stage already, `release ` tag for when it's production ready.
> 
> **Who and when should the builds be created?**
> 
> If possible tag based, for instance when we add a `Release` tag it autobuilds and publishes so that we don't have to worry about updating mirrors like with our current Sourceforge system.
> 
> **Only binary files or just packed?**
> 
> Would only do binary packs as that is most used.
> Right now for Hyperion vanilla we have the auto install scripts so we can re-purpose these for installers if needed:
> 
> https://hyperion-project.org/wiki/Installation-with-command-line

I would also tend to modifing the install script and let the user use this or docker images. 
Since .ng is creating a config on it's own it should also be very straight forward. But in installation there should be a possibility to thange the port .ng is running on since it could be already used and the initial config should be created too in this case.

> 
> **Which platforms and which operating systems?**
> 
> Raspberry 1-3
> X86
> OSX
> Certain Docker images

Yep.

> 
> That are the mayor ones I think which use Hyperion we can always expand of course :)
> 
> **Documentation and site info updates**
> 
> We also need some sort of quick start manual to get people going, with the web interface everything is much more clearer so would be the first steps:
> 
> run installer -> point them to web ui -> couple pointers for every section
> 
> Most of the config and naming logic stayed the same so should be ok for existing users.
> 
> Site wise the forum hasn't got a lot of attention so we can discuss how we want to present it, as in move the Hyperion Vanilla to a less prominent area etc..
> New forum sections for sure as to make a clear distinction between vanilla and .ng

I think this is the biggest challange before releasing the real 1.0. We should modify the forum. We should point more to NG. We should archive the most topics of the old wiki and write some new articles. Also we have to clean up the webui a bit. 
Then we should point new users to ng and not to vanilla. We should encourage version change for today users. To do this we have to sort the forum and sources new. 

I am excited for the final release :)

**Comment by Paulchen-Panther** [comment]
@RickDB @b1rdhous3 Thanks for your detailed answers. I already worked on your suggestions today. Will come next week to get everything done.

**Comment by tpmodding** [comment]
hey gus, nice to see the next steps and the progress...
what about all the additional dependence things we need for kodi?
do we wonna add them as "binary + *elec dependence" or "*elec-build"?

**Comment by RickDB** [comment]
Kodi addon should work the same, we don't have an active maintainer for the addon however but our API entries remained the same at least.

For *-Elec binary builds those were build by someone in their community or team afaik :)

**Comment by b1rdhous3** [comment]
Maybe we sould do a post in the forum to ask some power users from ng and which are activ in the forum for help. I am thinking of documentation etc. 
I think we have to do some activities on this. 

And besides of this we can announce this version which will come shortly in beta to the community. I think many are not viewing here on github.

**Comment by RickDB** [comment]
Will write up something for the forum and create new sections, old wiki I think we can retire (copy over parts ofc) and create something on a new platform so any points on this are appreciated 
It can be self hosted as have the server server or some service.

**Comment by b1rdhous3** [comment]
Why don‘t we Use github Wiki. Should be enough for Us plus we can update it within the repo if we are making big changes.

**Comment by RickDB** [comment]
We used in the past and it got cluttered pretty fast.

**Comment by b1rdhous3** [comment]
Really? There are some nice projects which use this. We don‘t need to explain all in detail. We should focus on the functions in the software. Other topics can be tutorials in forum

**Comment by RickDB** [comment]
Probably the way it was arranged many years ago, if we can keep it clean all for it and that way easy to add maintainers for it as well.

**Comment by b1rdhous3** [comment]
I think we should give it a go. 
But next step for release prep. would also be modify the setup script with the new paths to release and beta etc, right?

**Comment by tpmodding** [comment]
+1 for wiki in github, we should try it..otherwise we can copy all the stuff in another wiki

**Comment by Paulchen-Panther** [comment]
I am also still working on it. Please wait with merge

**Comment by brindosch** [comment]
Hey guys,
I suspect my doc work was "lost in space". It reflects the state of my rework branch (at least the dev corner). It documents 100% of available APIs for programming (at least what i remember)

It also reflects some things at the user side, installation or the LED coords system for example.
I vote for the .deb and .yml packages where possible, because these are no brainers also for desktop linux users (with menu icon!). However the .yml systems have the problem of different package naming, which makes it weird to write the dependecy list (Needs more investigation/testing)

https://docs.hyperion-project.org/en/intro
Be aware to choose the english flag at the top (at the root page you will be moved to german, if this reflects your browser lang)

This wiki was set to private to prevent confusion

**Comment by b1rdhous3** [comment]
Hey @brindosch,

I am very glad to here from you again!

Thanks for open up that wiki. I was indeed not aware of this. I don't know what you excactly mean with .yml packages. I think I have to research there. So you think we should move away from that installation script?

**Comment by brindosch** [comment]
Hello @b1rdhous3 ,
sorry, my fault. I mean .rpm not .yml! But the .deb works good so far (at least by the time i "programmed" it at around 3.2018)

The installation script is fine and can be used for 100% automation (.deb downloading + execution in one step) and for other platforms where you can't use these installation packages.

**Comment by RickDB** [comment]
Hi @brindosch,

Good to see you again!
The other doc / wiki site was archived a while back but can restore that if needed.

**Comment by brindosch** [comment]
Yeah, here again :dancer: 
What do you mean with "other"? We had way too much of them ;)

My personal all time favorite of a wiki would be a github repository with markdown files (kind of, if needed, but with a proper preview), together with a wiki creator software that supports mutiple languages. Build and publish via ci. The design and usability shouldn't be from 1990.
The main problem is often you want to document and program at the same time (Example: API or larger changes to a current system). With a github repo you can stage your changes in a pr and merge/publish on command.

I noticed it is very handy to TEST and document examples/apis directly. Also usability flaws you haven't noticed while programming or simply a corner is missing which just costs you time afterwards to complete/correct

**Comment by b1rdhous3** [comment]
I think the way you described @brindosch would be indeed the best to maintain a wiki at the current development state.

**Comment by brindosch** [comment]
I should notice that DokuWiki uses already markdown files
Was also a reason why i wanted it, no database for endless weird migration

Oh and regarding release and Raspberry. It was already noted.
I also played around with image building for Pi. The Pi Foundation hackt a script together for that task and can be used.
Here in my repo https://github.com/brindosch/pi-gen
It can run on travis (11 minutes runtime. See https://travis-ci.org/brindosch/pi-gen/builds/266269685)
All it needs is a .deb or install script to pull and install Hyperion. Afterwards can be uploaded automatically as @Paulchen-Panther  noted :)

**Comment by Paulchen-Panther** [comment]
@RickDB 
I'm done with this PR.
If you want to create a release, the order is as follows:
In the file version.json you specify the version (eg "1.0.0") as well as the channel (stable or beta). The description as well as the changelog are intended for the WebUI. Then create a release in GitHub. The finished packages are automatically attached.

**Comment by RickDB** [comment]
Great work 👍 

Work will have me busy this weekend but will pick up on the forum changes + release prepping later next week.

**Pull request merged**
