### PR TITLE
DirectX9 Grabber

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

The title says it all.

TODO:
- [ ] Resize destination image with DirectX [link1](https://github.com/sabaatworld/HyperionScreenCap/blob/master/HyperionScreenCap/Capture/Dx9ScreenCapture.cs#L77) [link2](https://github.com/SlimDX/slimdx/blob/426f59d9e30eaa75cd178f8abdf46ec915530ff7/source/direct3d9/Surface.cpp#L633)
- [ ] Support for multiple monitors and offer them in the WebUI [link1](https://github.com/sabaatworld/HyperionScreenCap/blob/master/HyperionScreenCap/Capture/Dx9ScreenCapture.cs#L102) [link2](https://github.com/SlimDX/slimdx/blob/426f59d9e30eaa75cd178f8abdf46ec915530ff7/source/windows/DisplayMonitor.cpp#L119)
- [x] Standalone-Grabber
- [ ] Manually load the d3d9.dll library [link1](https://docs.microsoft.com/en-us/windows/win32/api/d3d9/nf-d3d9-direct3dcreate9ex#examples)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by brindosch** [comment]
Sounds great! I want to help pushing it :)

**Comment by Paulchen-Panther** [comment]
@brindosch 
Thank you for your help. Great :relaxed:

**Comment by Lord-Grey** [comment]
Hi DirectX grabber works fine.
Only one question. I have two screens, but only the primary screen is grabbed and not the extended screen across both monitors.
I assume that is the expected behavior, correct?

**Comment by Paulchen-Panther** [comment]
> I assume that is the expected behavior, correct?

Yes. Precisely.



> One finding:
> 
> If I execute
> `.\hyperion-dx.exe --screenshot`
> 
> an empty sceenshot file is created
> 
> image
> 
> edit: Same behavior for hyperion-qt.exe

I'll look at that. Thanks for the find. 👍

**Comment by brindosch** [comment]
You unveiled, i copied from qt :)

**Comment by Paulchen-Panther** [comment]
> You unveiled, i copied from qt :)

Kein Problem. Was doch eine gute Basis. 😃

**Comment by Lord-Grey** [comment]
Sorry, ich hatte folgendes File und Zeile gemeint.
Hier sollte auch das Sceenshotproblem auftreten.

https://github.com/hyperion-project/hyperion.ng/blob/8a9b44fd3cf257fb279aa5ae803bfc328743d5a3/src/hyperion-x11/X11Wrapper.cpp#L18

**Comment by Paulchen-Panther** [comment]
> Sorry, ich hatte folgendes File und Zeile gemeint.
> Hier sollte auch das Sceenshotproblem auftreten.
> 
> https://github.com/hyperion-project/hyperion.ng/blob/8a9b44fd3cf257fb279aa5ae803bfc328743d5a3/src/hyperion-x11/X11Wrapper.cpp#L18

Das ändert daran nichts. In der Funktion _grabber.grabFrame() wird der ImageResampler aufgerufen.

**Comment by Lord-Grey** [comment]
> Das ändert daran nichts. In der Funktion _grabber.grabFrame() wird der ImageResampler aufgerufen.

Meine Frage war, wenn Du für den Qt und Qx Screenshot-Fix , 
 _grabber.grabFrame(_screenshot, true); 
durch capture() ersetzt, also

const Image<ColorRgb> & QtWrapper::getScreenshot()
{
	capture();
	return _screenshot;
}

warum dann nicht auch in 

hyperion.ng/src/hyperion-x11/X11Wrapper.cpp

**Pull request closed without merging**
