### PR TITLE
Suppress default password warning

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

Allow the user to suppress default password warning,
in case they are happy to run hyperion without password access.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Before**

image

**After**
image

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
I like it. ❤️

**Comment by Paulchen-Panther** [comment]
Ready to merge?

**Comment by brindosch** [comment]
Anstrengend, jetzt werfe ich schon meine selbst erstellten Konventionen ins Meer.
Gerne die CHANGELOG.md in der `Unreleased` Sektion beglücken.

**Comment by Paulchen-Panther** [comment]
Ich verstehe kein Wort von dem was du uns sagen wolltest aber EGAL. 😄

**Comment by brindosch** [comment]
Wir haben eine CHANGELOG.md im repo, in der alles "wichtige" festgehalten werden soll. Dann sitzt man beim nächsten Release nicht mehr dran alle commits durchzusehen nach wichtigen Notizen.

**Comment by tpmodding** [comment]
https://github.com/hyperion-project/hyperion.ng/pull/833 einfach hier ergänzen :-)

**Comment by brindosch** [comment]
Ah, schon in den Brunnen gefallen :)

**Pull request merged**
