### PR TITLE
ledConfig in config, report creation and upload

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
- New: uploading log+config+basic info to https://glot.io (report) Demo report: https://glot.io/snippets/en4xcjfeld
- New: ledConfig is now stored in config instead storage. Matrix layout is not included!
- Fixed: wiz cc kodi address wasn't read from storage
- Changed: update remote and wiz cc cause of https://github.com/hyperion-project/hyperion.ng/pull/394
- Changed: clock effect is now usable. The default .json is no longer provided as you need to configure it first. Pacman and his guys have now a adjustable margin
- Changed: I added all possible keys for framegrabber to default config. We need a proper grabber information to hide options. e.g. if x11 is available - all non possible options should be hidden @redPanther  

Some words to the report upload.
glot.io is an open source project which is used to run code snippets, but you could also upload plaintext. This is not ideal, but due to the point you could upload more than one file that are grouped under one link and it allows CORS it is near perfect.
--> You could run glot.io on your own server and you are free how the presentation of the content should be. So for example for the config you could use a json syntax check/validation (inline!). You could create own code highlighter for the log (red for error).
You could also edit files and save them online (if you need to adjust something for someone).
---> All in all this will be on my ToDo list, if @RickDB  found some time for pending todos :)

@redPanther 
I am sorry, but i added again some leds :) Looks much better than just 3 left/right.

**2.** If this changes affect the .conf file. Please provide the changed section
New object
```
	"ledConfig" :
	{
		"top"	 	: 8,
		"bottom"	        : 8,
		"left"		: 5,
		"right"		: 5,
		"glength"    	: 0,
		"gpos"		: 0,
		"position"	: 0,
		"reverse"	       : false,
		"hdepth"	       : 8,
		"vdepth"     	: 5,
		"overlap"  	: 0,
		"edgegap"      : 0
	},
```
And update your framegrabber section

**3.** Reference an issue (optional)
https://github.com/hyperion-project/hyperion.ng/issues/370
https://github.com/hyperion-project/hyperion.ng/issues/395

### CODE REVIEW

**Comment by penfold42** [comment]
Excellent work!

**Comment by redPanther** [comment]
We can handle grabber config like the ledDevices. We can have schema files for every grabber.

**Comment by brindosch** [comment]
I also thought about it. But than you need to remove the "auto" option. Hyperion needs to edit this in default config before it starts.

You need a detection for Pi BCM, x86 platform, Weteks and for other amlogic?
In any way, you need to do some actions. Which is why i thought just do provide a list of compiled capture devices and write just a some ui code wich hides option in a sort of priority chain (dispamanx is over framgrabber, x11 is over framegrabber. etc.

--> No need for additional detection or workarounds on default config creation.
But it's up to you. I will complete the however you wanna do it. :)

**Comment by redPanther** [comment]
How about givin special options a prefix like x11_ dispmanx_ ... then its clear where the options belong and we have not so much changes.

**Comment by brindosch** [comment]
Possible but doesn't look good. As they are also mixed. (some of them needs more than one attribute)
I think a list of cimpiled grabbers in serverinfo is for the moment good enough? (And not too much work?)

**Comment by redPanther** [comment]
... you will get the list :-)

**Comment by brindosch** [comment]
They "fixed" the CORS, upload is broken :)
@RickDB 
Time for own dbs :)

**Comment by brindosch** [comment]
OT
@RickDB 
Forum emergency :)

**Comment by RickDB** [comment]
Fixed :)

**Pull request merged**
