### PR TITLE
add command for getting schema via json api

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- update coding style
- add command for getting schema via json api
- json api: merge config commands into one single "config" command with subcommands
```
{"command":"config","subcommand":"getconfig"}
{"command":"config","subcommand":"getschema"}
{"command":"config","subcommand":"setconfig","config":{"logger":{"level":"warn"}},"create":false}
```

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by b1rdhous3** [comment]
Can't wait to test! :)

**Comment by redPanther** [comment]
BTW you can get the configured json port via jquery ajax call from url:
"http://"+document.location.hostname+":8099/cgi/cfg_jsonserver"

result:
:19444

**Comment by Paulchen-Panther** [comment]
Great. Super. +1

**Comment by b1rdhous3** [comment]
@redPanther I think we need a way to send the tanslation token and default language key for our translation with the schema.

**Comment by redPanther** [comment]
Default language is the browser language.
You can add 'title' in json schema and use it for translation token. 
We can save language as cookie. If no cookie, show language selector with browser lang preselected.

**Comment by brindosch** [comment]
This may be possible for language but i am not sure if this is the long run in general (other options/flags that you don't want in config .json)
So maybe another settings.json to read from for system settings or a database like you mentioned for better effects handling/configuration

**Comment by b1rdhous3** [comment]
Our translation lib needs to tags in a html element like <a> <span> etc:
data-lang-token and lang. 
But I think we also could set these two with JS tag manipulation after the JSON Forms were generated

**Comment by redPanther** [comment]
In config.json we can save webui related stuff in webconfig section.

**Pull request merged**
