### PR TITLE
use QSerialPortInfo to detect presence of a serial port (fix #836)

### LINKED ISSUE #836: ProviderRs232: checking port's existence by device file does not work on windows
- [x] I confirm that this is an issue rather than a question.

## Bug report
ProviderRs232::tryOpen checks, if a file with name of serial device is present before opening serial port. This is OK for linux, but does not work on windows (even if I use \\.\COMx as device name). hyperion-ng never initializes LED hardware connected via serial port (e.g. adalight).

#### Steps to reproduce
* hyperion.ng on windows
* adalight (or any other LED hardware) connected to serial port (e.g. COM10)
* configure adalight as LED hardware on serial port COM10

#### What is expected?
* hyperion.ng initializes adalight successfully

#### What is actually happening?
* adalight is not initialized, hyperiond logs `[hyperiond LEDDEVICE] <ERROR> Device disabled, device 'adalight' signals error: 'Error opening device!'`

#### System

Hyperion Server: 
- Build:       do-not-check-serial-port-file-on-windows (GitHub-0dd4bbf9/5eb45e85-1592422704)
- Build time:  Jun 20 2020 12:31:15
- Git Remote:  git@github.com:heikobihr/hyperion.ng.git
- Version:     2.0.0-alpha.6
- UI Lang:     auto (BrowserLang: de-DE)
- UI Access:   default
- Avail Capt:  qt

Hyperion Server OS: 
- Distribution: Windows 10 Version 1903
- Arch:         x86_64
- Kernel:       winnt (10.0.18362 (WS: 64))
- Browser:      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36

### PR DESCRIPTION
**Pull request by heikobihr**
**Summary**

* ProviderRs232: checking for existence of device file does not work on windows.
* instead: construct QSerialPortInfo from device name and check, if it is not null.

  When constructing QSerialPortInfo from device name, this constructor finds the
  relevant serial port among the available ones according to the port name name,
  and constructs the serial port info instance for that port.
  (https://doc.qt.io/qt-5/qserialportinfo.html#QSerialPortInfo-2)

Fixes: #836 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@heikobihr Thanks for the update.

I am currently in the process refactoring the Led-Devices's code which included the Rs232 one.
I have incorporated your input (plus some minor additions).

As it seems you have a serial device running with windows, would you mind testing my [development branch](https://github.com/Lord-Grey/hyperion.ng/tree/Refactor_LedDevices) from a Windows/Rs232 perspective?
That would be very much appreciated!

Many thanks in advance!

**Comment by heikobihr** [comment]
@Lord-Grey 
Yes, I am running an adalight serial Port device with hyperion.ng on windows. I'll run a test of your development branch tonight.

**Comment by Paulchen-Panther** [comment]
I would like it if the available serial devices were transferred to the JsonAPI. With this one could create a drop down field in the WebUI and select connected devices. Examples can be found in the V4L2 Grabber.

[QSerialPortInfo Enumerator Example](https://doc.qt.io/qt-5/qtserialport-enumerator-example.html)

**Comment by Lord-Grey** [comment]
@paulchen-Panther This is already available as part of my LedDevice Refactor Branch.
When I am back at my PC, I can quickly tell, how you could test it.

**Comment by heikobihr** [comment]
@Lord-Grey 
I tested your LedDevice Refactor Branch, successfully. Hyperion.ng connects to my adalight and shows rainbow swirl startup effect.

**Comment by brindosch** [comment]
Thank you for contribution and testing.

**Pull request merged**
