### PR TITLE
adjustable image2led mode for grabbers

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
you can switch between multicolor (all leds could have different colors) und unicolor mode.
unicolor means all leds have sa same color. The color is calculated from the average of the whole(!) image.
This method is not the best, because it gets sometimes to dark, but it's a start. This methode is very cool when you watch pictures.
In general we have now a methode to implement other image to led mapping algorithms.

usage:
use it via hyperion-remote or json interface with you own application:
unicolor mode
```
bin/hyperion-remote -M unicolor_mean --print
hyperion-remote:
        Version   : 2.0.0 (unicolor (redpanther-90f27a1/cbec2f4-1482083992))
        build time: Dec 18 2016 19:02:32
Connected to: "localhost:19444" 
Command: {"command": "processing","mappingType": "unicolor_mean"}
Reply: {"command": "processing","success": true,"tan": 0}
```

multicolor mode:
```
bin/hyperion-remote -M multicolor_mean --print
hyperion-remote:
        Version   : 2.0.0 (unicolor (redpanther-90f27a1/cbec2f4-1482083992))
        build time: Dec 18 2016 19:02:32
Connected to: "localhost:19444" 
Command: {"command": "processing","mappingType": "multicolor_mean"}
Reply: {"command": "processing","success": true,"tan": 0}
```

**2.** If this changes affect the .conf file. Please provide the changed section
you can set default mode in hyperion.config:
```
	"color" :
	{
		"imageToLedMappingType" : "multicolor_mean",
```
or "unicolor_mean" ...

**3.** Reference an issue (optional)
 #10

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by b1rdhous3** [comment]
So we should add a simple button in the webui remote for this?! =)

**Comment by redPanther** [comment]
somewhere in the remote control would be fine. the settings for the config is already there

**Comment by brindosch** [comment]
I am to slow or you to fast! I will do... :)

**Comment by brindosch** [comment]
Regarding feedack, the same "ui issue" i have with the auto selection button. Could we output 'somewhere' the state to set a proper button styling

Do you want to add the auto mode (source selection) like the "off" mode to the list to get proper state feeback?

Thank you :)

**Comment by redPanther** [comment]
I realized already thst i forgott to expose the state to json api. A function alredy exists, but have to be added to json serverinfo

**Comment by teeedubb** [comment]
Hi redPanther, thanks for this addition, this is one feature which I missed from my old setup. 
One question, is it possible to make this feature work with the kodi addon (which uses the UDPLISTNER input)? Toggling unicolor_mean when it is active has no effect. Work wonderfully with the v4l grabber.

Thanks again for this PR.

**Pull request merged**
