### PR TITLE
Fix OSX Bundling

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

Fix OSX Bundling

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by tpmodding** [comment]
läuft wieder :-)

**Comment by fightingforyou46** [comment]
not working, because if I remove python 3.10 from mac, then Hyperion.app error says missing folder "lib" at Hyperion.app/contents/frameworks/python.framework/version/3.10/

**Comment by Lord-Grey** [comment]
> @Lord-Grey not working, because if I remove python 3.10 out of mac, then Hyperion.app error says missing folder "lib" at Hyperion.app/contents/frameworks/python.framework/version/3.10/

Did you try both version?
And you should not remove the python folder. Hyperion delivered the required files with the package.

What is the error message this time? Previously it was related to the Qt libraries, not python.

**Comment by fightingforyou46** [comment]
> > @Lord-Grey not working, because if I remove python 3.10 out of mac, then Hyperion.app error says missing folder "lib" at Hyperion.app/contents/frameworks/python.framework/version/3.10/
> 
> Did you try both versions? And you should not remove the python folder. Hyperion delivers the required files with the package (and rely on them).
> 
> What is the error message this time? Previously it was related to the Qt libraries, not Python.

@Lord-Grey Here you are:
```
Last login: Thu May 19 00:03:53 on ttys000
/Volumes/Hyperion-2.0.13-beta.1.PR1465-macOS-x86_64/Hyperion.app/Contents/MacOS/Hyperion ; exit;
macos@MacOS ~ % /Volumes/Hyperion-2.0.13-beta.1.PR1465-macOS-x86_64/Hyperion.app/Contents/MacOS/Hyperion ; exit;
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'Hyperion'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Volumes/Hyperion-2.0.13-beta.1.PR1465-macOS-x86_64/Hyperion.app/Contents/MacOS/Hyperion'
  sys.base_prefix = '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9'
  sys.base_exec_prefix = '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9'
  sys.platlibdir = 'lib'
  sys.executable = '/Volumes/Hyperion-2.0.13-beta.1.PR1465-macOS-x86_64/Hyperion.app/Contents/MacOS/Hyperion'
  sys.prefix = '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9'
  sys.exec_prefix = '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9'
  sys.path = [
    '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python39.zip',
    '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9',
    '/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010e5aa600 (most recent call first):
<no Python frame>

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

that means if I run Hyperion.app in a any MacBook, I have to install home-brew then install python 3.9, Hyperion.app just can run.

**Comment by Lord-Grey** [comment]
@fightingforyou46 Thank you.

It seems that the executable is looking for the default python path 

`/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9`

and not at the python packaged with Hyperion 

`... Hyperion.app\Contents\Frameworks\Python.framework\Versions\3.9\`

I would need to find out how to change that.
Any help is appreciated

**Comment by fightingforyou46** [comment]
@Lord-Grey not really, because as soon as I copy the folder `"lib"` from `"/usr/local/Cellar/python@3.9/3.9.12_1/Frameworks/Python.framework/Versions/3.9/lib"` into `"Hyperion.app /contents/frameworks/python.framework/version/3.9/` .Hyperion.app was running fine even when I removed python by command line `"brew uninstall python@3.9"`

**Comment by Lord-Grey** [comment]
@fightingforyou46 I checked the 2.0.12 dmg file vs. the 2.0.13-beta1.
The 2.0.12 seems to include the libs whereas in 2.013-beta1 the lib directory is missing (which I assume causes the error....)
"Only" question is now why...

**Comment by fightingforyou46** [comment]
@Lord-Grey since you added qmdnsengine it has changed significantly and created some issues for deployment

**Comment by Lord-Grey** [comment]
@fightingforyou46 Would you mind checking, if the following works:

https://github.com/hyperion-project/hyperion.ng/actions/runs/2360254523

Thank you!

**Comment by fightingforyou46** [comment]
> @fightingforyou46 Would you mind checking, if the following works:
> 
> https://github.com/hyperion-project/hyperion.ng/actions/runs/2360254523
> 
> Thank you!

it works great!

**Comment by Lord-Grey** [comment]
> it works great!

Good to hear. 
I disabled multiple things to be on the save side. I will enable some again , as I think they are ok.
Then I would need your help in another test again, please. 
Hoping that is ok.

**Comment by fightingforyou46** [comment]
you're welcome!

**Comment by Lord-Grey** [comment]
@fightingforyou46 Seems I now understood what was going wrong...

Would you mind checking, if the following package works:

https://github.com/hyperion-project/hyperion.ng/actions/runs/2363868474

Thank you and fingers crossed!

**Comment by fightingforyou46** [comment]
> @fightingforyou46 Seems I now understood what was going wrong...
> 
> Would you mind checking, if the following package works:
> 
> https://github.com/hyperion-project/hyperion.ng/actions/runs/2363868474
> 
> Thank you and fingers crossed!

it runs very great!

**Pull request merged**
