### PR TITLE
drop (some) AMLOGIC specfic rules, fix buid against flat-+/protobuf system libs

### PR DESCRIPTION
**Pull request by mirko**
**Summary**

Build against shared system protobuffer and flatbuffer libs is completely broken, at least if AMLOGIC is turned off. Until recently that was also the case for mbedtls, however got fixed (https://github.com/hyperion-project/hyperion.ng/issues/883).

I'm confused about the so many AMLOGIC specific build rules anyway. Maybe don't necessarily see this PR as ready to be merged, but more to raise a discussion about those AMLOGIC specific build rules. They really seem unnecessary to me.
Actually, to me it looks like somebody needed to have the system lib support running on AMLOGIC but didn't care about everything else. So, for the rules I had to touch I dropped the AMLOGIC specific rules.

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [X] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No
- [X] Maybe

I'm really confused of the many AMLOGIC specific build rules. I'm dropping the ones I had to touch anyway. Non-AMLOGIC builds with system libs were broken anyway, but this change potentially breaks AMLOGIC specific stuff.

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

Happy to do so, once the AMLOGIC question-marks are solved.

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
@Portisch Your opinion?

**Comment by Paulchen-Panther** [comment]
Works wonderfully in the CI. 😅

**Comment by mirko** [comment]
> Works wonderfully in the CI. sweat_smile

Unable to determine whether you you're totally ironic or not.
Taking the risk of not getting it right: the failing tests are a result of mentioned 3rd party libs - flatbuffers and protobuf - not being installed in the CI container (so compiling/linking against them fails). Or am I missing sth. else here?

**Comment by Paulchen-Panther** [comment]
Submodules beachtet?

**Comment by mirko** [comment]
> Submodules beachtet?
> bzw. Compile output from terminal.

This PR is about building against protobuf and flatbuffers as system libs.
Not sure what its submodules should have to do with it, as the idea of those flags is /not/ to use them.

build command line:
`mkdir build && cd build && cmake -DENABLE_AMLOGIC=OFF -DPLATFORM=linux -DENABLE_X11=OFF -DENABLE_FB=OFF -DENABLE_TINKERFORGE=OFF -DCMAKE_BUILD_TYPE=Release -DENABLE_SPIDEV=ON -DENABLE_WS281XPWM=ON -DENABLE_QT=OFF -DUSE_SYSTEM_MBEDTLS_LIBS=ON -DUSE_SYSTEM_PROTO_LIBS=ON -DUSE_SYSTEM_FLATBUFFERS_LIBS=ON .. && make`

**Comment by Paulchen-Panther** [comment]
> This PR is about building against protobuf and flatbuffers as system libs.
> Not sure what its submodules should have to do with it, as the idea of those flags is /not/ to use them.

I understand you. But you should keep in mind that our Docker CI containers run without System Proto / Flat dependencies. It would be nice if you limited your changes to these cmake switches (USE_SYSTEM_PROTO_LIBS & USE_SYSTEM_FLATBUFFERS_LIBS). Many thanks.

**Comment by Paulchen-Panther** [comment]
To possibly clarify why so many AMlogic switches were used. The changes were introduced by @Portisch  in order to also compile Hyperion on CoreELEC.

**Comment by Paulchen-Panther** [comment]
Thanks for contribution.

**Pull request merged**
