### PR TITLE
Hyperion Buster releases

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

This PR will cause future releases to be made with Debian Buster (to avoid QT complications).
A few more tests will be necessary to identify and fix teething problems with the dependencies on different systems.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [x] Yes
- [ ] No

**If yes, please describe the impact and migration path for existing setups:**

Upgrade the system if possible.

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [x] No, CHANGELOG.md is not yet updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Hukuma1** [comment]
Got this artifact working with a `debian:buster-slim` install in a Docker environment on a Raspberry Pi 4. Anything to test specifically for you?

**Comment by Paulchen-Panther** [comment]
> Got this artifact working with a `debian:buster-slim` install in a Docker environment on a Raspberry Pi 4

I guess so. Hyperion brings its own dependencies (with the exception of libcec). So if libcec is present it shouldn't be a problem (not tested)
Of course, hyperion only works to a limited extent in the Docker container.

**Comment by Hukuma1** [comment]
Could not get release a7 to work, but this one did.

```
	libpython3.5 \
	libjpeg62-turbo \
	libavahi-compat-libdnssd1 \
	libdbus-1-3 \
	libqt5sql5 \
	libqt5serialport5 \
	libqt5network5 \
	libqt5widgets5 \
	libqt5gui5 \
	libqt5core5a \
	zlib1g-dev \
	curl \
	libusb-1.0-0 \
	libcec4
```

Has to get these installed on top of buster-slim variant. Or does this mean I only needed to get `libcec` installed with this artifact and the rest are included by default?

**Comment by Paulchen-Panther** [comment]
> Or does this mean I only needed to get `libcec` installed with this artifact and the rest are included by default?

Yes

**Pull request closed without merging**
