### PR TITLE
Logging for dispmanx, framebuffer, x11, v4l2, osx

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
Logging for dispmanx, framebuffer, hyperion-x11, v4l2, osx
**2.** If this changes affect the .conf file. Please provide the changed section
no
**3.** Reference a issue (optional)
https://github.com/hyperion-project/hyperion.ng/issues/25
Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
this is not optimal:

```
Info(_log, "Cropping from image (width x height) %dx%d", _width, _height);
Info(_log, " left: %d", cropLeft);
Info(_log, " right: %d", cropRight);
Info(_log, " top: %d", cropTop);
Info(_log, " bottom: %d", cropBottom);
```
... because it splits coherent inf accross logger statements. 
this contains same info and is in one statement:
```
Info(_log, "Cropping image: width=%d height=%d; crop: left=%d right=%d top=%d bottom=%d ", _width, _height, cropLeft, cropRight, cropTop, cropBottom);
```

**Comment by brindosch** [comment]
Ah, yes i know. i tried it first with newline, but this looks ugly. Is there no better solution available?

**Comment by redPanther** [comment]
logging is no ascii art. If you want to put a message it has to fit in a line.

This is the difference to freely put something on terminal. If we want something nioce for the user -> this is no logging -> do not use logger.
But hyperion is a daemon and it has no ui for the user, so there should be no reason for nice painted terminal art.

**Comment by brindosch** [comment]
:P

**Comment by redPanther** [comment]
... I had countless discussions over that @ work ... drawing big tables in logfiles and then complaining if another thread or the log rotation scrambles the ascii art ... *grrr* and poor people that should made automated processes for log evaluation.

**Comment by brindosch** [comment]
I made a mistake, v4l2 should output a float value. instead i get this with %f
```
[HYPERIOND V4L2GRABBER] <INFO> Signal threshold set to: 1717788323676192129486435861422674573983...
```
Duo the point it uses in master %d which can't or should not work, i missed a convert for this value, could someone point me to the right one?
https://github.com/hyperion-project/hyperion.ng/pull/103/files#diff-aec2cfe446c748ff341302e49e490d6bR80

**Comment by redPanther** [comment]
use `%4.2f` you can play with the numbers to get a result that satisfy you
http://www.cplusplus.com/reference/cstdio/printf/
(precision)

**Pull request merged**
