### PR TITLE
update qt version on macOS

### PR DESCRIPTION
**Pull request by Starbix**
**1.** Tell us something about your changes.

Update Qt version in brew.

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Hm, i don't like it since it has been added a while back.
Isn't there something possible like 
```
export QVER=$(ls /usr/local/Cellar/qt5 | grep '^5')
cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/$QVER  -DCMAKE_BUILD_TYPE=Release ..
```
Does `ls` show more than one entry for the given command? If it needs more vodoo

**Comment by Starbix** [comment]
yes, something like that would be much better

**Comment by redPanther** [comment]
how about
```
export QVER=$(find  /usr/local/Cellar/qt5 -type d -name "5.*" | sort -n  | head -n1)
cmake -DCMAKE_PREFIX_PATH=$QVER  -DCMAKE_BUILD_TYPE=Release ..
```

**Comment by redPanther** [comment]
I integrated in my pr

**Pull request closed without merging**
