### PR TITLE
Amlogic box uses aml and fb buffer

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
**Amlogic box uses aml and fb buffer**
on amlogic (wetek) systems you need 2 grabbers. aml and fb. Now both are started, with same settings. This is the same as before adding the amlgrabber section with same settings of framegabber section. The prio of aml is decreased by 1, because aml and fb arn't allowed to e on same channel.

In framegrabber section set type to "auto" or "amlogic". If you want FB only use "framebuffer" as type.

**hyperiond**
refactoring of hyperiond.cpp grabber config code.

**json client**
now all input sources (grabber, network, effects) are shown in hyperion-remote --list. Entries marked as active=true/false to show their state.
example:
```
   "priorities" : [
      {
         "active" : "true",
         "duration_ms" : 178,
         "owner" : "X11 Grabber",
         "priority" : 900
      },
      {
         "active" : "true",
         "owner" : "EFFECT: /usr/share/hyperion/effects/mood-blobs.py",
         "priority" : 2147483646
      },
      {
         "active" : "false",
         "owner" : "Boblight",
         "priority" : 710
      },
      {
         "active" : "false",
         "owner" : "V4L2",
         "priority" : 890
      }
   ],

```
(small todo ... sort output by priority)

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by stefansaraev** [comment]
not near my box now, will test this evening.

**Comment by stefansaraev** [comment]
when setting framegrabber to auto or amlogic, indeed framebuffer grabber is also started, log says: http://sprunge.us/JhhC

but sadly, amlogic grabber still does not work. framebuffer works.

both grabbers run with same prio now as they use common config, previously (hyperion, split grabber config) I had always set different prios (aml: 800, framegrabber: 900). 

as I quick hack, I forced those prios in code http://sprunge.us/ibcX and this worked for me.

**Comment by redPanther** [comment]
I know how to solve.  Will fix it when I'm home. Yeah and I'm happy I can test such things on my own in future :-)

**Comment by redPanther** [comment]
.. ready to test

**Comment by stefansaraev** [comment]
needs a rebase but yep 855c1c965a5f39c02c7d6fbbc0a86fbe129f7bde works for me. thanks

there are other unrelated issues (one is constant led flickering, not easy to reproduce, after it happens, I have to restart hyperion AND kodi, I think this happened with old hyperion too). this should be good enough for now after rebasing.

**Pull request merged**
