### PR TITLE
Update Webui

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
Update font-awesome from 4.2 to 4.6.3
Add Roboto Font
Add Dashboard example
Add Config example
Add support page
little adjustments

Note: Code mess on kodi page - and nothing final there. Just to get an idea of my personal direction.

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
+1

**Comment by brindosch** [comment]
@redPanther 
There is a issue loading the Roboto font (parsing)
For a uknown reason this works flawless with my local xampp (No - Roboto is not installed)

Do you have an idea/same problem?

**Comment by redPanther** [comment]
@brindosch an \r\n is appended. This dosn't harm on textfiles, but is fatal on binaries. I investigate ... but my schedule this week is tight, but this will be the next thing I hunt (have also other things for webserver todo ... e.g. the bug that index.html in subfolder is not called automaticly)

**Comment by redPanther** [comment]
I think this is the reason
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/webconfig/QtHttpClientWrapper.cpp#L178

**Comment by brindosch** [comment]
Fast!
No hurry :)
Just note it on the buglist :)

**Comment by redPanther** [comment]
can't resist:
wehen commenting out this https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/webconfig/QtHttpClientWrapper.cpp#L190 it works, but i don't know the consequences ...

**Pull request merged**
