### PR TITLE
Updating rpi_ws281x submodule to latest master

### PR DESCRIPTION
**Pull request by pkoutsias**
**Summary**

Update rpi_ws281x to add support for Pi 4 Model B - 2GB v1.4

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [x] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [x] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
Many Thanks. 👍🏻

**Comment by weitheng** [comment]
Have this issue been fixed? Still getting the error `[hyperiond LEDDEVICE] (ERROR) Device disabled, device 'ws281x' signals error: 'Failed to open. Error message: Hardware revision is not supported` on my Raspberry Pi 4 2GB Rev 1.4

**Comment by Lord-Grey** [comment]
@weitheng what have you installed? Or did you self build from the master Branch?

**Comment by weitheng** [comment]
> @weitheng what have you installed? Or did you self build from the master Branch?

I installed the latest release, but seems like that was released before this change was implemented. Would you advise me to build from master branch?

**Comment by Paulchen-Panther** [comment]
@weitheng 
You have to decide for yourself. Either build it yourself or wait for the next release. (No ETA)

**Comment by weitheng** [comment]
Any resources how I can build it myself?

**Comment by Lord-Grey** [comment]
https://github.com/hyperion-project/hyperion.ng/blob/master/CompileHowto.md

**Pull request merged**
