### PR TITLE
extend schema for leddevices

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
extend schema for led devices a bit. still lot's of work here ...

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
I vote for remove this format:checkbox option. I "hardcoded" it at my branch: https://github.com/brindosch/hyperion.ngBeta/commit/2ac86d040b00d0a609e5971413c9672c82d7b8ae

**Comment by redPanther** [comment]
oh great! I don't understand why jsoneditor has this bad default behaviour for booleans ...

**Comment by redPanther** [comment]
BTW if you modify jdoneditor. Would be great if you can alter behaviour of headlines. If headline has empty title, the headline (h3) is not shown. currently we add a title: " " to supress headline, but it add more space then needed

**Comment by brindosch** [comment]
This is the general fallback, if no title attribute is available, it falls back to object description. In the meantime i found the fallback, now it is empty, but the h3 is still rendered. need to catch the non existing title attribute to prevent this.

**Comment by redPanther** [comment]
instead of throwing out the h3, set css("display","none") for hiding them. Then dom is not altered, but we get rid of unneccesary space

**Pull request closed without merging**
