### PR TITLE
fix #158 initial state of kodi checker

### LINKED ISSUE #158: Kodi checker initial state bug
If you have a video playing and then start Hyperion it doesn't "grab video" I just get the background effect.

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
fix #158 

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)
#158
Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Thanks,
sorry - i killed the trello sync i need to wait for support as i can't do anything.

**Comment by brindosch** [comment]
Follwing bug and this was the last change regarding kodicheck
This is after startup of the system. If i start stop the video it works again. For a reason it ignores this message now the first time. ( {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]})
```
Aug 12 14:00:28 osmc hyperiond[305]: Connection error (Connection refused)
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:399:reconnect()> try reconnect
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND KODI] <INFO> Connected
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"error":{"code":-32601,"message":"Method not found."},"id":666,"jsonrpc":"2
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND KODI] <INFO> switching to OFF mode
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND Core] <INFO> Unregister input source named 'V4L2' from priority register
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND Core] <INFO> Unregister input source named 'Dispmanx' from priority register
Aug 12 14:00:38 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"error":{"code":-32601,"message":"Method not found."},"id":668,"jsonrpc":"2
Aug 12 14:01:50 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"id":78
Aug 12 14:01:54 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"id":78,
Aug 12 14:01:54 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
Aug 12 14:01:54 osmc hyperiond[305]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id":671,"jsonrpc":"2.0","result":{"speed":1}}
```

**Comment by redPanther** [comment]
I can not reproduce.

```
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:399:reconnect()> try reconnect
[HYPERIOND KODI] <ERROR> Connection error (Connection refused)
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:399:reconnect()> try reconnect
[HYPERIOND KODI] <INFO> Connected
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id": 666,"jsonrpc": "2.0","result": []}
[HYPERIOND KODI] <INFO> switching to OFF mode
[HYPERIOND V4L2] <INFO> Stopped
[HYPERIOND Core] <INFO> Unregister input source named 'V4L2' from priority register
[HYPERIOND Core] <INFO> Unregister input source named 'X11' from priority register
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id": 668,"jsonrpc": "2.0","result": {"System.ScreenSaverActive": false}}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id": 666,"jsonrpc": "2.0","result": []}
[HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id": 670,"jsonrpc": "2.0","result": {"version": {"major": 16,"minor": 1,"revision": "c327c53","tag": "stable"}}}

```
can you try to start hyperion later after kodi is started, to avoid connection error? which kodi you have? I have 16.1

**Comment by redPanther** [comment]
tested with kodi 15 this also works for me. hyperion started first, then later kodi ...

**Comment by brindosch** [comment]
If you start a movie now, does it recognize? (log)

**Comment by redPanther** [comment]
I can reproduce, it looks like the menu state has the same problem like the video state had.
If you playing a video or you in pause mode, this would be recognized.
I'll investigate ...

**Comment by brindosch** [comment]
Here you see the issue, this is just "the first time" i start a video. Afterwards everything works
```
Aug 12 15:24:20 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"error":{"code":-32601,"message":"Method not found."},"id":666,"jsonrpc":"2.0"}
Aug 12 15:24:20 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <INFO> switching to OFF mode
Aug 12 15:24:20 osmc-sascha hyperiond[311]: [HYPERIOND Core] <INFO> Unregister input source named 'V4L2' from priority register
Aug 12 15:24:20 osmc-sascha hyperiond[311]: [HYPERIOND Core] <INFO> Unregister input source named 'Dispmanx' from priority register
Aug 12 15:25:16 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"jsonrpc":"2.0","method":"Playlist.OnAdd","params":{"data":{"item":{"id":1,"type":"movie"},"playlistid":1,"position"
Aug 12 15:25:16 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"id":1,"type":"movie"},"player":{"playerid":1,"sp
Aug 12 15:25:16 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
Aug 12 15:25:16 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id":671,"jsonrpc":"2.0","result":{"speed":1}}
Aug 12 15:25:28 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"jsonrpc":"2.0","method":"Player.OnPause","params":{"data":{"item":{"id":1,"type":"movie"},"player":{"playerid":1,"s
Aug 12 15:25:31 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"jsonrpc":"2.0","method":"Player.OnPlay","params":{"data":{"item":{"id":1,"type":"movie"},"player":{"playerid":1,"sp
Aug 12 15:25:31 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <DEBUG> <KODIVideoChecker.cpp:141:receiveReply()> message: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
Aug 12 15:25:31 osmc-sascha hyperiond[311]: [HYPERIOND KODI] <INFO> switching to VIDEO mode
```
At the top the first time it won't jump to video mode, the second time it does. And after this hang everything is working as it should

**Comment by redPanther** [comment]
I have a solution. I'll prepare the PR.
problem was that initial playback state was initialized more than one time.
I'm very unhappy with current kodichecker code. This is horrible to read and to extend. There is also a similar bug when kodi is used with login screen. We need a good refactoring here, but this isn't done in a couple of minutes.

**Comment by brindosch** [comment]
I think we could get this just better with a native kodi client. I saw that kodi 17 alpha3 didn't react with full responses for me. I hope this is just for me...

But for now, not too much headach about this :)

**Pull request merged**
