### PR TITLE
disable v4l2 on osx

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
as the title says .. now v4l2 is disabled by default on osx build
additionally I remove unused zeroconf defines 

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
thanks i remove it from the command again.

**Comment by brindosch** [comment]
funny error.

**Comment by brindosch** [comment]
This error is true, also on my Pi.
But why and how.

**Comment by brindosch** [comment]
@redPanther 
might you able identify the current problem? Not sure why, but since this PR the build fails :)

**Comment by redPanther** [comment]
Can you paste compile errors here. Im not at home

**Comment by brindosch** [comment]
```
/home/travis/build/hyperion-project/hyperion.ng/src/hyperiond/hyperiond.cpp: In member function ‘void HyperionDaemon::loadConfig(const string&)’:
/home/travis/build/hyperion-project/hyperion.ng/src/hyperiond/hyperiond.cpp:112:29: error: ‘assert’ was not declared in this scope
  assert(schemaData.isValid());
                             ^
make[2]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/hyperiond.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by penfold42** [comment]
I was looking at this earlier - it builds ok on my pi, but not on my Ubuntu or centos x86 boxes

**Pull request merged**
