### PR TITLE
Leddevice refactoring the next part

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
just another monkey job. I want to save some code lines and remove dups.

led devices:
- move switchoff() into base class, where possible. (default switchoff means, set al leds to black)
- _ledCount is set automaticly before write is called.
- use _ledCount where possible
- some code style fixes
- cleanup includes

=> now every leddevice including upcomming devices have a working switchOff 

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference an issue (optional)
#194

### CODE REVIEW

**Comment by brindosch** [comment]
cool! Let the tests begin :)

**Comment by redPanther** [comment]
I just see I didn't cleaned the includes ... in some drivers are unused includes 
e.g. ws2801:
currrent:
```

// STL includes
#include <cstring>
#include <cstdio>
#include <iostream>

// Linux includes
#include <fcntl.h>
#include <sys/ioctl.h>

// hyperion local includes
#include "LedDeviceWs2801.h"
```

neccessary
```
// hyperion local includes
#include "LedDeviceWs2801.h"
```

... I'll have a look

**Comment by redPanther** [comment]
ok, now also includes are cleaned ... and lots of code line removed ;-)

**Comment by brindosch** [comment]
spicy!

**Comment by penfold42** [comment]
Great work - I love the sea of red!

I did laugh at  the 10 different implementations of switch off tho !

**Comment by tpmodding** [comment]
you are awesome red!!!

**Comment by redPanther** [comment]
Thx, I'm actualy on the next leddevice iteration. I will seperate init code from write function as @penfold42 suggested. The base is already finished, but now comes the monkey part for every device. 

Currently if you look into some devices it's somehow frightend that it contains only a few lines of code

**Comment by penfold42** [comment]
I guess most of them have very little to do - frame up the led data and get the provider to send it!

**Pull request merged**
