### PR TITLE
new effect plasma

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

_As mentioned in the title._
_Proof:_
Proof

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by brindosch** [comment]
Ich hab auch eine Lavalampe! Gefällt mir.

**Comment by Paulchen-Panther** [comment]
> Ich hab auch eine Lavalampe! Gefällt mir.

Dann kannst du gerne den deutschen WebUI Namen auf Lavalampe ändern.

**Comment by brindosch** [comment]
> Dann kannst du gerne den deutschen WebUI Namen auf Lavalampe ändern.

Das ist mir nur als Erstes eingefallen. Findest du das passend?

**Comment by Paulchen-Panther** [comment]
> Das ist mir nur als Erstes eingefallen. Findest du das passend?

Scheint das selbe zu beschrieben. Plasma <-> Lava
https://towardsdatascience.com/fun-with-html-canvas-lets-make-lava-lamp-plasma-e4b0d89fe778

**Comment by brindosch** [comment]
Dann lassen wir es so

**Comment by Lord-Grey** [comment]
Hi @Paulchen-Panther

When trying the effect. I got a warning that the "time.clock" function was deprecated already in Python 3.3:

`__main__:28: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
`

May be worth having it updated....

**Pull request merged**
