### PR TITLE
always output latest version of config file to webui

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
this fixes bug:
1. start hyperion
2. open webui
3. open e.g. led config
4. change config file on disk (e.g. device -> name)

prior: in webui always old value is displayed in webui, until restart
now:  in webui always current value is displayed

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
@redPanther 
OT: Please set the permission for the extracted config from qrc. This is ReadOnly default.
[main.cpp](https://github.com/hyperion-project/hyperion.ng/blob/master/src/hyperiond/main.cpp#L177)

**Comment by redPanther** [comment]
fixed ...

**Comment by Paulchen-Panther** [comment]
Du wolltest wohl nicht das interne QFile::setPermissions benutzen?

**Comment by redPanther** [comment]
hab in letzter zeit zuviel ohne qt programmieren müssen ... ja natürlich will ich setpermisions verwenden ;-) ich pass das dann gleich mal an ...

**Comment by Paulchen-Panther** [comment]
Vielen Dank :-)

**Pull request merged**
