### PR TITLE
fix: Backlight/BBDetector during effects

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
- fix: Backlight/BBDetector during effects

Fixes: #674

### CODE REVIEW

**Comment by brindosch** [comment]
As you may noticed, you can link one or more issues to close them automatically when a PR is merged.
`Fixes: #674`
@Lord-Grey

**Comment by T-IOOO** [comment]
Backlight threshold is now beeing deactivated during effects but still there are some issues remaining.

When i power off my tv the backlight stays on.

Then a weird issue for those of you running homebridge with homebridge-hyperion-light
if i switch ambilight off backlight stays on. If i quickliy play around with the switch then backlight switches off.

I have not tested this fully but it would be great to have a little bit of lightning during ”black screen moments”

**Comment by brindosch** [comment]
> When i power off my tv the backlight stays on.

How do you "power off"?

>  If i quickliy play around with the switch

What action is executed with this "switch"?

**Comment by T-IOOO** [comment]
By power OFF I mean the Receiver. I usually see the rainbow colors for like 10 seconds then the LEDs goes off totally. But when having backlight to a certain value it is going to stay on. The ”TV Ambilight” switch for homebridge is acting weird when power on/off. Backlight stays on if switch on and then off... but tap the switch two times fast will switch leds off. I think i might have a power backfeeding issue from my receiver since both the hdmi splitter and hdmi2av dont need any power supply connected to them 😬

**Comment by brindosch** [comment]
> The ”TV Ambilight” switch for homebridge is acting weird when power on/off. Backlight stays on if switch on and then off

Which action does this switch perform on Hyperion side.

**Comment by T-IOOO** [comment]
This switch makes leds either go on or off. I am not sure how it works. There is another separate button for ”tv backlight”,

The backlight threshold stays on when switch is in OFF mode. tapping quickly twice (on-off-on-off) wil turn leds off completely.

I dont think homebridge is the problem itself. Maybe it is my power backfeed. I dont know how hyperion recognize OFF?

**Pull request merged**
