### PR TITLE
Hyperiond refactoring + preparation for ip restriction settings

### PR DESCRIPTION
**Pull request by redPanther**
extensive refactoring of hyperiond - now it has a good structure. There is always room to make it better, but now we reached a state where we can extend in a future save way.

webserver: add ability to retrieve client/server ip. This is necessary for implementing ip restrictions

### CODE REVIEW

**Comment by brindosch** [comment]
always appreciated :)

**Comment by brindosch** [comment]
latest test build
may be a small regression  - LM 18 - x11 enabled
```
In file included from /home/Schreibtisch/hyperion.ng/src/hyperiond/hyperiond.h:35:0,
                 from /home/Schreibtisch/hyperion.ng/src/hyperiond/hyperiond.cpp:21:
/home/Schreibtisch/hyperion.ng/src/hyperiond/hyperiond.cpp: In member function ‘void HyperionDaemon::run()’:
/home/Schreibtisch/hyperion.ng/include/utils/Logger.h:21:71: error: request for member ‘Message’ in ‘log’, which is of non-class type ‘double(double) throw ()’
 #define ErrorIf(condition, logger, ...)   { if (condition) {(logger)->Message(Logger::ERROR   , __FILE__, _FUNCNAME_, __LINE__, __VA_ARGS__);} }
                                                                       ^
/home/Schreibtisch/hyperion.ng/src/hyperiond/hyperiond.cpp:75:3: note: in expansion of macro ‘ErrorIf’
   ErrorIf(_config.isMember("framegrabber"), log, "No grabber can be instantiated, because all grabbers have been left out from the build");
   ^
src/hyperiond/CMakeFiles/hyperiond.dir/build.make:62: die Regel für Ziel „src/hyperiond/CMakeFiles/hyperiond.dir/hyperiond.cpp.o“ scheiterte
make[2]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/hyperiond.cpp.o] Fehler 1
make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
CMakeFiles/Makefile2:1515: die Regel für Ziel „src/hyperiond/CMakeFiles/hyperiond.dir/all“ scheiterte
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Fehler 2
Makefile:149: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by brindosch** [comment]
Another (small) topic regarding cleanup

#ifdef ENABLE_TINKERFORGE

**Comment by redPanther** [comment]
Typo, Rename log to _log

**Pull request merged**
