### PR TITLE
implement set videomode via json api

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
as written in title ...

+ refactoring of cmake files
+ grabbers have a base class now 

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)
#454

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
I forgot to mention, your sendSucessReply triggers a new serverinfo which is not intended. I am not happy about the solution, the  specific parts of hyperion should trigger them in best case.

**Comment by brindosch** [comment]
Oh, wait. The serverinfo needs a entry in order to display the _current_ videoMode. Can you add it too? hyperion class can hold the information.

**Comment by redPanther** [comment]
will add it later. I refactored all the grabber stuff like I refactored the grabberwrapper stuff some time before. Now grabbers have a more ore less commen api. Will extend this work in future ... (cropping isn't implemented in all grabbers -> more or less needed for 3D modes)

**Comment by brindosch** [comment]
Yes, i have seen the utils/ImageResampler.cpp which should be used instead of own implementation (like dispmanx)

**Comment by redPanther** [comment]
can somebody compile it on raspi (dispmanx)?

**Comment by brindosch** [comment]
```
/home/pi/hyperion/src/hyperiond/main.cpp: In function ‘QCoreApplication* createApplication(int&, char**)’:
/home/pi/hyperion/src/hyperiond/main.cpp:118:1: error: a function-definition is not allowed here before ‘{’ token
 {
 ^
/home/pi/hyperion/src/hyperiond/main.cpp:337:1: error: expected ‘}’ at end of input
 }
 ^
/home/pi/hyperion/src/hyperiond/main.cpp:337:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
```
Not related to this PR but your desktop integration.

**Comment by redPanther** [comment]
fixed directly in upstream/master .... should work now

**Comment by redPanther** [comment]
> Yes, i have seen the utils/ImageResampler.cpp which should be used instead of own implementation (like dispmanx)

in dispmanx as well as in X11 scaling and croping is done by x11 or dispmanx in hardware - when available.
usage of imageresampler means slow software resampling.

**Comment by redPanther** [comment]
besides neccessary refactoring did anybody need 3d support?https://en.wikipedia.org/wiki/3D_television#The_Fall_of_3D_Television

**Comment by brindosch** [comment]
This 3d stuff just came to my attention recently from a user. So yes, there are some people.
The SBS/TAB implementation is not a big deal at all as you see.

**Comment by brindosch** [comment]
Next round
```
/home/pi/hyperion/libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp: In member function ‘void DispmanxFrameGrabber::setCropping(unsigned int, unsigned int, unsigned int, unsigned int)’:
/home/pi/hyperion/libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp:69:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (cropLeft + cropRight >= _width || cropTop + cropBottom >= _height)
                           ^
/home/pi/hyperion/libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp:69:61: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  if (cropLeft + cropRight >= _width || cropTop + cropBottom >= _height)
                                                             ^
```

**Comment by brindosch** [comment]
Note: The grabbing mode is some kind of bloat and is kodi specific. The usual way would be to use the "new" start/stop mechanic for capture devices. The current mode expose is therefore not intended.

You can keep it for the moment :)

**Comment by redPanther** [comment]
just as note:
not all grabbers have 3d and croping support. here a list:
```
    3D crop
aml -   -
dis x   x
fb  -   -
osx -   -
v4l x   x
x11 -   x
```
missing support will be added later

**Pull request merged**
