### PR TITLE
Update Flag Effect

### PR DESCRIPTION
**Pull request by Cosmicbase**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Cosmicbase** [comment]
Hello, the sorting by name is complete and the Russian flag has been deposited.

**Comment by Lord-Grey** [comment]
@Cosmicbase Is there any reason why you closed the PR (which means you do not want to have it made available to everybody)?

The process is normally
1. You initiate a PR
2. The central team reviews and provide feedback
3. You provided additional commits to this PR (if required)
4. If everything is fine, the central team will merge it into the master code repository
5. The PR gets closed.

**Comment by Cosmicbase** [comment]
OK thanks my promise.

**Review by Lord-Grey — APPROVED** [review]

**Comment by Lord-Grey** [comment]
> OK thanks my promise.

@Cosmicbase Thanks for your contribution!

**Pull request merged**
