### PR TITLE
hyperiond doesnt call switchoff to the leds on exit

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
The refactoring lost the automatic switchoff of leds.
Now we track the hyperion object and delete it on exit (which cleans up the led strips)

**2.** If this changes affect the .conf file. Please provide the changed section
No - but maybe this feature should be a configurable option?

### CODE REVIEW

**Comment by brindosch** [comment]
you may should consider to use different branches for different PRs

**Comment by brindosch** [comment]
edit: ah no everything okay, just resync please :)

**Comment by penfold42** [comment]
I need to do something better - I'm sure im doing it a dumb way

what is the workflow you guys use?
@redPanther ? @brindosch 

ie, you have your fork on github, you have your local repository that you're developing out of....

**Comment by brindosch** [comment]
there is just a small trick, if you want to create more than 2 PRs at the same time, always create branches from the master branch and do you chnages. You will be always even with master and keep it mergable

**Comment by redPanther** [comment]
git remote update
git checkout -b newFeatureBranch upstream/master
Make your changes
git commit
git push origin newFeatureBranch

This is one way ...

**Comment by penfold42** [comment]
this looks much better now!

I've added the main project as upstream, pulled from upstream and pushed to master.

no more fiddly pull requests to my fork anymore!

**Pull request merged**
