### PR TITLE
Ammeded timing to suit new revision of ws2812c

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Ammeded timing to suit new revision of ws2812c
Should also work with WS2813 (but untested)

Included comments on the timing calculations

**2.** If this changes affect the .conf file. Please provide the changed section
nope

**3.** Reference an issue (optional)
#437 

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
btw there is a  new version of ws2813: https://github.com/FastLED/FastLED/issues/449
the older one is not compat with the newer one. I use the new one now with fastled 2812 driver

**Comment by penfold42** [comment]
Oh goodie !

I think I'll write a generic SK-WS 1 wire led device that exposes all the timing as config options.

Until I do that, at least I provided detailed comments to enable quicker rework

**Comment by redPanther** [comment]
With increase of ws2812 reset time to 300ns for 2017 produced 2812 and 2813 should have fairly same timing.

Btw did you notice the upcomming 2815 led? This is a 12v droven stripe. I hope this will become available soon, so we dont have to deal with high amps for larger lef installstions.

Another info is that 2812 is declared obsolete by worldsemi and 2813 will be the replacement

**Comment by penfold42** [comment]
I hadn't heard either - thanks for sharing.

12v brilliant ! I hope they do 3v3 compatible signalling too.

**Comment by brindosch** [comment]
Pictures looks promising, i hope it's not a fake and the lost power isn't crazy high (burned with resistors) :)
The 5V are really annonying. 
@redPanther Slack :)

**Comment by redPanther** [comment]
http://www.world-semi.com/solution/list-4-1.html

**Comment by redPanther** [comment]
https://blog.adafruit.com/2017/05/03/psa-the-ws2812b-rgb-led-has-been-revised-will-require-code-tweak/

**Comment by penfold42** [comment]
Yep - that's the reason for this PR

i wonder if they're using the same die as the 2813

**Pull request merged**
