### PR TITLE
add Pac-Man effect

### PR DESCRIPTION
**Pull request by 7h30n3**
**1.** Tell us something about your changes.
Just adding a new effect.

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
thx! can you add a json schema  file. This is located in effects/schema. This file is needed for the effect configurator and json validation

**Comment by brindosch** [comment]
Sounds funny, thank you!
As i respect your efforts i won't miss the moment and want to ask you if you may be interested in porting this one :)
https://github.com/FastLED/FastLED/blob/master/examples/Fire2012/Fire2012.ino

Would be great :)

**Comment by 7h30n3** [comment]
Is there a guideline for the json schema? The pac-man effect hasn't any changeable properties, so is "required" still "true" and can I leave out "properties" at all or do I have to write 	`"properties":{},` ?

@brindosch I don't know if the Fire2012-Effect is suitable or easily applicable for LEDs in a square arrangement (behind a display).

**Comment by Paulchen-Panther** [comment]
@brindosch  @7h30n3 
Try this. [fire2012](https://gist.github.com/Paulchen-Panther/628ac68be06f3b169cec0740c0ab1eb8)

P.S.: Ist nur eine Testversion. Ist noch ziemlich CPU Hungrig. Und die Richtung der Flamme könnte auch von unten nach oben geändert werden.

**Comment by brindosch** [comment]
I didn't know you did it!
Cool! Yes, some options are never bad which controls the direction or limit it to left/right only /brightness colors/ whatever :)  (like seen in knight rider)

**Comment by brindosch** [comment]
@7h30n3 
I added the effect schema to my current pr. No further actions required :)
I you have some more effect ideas, feel free to PR them :)

Thank you!

**Pull request merged**
