### PR TITLE
Philips Hue APIv2 support

### LINKED ISSUE #1347: Hue Gradient LEDStrip (per zone control/ambilight)
#### What problem does this feature solve?
Hue Gradient LEDStrip can't be controled to feature more then 1 color at the time.
Since a couple of days it's possible in the APP to controle 3 of the 7 zones on a Hue Gradient LEDStrip.
Within the API it's possible to address all 7 zones. These zones are in fixed places within the strip size (55" / 65" / 75")

#### What does the proposed API look like?
REST Api
https://developers.meethue.com/develop/get-started-2/

#### How should this be implemented in your opinion?
When setting up a light source that is Hue and one starts the entertainment control, there should be a check
for the gradient LEDstrip. When detected the size should be confirmed by the user.

#### Are you willing to work on this yourself?
Absolutely! :D
Although my experience in developing is zero...

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

### Added / Changed

Philips Hue
- APIv2 support, incl. full https security and certificate validation
- Multi-Segment device support, e.g. Gradient light
- Use Entertainment area device location for Hyperion layout in addition to manual locations
Option to layout by focussing on full- or only center of entertainment area
- Wizard supports multiple Hue-Bridge discovery
- Support of DIYHue specifics. DIYHue bridge's name must start with "DIY"
- Backward compatibility for bridges not supporting APIv2 and/or Entertainment API
Note: The wizard will configure an APIv2 capable bridge always with Entertainment to ensure the best experience.

### Fixed
- MDNSBrower - Fixed, if timeout while resolving host occurs
- MAC-OS build

### Removed
Philips Hue
- Removed "Switch Off On Black" for APIv2, as the original bridge will switch off LEDs itself.
- Removed "Candy Gamma" for APIv2, as the bridge maps the RGB values best per device.

#### Multi-Bridge discovery
image

#### Configure Lights per Entertainment Area location
image

#### Generated Layout per Entertainment Area and support of Gradient Light
image

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
Fixes #1347

### CODE REVIEW

**Comment by smcclain** [comment]
I built this to try it out with my Hue setup, but it initially did not work-- was getting SSL handshake failures. It turns out older Hue bridges still use self-signed certificates so the certificate validation as implemented here fails on those bridges. I was able to get it to work by always allowing self-signed certs, not just when using a DIY bridge. Thought I would bring it to your attention before this gets released.

**Comment by Lord-Grey** [comment]
@smcclain Thanks for sharing your practical experience!
To better understand where you are coming from… is your point
A) There are bridges with latest firmware out there which make use of self-signed certificates? Or
B) There are bridges out there with self signed certificates and not the latest firmware and people  do not understand why the new feature is not working?

On B) I would not like to encourage people to weaken their security, but update the firmware.
Then it would be just something to be highlighted by documentation/release notes.
If A) then this would be a serious issue and the current workaround for DIYHue could be generalized.

Happy to hear, if there are further aspects for consideration.

**Comment by smcclain** [comment]
it is scenario A-- I am on the latest bridge firmware and still have a self-signed certificate. the API doc states that at some point in the future they will be updated with a non-self signed certificate, but there is no indication as to when that may happen.

**Comment by Lord-Grey** [comment]
Thank you! Seems I then need to make it configurable…

**Comment by Lord-Grey** [comment]
@smcclain Fixed via #1649

**Comment by Lord-Grey** [comment]
@smcclain Id you Tell me on which System you are running, I can provide you a way to test the change without building yourself…

**Comment by smcclain** [comment]
@Lord-Grey  I'm using the Raspberry Pi 4. but I probably won't have time to test out until this weekend, work is getting in the way :)

**Comment by Lord-Grey** [comment]
@smcclain No issues, take your time....
I added the [instructions on how to test](https://github.com/hyperion-project/hyperion.ng/pull/1649#issuecomment-1772323374) to #1649 itself.

**Pull request merged**
