### PR TITLE
Add Trapezoid to LED Layout & WebUI translations

### PR DESCRIPTION
**Pull request by desertblade**
**Summary**
This is from @SputnikElf original pull request: 
"add 4 corner parameter in html, with horizontal and vertical percent values. new calculation of classic led lines. parameters in advance part. default values are for a rectangle."
I just went through and removed conflicts to make it pull able. 

I still use @SputnikElf  cloned branch. This feature makes setting up a Pi Camera easier and allows for trimming  to match your TV.

NOTE: This works fine on my test box (proxmox virtual machine, no LEDS connected). On my RaspberryPI, with camera and LEDS, this branch and master, the web front end does not load. It does not find http://<IP_ADDRESS>:8090/cgi/cfg_jsonserver.  and goes into a loop. I want to debug more and if an issue will open up a defect

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:
image

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
@brindosch Could you see if the JS code is okay?

**Comment by brindosch** [comment]
When you use the full range of the options it generates invalid data.
error

This can be rounded, but will break the led area itself.
Solution depends on how sophisticated this addition should be.

**Comment by desertblade** [comment]
Would you recommend enforcing rounding or other limits in the UI? For example limiting the range to less than 40%

**Comment by desertblade** [comment]
Decided to just add the limits it was super easy to do in the UI

**Comment by brindosch** [comment]
Thank you, this is a good solution. Will be part of the next release.

**Pull request merged**
