### PR TITLE
make blackboder component enable/disable at runtime

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
make blackboder component enable/disable at runtime

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)
#204 
Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
can somebody verify if its realy work?

**Comment by brindosch** [comment]
Will test and report immediately

**Comment by brindosch** [comment]
//confirmed as working to 100%

**Comment by redPanther** [comment]
smmothing bug solved, but when smoothing disabled in config, it cant be enabled via ui

**Pull request merged**
