### PR TITLE
feat(webui): Add French, Turkish, Vietnamese & translation update

### PR DESCRIPTION
**Pull request by brindosch**
**Summary**

Thank you to all contributors. I think we schould export all contributor names for credits.
**Note to myself: Update POEditor connection after merge**

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by m-seker** [comment]
I stumbled yesterday, cool project ! I'll continue supporting Turkish translations as well as the codebase itself.

**Comment by tpmodding** [comment]
@m-seker eyvallah kardesim

**Comment by m-seker** [comment]
@tpmodding lafi mi olur :)

**Comment by brindosch** [comment]
Thank you to all :)

**Comment by brindosch** [comment]
Die neuen Dateien sind für den export gelinkt

**Pull request merged**
