### PR TITLE
color filter config additions

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
add ability to disable specific color corrections
update protobuf external
move smoothing out of color section

**2.** If this changes affect the .conf file. Please provide the changed section
new options in color section: 
transform_enable
temperature_enable
channelAdjustment_enable

see default config for details

**3.** Reference a issue (optional)
#23

### CODE REVIEW

**Comment by brindosch** [comment]
Uh, nice. 
OT: Looks like we need to discuss the whole color adjustments anyway. From HSL(luminance) vs HSV(luminance) over minimumLuminance vs blacklvl and also temperature. :)

**Comment by brindosch** [comment]
If i am right you need to move the smoothing also inside the schema.

**Comment by redPanther** [comment]
thats right ... the temperature thingy annoys me, because it hasn't anything to do with temperature. Its a linear calculated whitepoint.

grrrr ... our test is to good ;-) I had to update the schema files. This is the moment where tests are absolute useful

**Comment by brindosch** [comment]
yeah your tests works pretty good :)

he blacklvl discussion could be done in a way that we may remove the minimumluminance again ang go back to spereated RGB values (At the UI that could be something like "simple/advanced". Your issue here is that the same amount of R/G/B won't work you right? As i see no "real" difference here.

**Comment by redPanther** [comment]
for my taste an easy "blackpoint" and "whitepoint" with linear behaviour is enough for most usecases. Ok it is not perfect, but its easy to code, to use and it's very fast.

For the rgb values we should use 0-255 instead of 0-1. I think this is more understandable and it's easier to use integers then floats.

BTW another topic. I'm sure you know that site: https://github.com/integrations/
I searched for an deployment service. something that will upload after every merged PR to sourceforge.
I found this: https://github.com/integrations/deployhq
It's free for opensource projects.

**Comment by brindosch** [comment]
Hm, okay. deployment from github, but you need binarys to deploy?

Is this one not more our list of interest? https://docs.travis-ci.com/user/deployment

**Comment by redPanther** [comment]
for tags we can use: https://docs.travis-ci.com/user/deployment/releases

**Comment by brindosch** [comment]
Oh, you talked about SF. but i still don't understand who compiles the code for PR deployment :)
Am i miss something?

**Pull request merged**
