### PR TITLE
Fix SEGFAULT in V4L2Grabber

### PR DESCRIPTION
**Pull request by drzony**
**Summary**

Fixes SEGFAULT caused by an improper `auto` deduction.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [x] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@drzony Thanks for your contribution in correcting proper use of iterators!
While you are anyway fixing interators in the given file, would you mind having a check, if the use of interators in the other methods should be "improved" too?

Maybe in 

-  V4L2Grabber::discover()
- V4L2Grabber::enumVideoCaptureDevices()
?

Thank you!

**Comment by drzony** [comment]
@Lord-Grey Corrected iterators in the file, also reduced the number of loops in discover

**Comment by Lord-Grey** [comment]
> @Lord-Grey Corrected iterators in the file, also reduced the number of loops in discover

@drzony Thank you so much for the additional clean-ups and simplification of the code.
Happy hearing from you on further fixes, clean-up or simplifications :)

**Comment by drzony** [comment]
You're welcome

**Pull request merged**
