### PR TITLE
Windows: Add a DDA grabber for much better performance

### LINKED ISSUE #1329: Stuttering with DX or QT screen capture under Windows
- [x] I confirm that this is an issue rather than a question.

## Bug report
When Hyperion is set to capture screen with DX or QT setting, Windows suffers from stuttering
Changing capture frequency or picture decimation makes no change.
Enable or disable Win10 transparency makes no change.
Tried some changes in nVidia settings made no difference.
Tested with Witcher3 it runs fine with no freeze or fps loss.
Does not happen when using Hyperion ScreenCap instead of Hyperion DX or QT.

#### Steps to reproduce
Go to capturing hardware, enable screen capture, set device discovered to DX or QT.

#### What is expected?
Smooth normal Windows behavior.

#### What is actually happening?
Examples:
- freezes when watching video
- moving windows stutters like there was 30fps but 60fps are actually here

#### System

Hyperion Server:
- Build:             (HEAD detached at 2.0.15) (GitHub-70e1043/24a00e3-1676809483)
- Build time:        Feb 19 2023 14:48:39
- Git Remote:        https://github.com/hyperion-project/hyperion.ng
- Version:           2.0.15
- UI Lang:           en (BrowserLang: fr-FR)
- UI Access:         default
- Avail Screen Cap.: qt,dx
- Avail Video  Cap.: v4l2
- Avail Audio  Cap.: audio
- Avail Services:    boblight,effectengine,forwarder,flatbuffer,protobuffer,mDNS,SSDP,borderdetection
- Config path:       C:/Users/.../.hyperion
- Database:          read/write

Hyperion Server OS:
- Distribution:      Windows 10 Version 2009
- Architecture:      x86_64
- Kernel:            winnt (10.0.22631 (WS: 64))
- Root/Admin:        false
- Qt Version:        5.15.2
- Python Version:    3.11.2
- Browser:           Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0

Thank you !

edit: issue remains with 2.0.15

### LINKED ISSUE #1391: Lagg during gameplay
- [x] I confirm that this is an issue rather than a question.

## Bug report
So when I'm playing League of Legends and Hyperion is active, my game stutters when moving a mouse. Didn't have that problem on windows 10, but when i switched to windows 11 it started doing that. 

#### Steps to reproduce
Have Hyperion active, have windows 11, open League and move mouse. 

#### What is expected?
The game running smoothly. Like it runs without Hyperion running. 

#### What is actually happening?
Game stutters when moving mouse.

#### System

Hyperion Server: 
- Build:           (HEAD detached at df149583) (GitHub-dc6aa4dd/df149583-1637501177)
- Build time:      Nov 21 2021 16:50:38
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.12
- UI Lang:         en (BrowserLang: en-US)
- UI Access:       expert
- Avail Capt:      v4l2,qt,dx
- Config path:     C:/Users/nikpe/.hyperion
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Windows 10 Version 2009
- Architecture:   x86_64
- Kernel:         winnt (10.0.22509 (WS: 64))
- Root/Admin:     false
- Qt Version:     5.15.0
- Python Version: 3.10.0
- Browser:        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0

### LINKED ISSUE #1547: NVIDIA NVFBC Grabber
## Feature request

It would be great to be able to use [NVFBC](https://developer.nvidia.com/capture-sdk) to capture the screen.

#### What problem does this feature solve?

Huge performance benefits, and almost completely solve microstuttering

#### How should this be implemented in your opinion?

Like any other grabber, and maybe in a future revision add an option to chose between direct-capture (works with VRR) or not (does not work with VRR, but is able to downscale the grabbed frame, allowing to further enhance performance). The initial implementation should probably just use direct-capture, in order to be as simple as possible.

#### Are you willing to work on this yourself?

Yes, and any help like having a grabber mock implementation would speed up the development a lot

### PR DESCRIPTION
**Pull request by davidsansome**
**Summary**

The [DDA (Desktop Duplication API)](https://learn.microsoft.com/en-us/windows/win32/direct3ddxgi/desktop-dup-api) was added in DX11 and allows for GPU-assisted screen capture on Windows. This PR adds a new `DDA` grabber that uses this API.

[Video comparing the old DX grabber with the new DDA grabber](https://drive.google.com/file/d/1JmhZtQYjouk7A9WJGswQG3ZotTdxg14r/view?usp=sharing)

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [X] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
Fixes #1329 
Fixes #1391 
Fixes #1547

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@davidsansome Thank you very much for your contribution.
The grabber performance much improved!

Could you please have a look at the Picture decimation and the Cropping values?
It looks like that any change in the values do not have any effect currently.

image

Maybe here the GPU can help too, if it is already possible to receive a cropped image in a target size....

**Comment by davidsansome** [comment]
Thanks for taking a look @Lord-Grey!

I've implemented cropping and pixel decimation. I decided to do it in software because it was much easier than trying to do it with the directx API, and performance is fine as is anyway.

I was taking a look through the bug tracker and I think this PR will probably fix #1547 (NVFBC [is deprecated](https://developer.download.nvidia.com/designworks/capture-sdk/docs/NVFBC_Win10_Deprecation_Tech_Bulletin.pdf) and DDA is the replacement), #1329 (the HyperionScreenCapture project referenced as a fix there actually uses DDA) and #1391.

**Comment by Lord-Grey** [comment]
@davidsansome Thanks for doing the changes. They look good for me.
A performant Windows Screengrabber was outstanding since a while, as you have seen with the issues you linked too.
Great that you addressed the issues, providing a new grabber.

**Comment by Lord-Grey** [comment]
@davidsansome Is the PR ready to be merged from your side or do you plan additional testing or changes?

**Comment by davidsansome** [comment]
Yes I think this is ready to be merged now! I've been running it locally for a few days without issues.

I have a few more ideas for performance improvements but I'll need to do some more investigation first. I might send some separate PRs in the next few weeks!

**Review by Paulchen-Panther — APPROVED** [review]

**Comment by Lord-Grey** [comment]
Yes. Screengrabber performance is a topic.
For videograbbers multi-threading was introduced, but the overall grabber code is lacking an overall, consistent design.

@Paulchen-Panther had a start some time back on [refactoring grabbers](https://github.com/Lord-Grey/hyperion.ng/tree/grabber_refactor). But due to time constraints and other priorities that was never brought forward.
Maybe it is something you would like to have a look too as food for thought.

Potentially, you had something different in mind…
I am curious what the upcoming PRs will bring. 😀

**Pull request merged**
