### PR TITLE
Use direct URL of GIF file rather than HTML page

### PR DESCRIPTION
**Pull request by jamieburchell**
**Summary**

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [X] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by jamieburchell** [comment]
Note that the output of the URL "https://i.gifer.com/1j6F.gif" changes depending on the HTTP accept header.

**Comment by Lord-Grey** [comment]
@jamieburchell Thank you very much for your contribution!

**Comment by jamieburchell** [comment]
Well despite my best efforts @Lord-Grey this effect still doesn't work. I even copied the fire effect as a custom effect and swapped out the gif for the matrix one but still can't get it to work.

**Comment by Lord-Grey** [comment]
@jamieburchell Maybe you could share how you start the effect?

I started the Matrix effect directly from the Remote Control, plus I create a new effect using the Matrix one as a template.
Both ways work...

image

**Comment by jamieburchell** [comment]
No, neither methods work. If I choose "Fire" (which I understand is also an animated GIF) that effect works.

**Comment by Lord-Grey** [comment]
The main difference between the Fire and the Matrix effect is, that for Fire the image is already available on disk whereas with Matrix, the effect loads the gif from the Web into memory first.
Does your rpi has proper network connectivity and access to the Web?

**Comment by jamieburchell** [comment]
It certainly does, so I'm not sure what is going on.

**Comment by jamieburchell** [comment]
When I tried to create a custom effect and placed the gif in the effects directory, I couldn't seem to get that to work either. Is that the correct place to put the images referenced in the custom effects file?

**Comment by Lord-Grey** [comment]
How does the Log output look like (in Debug mode)?

**Comment by jamieburchell** [comment]
https://pastebin.com/raw/9ALY5cjg

Yep 2.0.13

**Comment by jamieburchell** [comment]
I just tried to create a new effect based on Matrix and used the local file upload to upload the gif, but this still does not work.

**Comment by Lord-Grey** [comment]
I get the same error, if have no network connectivity.
What does the following command comes back with, when you execute it on your rpi with the same user hyperion run under?

`wget https://i.gifer.com/embedded/download/1j6F.gif`

**Comment by jamieburchell** [comment]
Yeah, it works I tried that before...

```
osmc@osmc:~$ ps aux | grep hyp
osmc       499  5.5  4.0 248684 30876 ?        Ssl  Jun07 164:59 /usr/bin/hyperiond
osmc     15131  0.0  0.0   2204   592 pts/0    S+   16:56   0:00 grep hyp
osmc@osmc:~$ wget https://i.gifer.com/embedded/download/1j6F.gif
--2022-06-09 16:57:07--  https://i.gifer.com/embedded/download/1j6F.gif
Resolving i.gifer.com (i.gifer.com)... 51.68.36.8
Connecting to i.gifer.com (i.gifer.com)|51.68.36.8|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 239117 (234K) [text/plain]
Saving to: '1j6F.gif'

1j6F.gif     100% 233.51K  --.-KB/s    in 0.06s   

2022-06-09 16:57:08 (3.92 MB/s) - '1j6F.gif' saved [239117/239117]
```

**Pull request merged**
