### PR TITLE
Swedish Translation

### PR DESCRIPTION
**Pull request by T-IOOO**
Swedish translation for Hyperion.ng!

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
@brindosch 
We should also take a look at the other languages:
translations


@T-IOOO 
Thank you for the Translation

**Comment by tpmodding** [comment]
@RickDB and @WoLpH  could translate it to dutch

**Comment by WoLpH** [comment]
How are translations managed these days? Are we using Mygengo? If not, we should... makes translations a whole lot easier and they can at least be done somewhat automatically :)

As for Dutch translations... I doubt it's that useful. Even my 3 year old understands a bit of basic English already. Any grown up Dutchie should understand English ;)

**Comment by brindosch** [comment]
Thank you for the contribution.
Is this the same we got at POEditor @T-IOOO ?

@Paulchen-Panther 
Du hast die Verbindung mit Github auf diesem repo. Entsprechend musst du die Dateien verlinken und exportieren

**Comment by brindosch** [comment]
@WoLpH 
We use POEditor
https://poeditor.com/join/project/Y4F6vHRFjA

**Comment by Paulchen-Panther** [comment]
@brindosch 
Ich werde es mal probieren. Versuch macht kluch.

**Comment by T-IOOO** [comment]
Correct! It’s from poeditor, sorry im a NOOB 😊

**Comment by Paulchen-Panther** [comment]
@tvdzwan @RickDB  @WoLpH @tpmodding
Have anyone access to this email adress and confirm the request from POEditor please?

Screenshot

**Comment by WoLpH** [comment]
> @WoLpH
> We use POEditor
> https://poeditor.com/join/project/Y4F6vHRFjA

That looks good too. It seems that I'm a bit out of date anyhow... Mygengo (now Gengo) doesn't have a free version anymore. Too bad because it was absolutely amazing at some point :)

Thanks @T-IOOO btw!

**Comment by T-IOOO** [comment]
Thank you, I am new to all this and POEditor aswell. But it was very easy since the UI is very simple and user friendly. Easy to update the language files too when new lines are added during development

**Pull request merged**
