### PR TITLE
github actions replaces azure (release creation)

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

The release creation was migrated to GitHub Actions to replace Azure DevOps. If a (lightweight) tag is assigned to a commit, the normal CI workflow starts and uploads the corresponding artifacts. In the publish step, all artifacts are uploaded to a newly created draft release. This means that the TAG creator can still edit the (pre) release before publishing.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by brindosch** [comment]
Großartig, ist schick geworden!

**Comment by brindosch** [comment]
Soll die azure.yml bleiben oder kann die weg?

**Comment by Paulchen-Panther** [comment]
Kannst du erst mal mit drin lassen. Ist ja in der Readme.md auch noch drin. 2 CI checks sind besser wie keiner. 😁

**Comment by brindosch** [comment]
Gut, der Test im fork ist durchgelaufen, gh-pages und release creation funktioniert.

**Comment by Paulchen-Panther** [comment]
Ich erstelle nie nicht funktionierende PRs. 🤣

**Pull request merged**
