### PR TITLE
Decrease compile time

### PR DESCRIPTION
**Pull request by m-seker**
**Summary**

Changed files are recompiled at every build due to generated flat buffer headers. Use forward declaration to reduce the time spent while compiling those.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
Thank you very much. Are you done here?

**Comment by tihoangyeudau** [comment]
i saw this commit make crash when first opening soft after installing

**Comment by m-seker** [comment]
@tihoangyeudau  Can you be more clear ? Opening what ? Installing what ? This PR just replaces header inclusion with forward declaration. Any development error should reveal itself in compile time, not in runtime.

**Comment by tihoangyeudau** [comment]
> @tihoangyeudau Can you be more clear ? Opening what ? Installing what ? This PR just replaces header inclusion with forward declaration. Any development error should reveal itself in compile time, not in runtime.

sorry, i cleaned and rebuilded then it works correctly

**Pull request merged**
