### PR TITLE
implement optional color correction for V4L only

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
Now it is possible to have color adjustment and color transform only for v4l input.
This is needed, because usb grabber often need heavy color adjustment, while effects, solid color or screen capturing often needs no correction.
Now you have the choice!

_additionals:_
 hyperion update function now knows from which component the current color comes. Perhaps this info might be handy in time ...
color temperatue is removed ... I don't like duplicated code!

webui: adapt config write to latest qjson PR. This function will always commit full config, regardless if your input is full config or a part of it.

**2.** If this changes affect the .conf file. Please provide the changed section
2 new values in color section:
		"channelAdjustment_v4l_only" : true,
		"transform_v4l_only" : true,

look default configs for details.
I set default to "true", so by default color correction is only for v4l. I think this is the most usecase ...

and: **color temperatue is removed**. The same thing can be achieved with color adjustment

**3.** Reference an issue (optional)
#59

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
amazing again :)
note: hyperion-remote cleanup is missing (temperature)
Q: Now if you add a second transform object into the array with splitted leds (0-50 and 51-80) does it still work to assign it properly to v4l2 only?

> I think this is the most usecase ...

Hm, hard to say. As long Openelec is the download count leader i bet against it ;)

**Comment by redPanther** [comment]
if you assign v4l_only any color object will be v4l only. Currently you only have the choice to assign to all input sources or only to v4l.
hyperion remote is now cleaned. There was also the old correction ... I removed it too, because it was the same as temperature.

**Comment by redPanther** [comment]
... and changed defaults to v4l_only false - this is the same behavior as we have now.

**Comment by Paulchen-Panther** [comment]
Auch von mir ein großes Danke für diesen PR. Respekt.

**Pull request merged**
