### PR TITLE
migrate std::string to qstring + add sysinfo via json

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- migrate std::string to qstring where it is usefull
- add sysinfo via json (hyperion-remote -s)

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)
#411 

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Amazing! Will use it :)

These lines could be removed
https://github.com/redPanther/hyperion.ng/blob/7ca0e65178aa59e6bc4afcc2720f62ea947bcae5/libsrc/jsonserver/JsonClientConnection.cpp#L596-L597

**Comment by redPanther** [comment]
I thought about splitting serverinfo in a static and dynamic part.
'sysinfo' is catched on webui launch and contains stuff that doesnt change and 'serverinfo' contains stuff that changes and this is called continously

**Comment by brindosch** [comment]
Q: How often you change a hostname, and bothers it that you need a restart of hyperiond to reflect it everywhere?

It's up to you, but i won't check hostname change on every poll on ui. (And i am confident other app devs won't do it too)

**Comment by redPanther** [comment]
Its not what I meant. I want to move more things to sysinfo. E.g. the hyperion version numbers .... I will delete those lines you suggested ...

**Comment by brindosch** [comment]
Ah, the entire static server info. Yes that makes sense
So add a checksum to serverinfo and push onChange to all open websockets with max interval of 500ms/1s? ;)

**Comment by redPanther** [comment]
Now I integrated sysinfo call into webui. "sysinfo" is called only one time and "serverinfo" as before continuously.

**Pull request merged**
