### PR TITLE
logging rework json/proto

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
- rework logging for ptoto and json component
- mDNS responter moved to Debug level
- Blackborder to debug, until this is enhanced

What shall i do with the: throw std exceptions?

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)
- https://github.com/hyperion-project/hyperion.ng/issues/25
Note: I need to clean the commit history

### CODE REVIEW

**Comment by redPanther** [comment]
> What shall i do with the: throw std exceptions?

don't touch the exceptions.

**Comment by brindosch** [comment]
Do nothing? okay :)

**Comment by redPanther** [comment]
you can't do anything. the exception is thrown from somewhere and caught in main.cpp

There the exception message is put into logger message.

**Comment by redPanther** [comment]
BTW I reformated the initializer list in code that I changed in that last times. Perhaps you do the same? My experience is, that the new format is better readable and prevent mistakes when modifying the initializers.

what I mean:
changing from:
```
MyClass::MyClass() :
  QObject(),
  _myvar1("blub"),
  _myvar2(1000),
  _myvar3(true)
{
....
}
```
to

```
MyClass::MyClass()
  : QObject()
  , _myvar1("blub")
  , _myvar2(1000)
  , _myvar3(true)
{
....
}
```

initializer indention is one 'tab'.

**Pull request merged**
