### PR TITLE
Add Home Assistant Lights support

### LINKED ISSUE #1703: Add Home Assistant support
## Feature request

It would be a nice addition if an native home assistant api could be implemented as an led hardware.

#### What problem does this feature solve?
This solves the issue of doing workarounds like emulate hue bridge in home assistant or something like this: https://community.home-assistant.io/t/use-home-assistant-lights-with-hyperion/678249/2

#### What does the proposed API look like?
See here, it's well documentated.: https://developers.home-assistant.io/docs/api/rest/

#### How should this be implemented in your opinion?
You could choose an entity for a single led on the led hardware setup.

#### Are you willing to work on this yourself?
No, sadly not.

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

- Add Home Assistant Lights support

A list of HA Lights can be mapped to one layout area currently.
For another capture areas an additional instance would be required.

It is recommended to set the latchtime to ensure that a certain time passes between two updates.
The solution cannot run with high fps and should only used for solitary lights, i.e. not the main ones.

**Configure the device**
1. In preparation, create a [Long-lived access token](https://developers.home-assistant.io/docs/auth_api#long-lived-access-token) in Home Assistant
2. Select Controller Type: homeassistant
3. Hyperion tries to find your Home Assistant server. If not provide a custom hostname or IP-address
4.Put the long lived token generated before in "Authorization Token" 
5. Select your HA light(s) from the list
6. You might do "identify" to check, if the provided light light up
7. Set the LED position in the layout using the wizard
8. Save 

See the screenshot below for reference

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [X] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

Screen in default settings mode
image

Screen in Expert settings mode
image

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Fixes #1703

### CODE REVIEW

**Comment by satgit62** [comment]
@Lord-Grey

Hello,

Took the time to test the new “HomeAssistant” build. 
I took the build branch from @Lord-Grey as a reference and built it for LG webOS. It worked right away and after the daemon start I got busy with the “HomeAssistant” LED controller in HyperHDR.

My short conclusion:

I can select all the lamps I have set up in Home Assistant and set them up in an instance.  I have added another instance to an existing Ambilight instance of HyperHDR on “adalight” LED controllers with HyperSerial and set up two Home Assistant IDs. You can specify in the LED layout which position the lamps should have.
I also configured two additional instances for left and right. This also worked wonderfully.

I only have a simple Hue Bridge for the ZigBee lamps and via this, I have also integrated the Hue and other ZigBee compatible lamps into my Home Assistant. 
This could cause a delay. With a short update interval and low FPS, the delay is kept within limits, and you won't be bothered by it. I don't know how this behaves with a real USB ZigBee Bridge. You also have to see whether you can address the lamps in Home Assistant via the entertainment area of the HUE so that the latency is reduced.

In any case, it is a super addition to the already extensive LED control of the Hyperion.NG.
I'm also looking forward to completing the implementation and hope for further development. Many thanks again to @Lord-Grey for the quick implementation.

[About Hyperion](https://github.com/user-attachments/assets/9f3606a4-4a92-442d-a1af-d5ca9857f7ab)
Hyperion NG Controller 1_adalight
Hyperion NG Controller Homeassistant

**Comment by Lord-Grey** [comment]
@satgit62 Just note, that currently the HA Light IDs will map only to the first LED in the layout.
Your screenshot indicates that you assume that ID1 will map to layout LED 0 and ID2 maps to layout LED 1.

**Comment by satgit62** [comment]
> @satgit62 Just note, that currently the HA Light IDs will map only to the first LED in the layout. Your screenshot indicates that you assume that ID1 will map to layout LED 0 and ID2 maps to layout LED 1.

Yes, I know that, I found out.
I just wanted to see if two lamps can register at once under one instance.
But I also made separate instances and that works with the mapping, only I didn't take a screenshot of it.

**Comment by Lord-Grey** [comment]
Yes, the current way gives most flexibility.
You can have multiple lights for one instance and you can have many instances.

**Comment by eporsche** [comment]
@Lord-Grey 

I would like to test your PR  - however when I issue the command:
wget -qO- https://raw.githubusercontent.com/hyperion-project/hyperion.ng/master/bin/scripts/install_pr.sh | bash -s -- -t github_token -c ~/.hyperion 1763

I get this:
---> Download package for identified runtime architecture: arm64 and Qt6
---> The specified PR #1763 has no longer any artifacts.
---> It may be older than 14 days. Ask the PR creator to recreate the artifacts at the following URL:
---> https://github.com/hyperion-project/hyperion.ng/pull/1763

Would you mind recreating the artifacts? Thank you very much! 😄

**Comment by Paulchen-Panther** [comment]
> Would you mind recreating the artifacts? Thank you very much! 😄

https://github.com/hyperion-project/hyperion.ng/actions/runs/9997312040?pr=1763

Once the workflow is complete, the artifacts should be available again.

**Comment by eporsche** [comment]
Installation worked - thank you!

**Comment by kylewhirl** [comment]
How do I install this on Hyperbian?

**Comment by eporsche** [comment]
@kylewhirl  I followed this: https://docs.hyperion-project.org/user/advanced/Testing.html
However the first time I tried it - it overpowered my zigbee2mqtt / mosquitto server with requests - I need to play with the settings.

**Comment by popy2k14** [comment]
Guys, thanks for your efforts and sorry that i found not more time to test this.

**Comment by Lord-Grey** [comment]
@popy2k14 You can still do testing and provide feedback, even the PR was merged. 😃

**Comment by popy2k14** [comment]
@Lord-Grey i will, but dont know when i find time

**Comment by Kesp92** [comment]
Hi there @Lord-Grey 
i just installed, Hyperion Ng in  docker with the following file https://hub.docker.com/r/foorschtbar/hyperion .
But i got the Problem that the controlType homeassistant isn't shown any ideas?

**Comment by Lord-Grey** [comment]
You need to install the nightly build

**Comment by Pichuhoehle** [comment]
@Lord-Grey Is there any docker image, which has the nightly/dev builds?

**Comment by Lord-Grey** [comment]
Unfortunately, I do not know.

**Comment by flayzer** [comment]
@Lord-Grey Thank you so much for this! Really appreciate the effort and work you’ve put into this feature.

I’ve got a quick question about how the LED instance determines its brightness value. Is this a static value, or does it adjust dynamically based on input?

I’m currently using a TP-Link Tapo L535B bulb, and I’ve noticed that when the screen is dark or black, my light is still bright as day. Is this just a quirk with the type of light I’m using, or is there something in the configuration I might have missed?

Running Version | 2.0.17-beta.2+nightly20241118bc1bfbc83a6f310f03e1328587985ac52babeb01

Here’s the debug log I’ve captured for reference:

`[LEDDEVICE|Overhead] (DEBUG) (ProviderRestApi.cpp:274:executeOperation()) POST took 26ms, HTTP 200: [http://192.168.x.x:8123/api/services/light/turn_on] [{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[0,0,0]}]`

**Comment by Lord-Grey** [comment]
@flayzer Did you solve the issue with your Tapo lights?

**Comment by flayzer** [comment]
@Lord-Grey Yep, I managed to solve it! I just had to enable the advanced settings toggle. 😅

Thanks for all your hard work on this. It's working perfectly now. 🙌

**Comment by Lord-Grey** [comment]
@flayzer Could you do me a favour and test how the Tapo lights behave with different color/brightness combinations?
It looks like some devices cannot deal with brightness >0 and full black color (I see it on a Yeelight too).
Before doing a fix, I would like to get an idea how some lights behave.

Would you be able to run the following commands against your "overhead_light_bulb" bulb?
Replace TOKEN by the token you configured in Hyperion and update the IP address.
The first command is always sending full red to see the behaviour of the next command

1.  Full brightness / Black (Current Misbehaviour)

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[255,0,0]}'`

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[0,0,0]}'`

2. Full brightness / a slight lighter Black

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[255,0,0]}'`

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[1,1,1]}'`

3. No Brightness / Black

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[255,0,0]}'`

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"entity_id":["light.overhead_light_bulb"],"rgb_color":[0,0,0]}'`

4. Brightness 0 / Black (it should switch of the light)

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":255,"entity_id":["light.overhead_light_bulb"],"rgb_color":[255,0,0]}'`

`curl -X POST -H 'Authorization: Bearer TOKEN' -i 'http://192.168.x.x:8123/api/services/light/turn_on' --data '{"brightness":0,"entity_id":["light.overhead_light_bulb"],"rgb_color":[0,0,0]}'`

I think we should go for 4. but I would like to validate...

**Comment by flayzer** [comment]
Yeah, sure. Happy to help.

I noticed my bulb doesn't handle full black colour well, so I've opted for the "Switch off on black" option.

### 1. Full brightness / Black (Current Misbehaviour)
**Behaviour:** Bright white light
**Attributes:**
```
min_color_temp_kelvin: 2500
max_color_temp_kelvin: 6500
min_mireds: 153
max_mireds: 400
supported_color_modes:
  - color_temp
  - hs
effect: "off"
color_mode: hs
brightness: 255
color_temp_kelvin: null
color_temp: null
hs_color:
  - 0
  - 0
rgb_color:
  - 255
  - 255
  - 255
```
### 2. Full Brightness / Slightly Lighter Black
**Behaviour:** Bright white light
**Attributes:** Same as Test 1.

### 3. No Brightness / Black
**Behaviour:** Bright white light
**Attributes:** Same as Test 1.

### 4. Brightness / Black (Expected Behaviour: Switch Off)
**Behaviour:** Light switches off as expected.
**State:** `off`

**Note:** If the goal is to offer an alternative to turning the light off on black, perhaps allowing users to set a static RGB/brightness value (like a dim off-white) could be a viable solution. However, I’m unsure if this would be feasible to implement. I experimented with the backlight threshold options, but they didn’t quite achieve the effect I was aiming for.

Let me know if there’s anything else I can try.

**Comment by Lord-Grey** [comment]
@flayzer Thanks for your very quick feedback!!!
I have created PR #1818 removing „Turn off on black“ in favour of setting brightness = 0 when Black. That better fits the HA Light Implementation.
The HA Integrations should better know, if they can turn off or display black.

Would be great, if you could test the PR.
See [here](https://docs.hyperion-project.org/user/advanced/Testing.html#pull-requests) how to do without affecting your current installation. If you are on Windows or osX, you can download an artifact from the latest PR build.

**Comment by flayzer** [comment]
@Lord-Grey I've tested the PR, and it's working as expected with my Tapo lights :)

**Pull request merged**
