### PR TITLE
update adalight sketch

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- add analog output to adalight sketch 
- add basic color corrections to adalight sketch
- add possiblility to switch of leds when no new data is comming in
- some refactoring of that sketch

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)
#284 

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
@penfold42 this is needed when smoothing is off. smoothing output is mostly fast (in ms interval), the serial refresh time is more a "keep alive" and has an interval in seconds

**Comment by penfold42** [comment]
Cool - we should probably consider doing this for all led device types ?

**Comment by redPanther** [comment]
Good idea. The code for refresh is not new in rs232. I made it available in webui.
I will move it to leddevice baseclas by time.

**Comment by redPanther** [comment]
What l havn't mentioned, the new adalight sketch make it possible to drive addressable and analog stripes at the same time.

**Comment by redPanther** [comment]
Hi, last days I puzzeled with my new sketch. The analog was flickering. I've thought my sketch was to slow or pwm interferes with fastled - yesterday I found the cause. Thx to my scope, I found out that some pins have 'faster' pwm then other and they are out of sync!
Here some info on that topic http://playground.arduino.cc/Code/PwmFrequency

I will update my sketch according to this new knoledge

**Pull request merged**
