### PR TITLE
V4l2 input

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

This PR reintroduces the input parameter into Hyperion. As in the classic version of hyperion, the input of a v4l device can be selected. As an example, I list the EasyCap Video USB Grabber (Fushicai UTV007), which also has two inputs (Composite / S-Video).

chips-utv007-new-usb-2-0-easycap-dc60-tv

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

before:
before

now:
after

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Fixes: #817

### CODE REVIEW

**Comment by newkind** [comment]
@Paulchen-Panther WHOAH! That's awesome! Thank you very much <3 This is exactly what I need for my EasyCap EMPIA chip based clone. Is there a buildbot where I could grab a build with this PR for my CoreElec?

**Comment by Paulchen-Panther** [comment]
> This is exactly what I need for my EasyCap EMPIA chip based clone. Is there a buildbot where I could grab a build with this PR for my CoreElec?

The good news: The [build bot](https://github.com/hyperion-project/hyperion.ng/pull/825#issuecomment-640249336) is exactly above your post.
The bad: The AARch64 release is only generic. So it does not run on CoreELEC, because this requires special dependencies. You can only contact @portisch in the CoreELEC forum and ask him about when a new release will be created.

**Comment by newkind** [comment]
@Paulchen-Panther I'll contact Portisch, thank you one more time!

**Comment by NKnusperer** [comment]
How do I 'install' a PR build?
Just extract the zip/tar and run the binary?

**Comment by Paulchen-Panther** [comment]
@NKnusperer Yes.

**Comment by moe7863** [comment]
USB webcams no longer seem to be working since this implementation. My camera is recognised by Hyperion ng but throws the following errors: **V4L2:/DEV/VI : Throws error nr: VIDIOC_STREAMON error code 5, Input/output error
V4L2:/DEV/VI : Throws error nr: VIDIOC_STREAMON error code 28, No space left on device**

My webcam video format is: UYVY

Thanks

**Pull request merged**
