### PR TITLE
Updated compile instructions for Mac OS

### PR DESCRIPTION
**Pull request by rudelm**
I've updated the compile instructions for Mac OS. I've tested them on Sierra and El Capitan.

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by b1rdhous3** [comment]
With El Caption the old instruction stopped to work. I remember an error at the cmake command. Now since you have changed that in this PR i hoped it would work again, but nope: not for me :D

 Failed to find "gl.h" in
  "/System/Library/Frameworks/OpenGL.framework/Headers;/System/Library/Frameworks/AGL.framework/Headers".
Call Stack (most recent call first):
  /usr/local/opt/qt5/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:141 (include)
  /usr/local/opt/qt5/lib/cmake/Qt5/Qt5Config.cmake:26 (find_package)
  CMakeLists.txt:175 (find_package)

**Comment by rudelm** [comment]
Thats strange. On my Mac Mini with El Capitan the same instructions worked. I've tested them first on Sierra before I tried it on El Capitan and they worked :/ Did you brew update before to make sure that QT5 is in its newest version?

**Comment by b1rdhous3** [comment]
Ah good hint there. I will update it and will come back to you shortly.

**Comment by redPanther** [comment]
Thx for testing!
I'm a bit curios about the cmake call:
`cmake -DENABLE_V4L2=OFF -DENABLE_OSX=ON -DENABLE_X11=OFF -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.7.0 ..`

v4l and x11 are disabled by default on osx, so this should not be needed.
I suggest:
`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.7.0 ..`

and instead of copy do:
`sudo make install`
`sudo mkdir -p /usr/local/share/hyperion/effects`
(will not be needed in future)

**Comment by b1rdhous3** [comment]
It is compiled now :)
For some reason cmake always tried to find MacOX10.11.sdk but it wasn't available on my mac. 
so i added this argument to the command: `-DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/ `
and it worked :)

**Comment by rudelm** [comment]
Hm I've tried now redPanther's command and it compiled with v4l and x11 set to off:

`cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.7.0 ..`

So I think that should be then the default. Disabling V4L was part of the old instructions and it complained about X11 so I had to disable it. The Make install prefix should trigger the creation of a makefile to install the bins to that folder but it doesn't seem to work, neither from the build folder nor from the hyperion.ng folder:

`sudo make install
Password:
make: *** No rule to make target `install'.  Stop.`

**Comment by redPanther** [comment]
whats puzzling me is, that it is already the default on osx. This issue was discovered before and was resolved ... anyway I do some changes right now in that area.
In the meantime, can you try it again, but remove the build folder before - perhaps the cmake cache disturbs here

**Comment by rudelm** [comment]
Oh I've just seen that I've overlooked the execution results from last time, it complained already on the first time after I've removed the build folder about missing X11 :(

**Comment by rudelm** [comment]
This command always works for me:

`cmake -DENABLE_V4L2=OFF -DENABLE_OSX=ON -DENABLE_X11=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.7.0 ..`

So I guess the autodetection of Mac OS doesn't seem to be working.

I also forgot to make build before I executed make install. Now its installing to /usr/local/share/hyperion correctly. I'll update the pr accordingly

**Comment by redPanther** [comment]
On osx platform is accidently recognized as x86/64 linux not as osx. Cmake output should proof that.

Will make a fix when I'm home today.

Btw instead of manual strip use
make install/strip
This should install and strip the bins

**Comment by redPanther** [comment]
can you retry with latest github version? I've made some improvements.

**Comment by rudelm** [comment]
Tried your changes @redPanther and it compiled. I've removed the build folder and updated the CompileHowto.md accordingly. I could hyperiond start and access the webinterface. Thanks for the update in the CMakeLists

**Comment by b1rdhous3** [comment]
Nice, i will try it tomorrow as well.

**Comment by rudelm** [comment]
Thanks for merging it!

**Comment by b1rdhous3** [comment]
@rudelm Sorry for digging out this topic, but I am not able to compile for Sierra. What is your experience? Are you able to compile for sierra?

I am getting these all the time during cmake:

Target "hyperion" links to target "Qt5::SerialPort" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

I linked the qt5 folder

Thanks!

**Comment by brindosch** [comment]
Is qt5serialport also in your qt5 dir? Is it just serialport?
At the meantime qt released qt5.9. But the discovery should still work.

Also for @rudelm 
If someone wants to improve the osx stuff. A closer look on https://cmake.org/cmake/help/v3.0/module/CPack.html
https://cmake.org/Wiki/CMake:CPackPackageGenerators
to build deploy packages would be great.
@Starbix already started here some time ago: https://github.com/Starbix/hyperion.ng/commits/macos

**Comment by b1rdhous3** [comment]
This is the complete cmake output:
`cmake -DENABLE_V4L2=OFF -DENABLE_OSX=ON -DENABLE_X11=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.9.1/ ..
-- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- PLATFORM: osx
-- ENABLE_AMLOGIC = OFF
-- ENABLE_DISPMANX = OFF
-- ENABLE_FB = OFF
-- ENABLE_OSX = ON
-- ENABLE_SPIDEV   = OFF
-- ENABLE_TINKERFORGE = ON
-- ENABLE_V4L2 = OFF
-- ENABLE_WS281XPWM = OFF
-- ENABLE_X11 = OFF
-- ENABLE_TESTS = OFF
-- ENABLE_PROFILER = OFF
-- validate json files
   checked files: 52 success: 52 errors: 0
-- validate json effect files
   checked effect files: 31 success: 31 errors: 0
-- validate json file
-- Current Version: master (GitHub-e49fabc/622a171-1499289592)
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found Qt Version: 5.9.1
-- Found libusb-1.0:
--  - Includes: /usr/local/include/libusb-1.0
--  - Libraries: /usr/local/lib/libusb-1.0.dylib
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.8") 
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Protobuf: doing try-compiles for hash map/set headers
-- Protobuf: doing try-compiles for pthread test
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Using protobuf compiler: /Users/jan/Desktop/hyperion/build/bin//protoc
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10") 
-- Configuring done
CMake Warning (dev) at libsrc/hyperion/CMakeLists.txt:48 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hyperion" links to target "Qt5::SerialPort" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/commandline/CMakeLists.txt:33 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "commandline" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/jsonserver/CMakeLists.txt:27 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "jsonserver" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/protoserver/CMakeLists.txt:39 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "protoserver" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/bonjour/CMakeLists.txt:28 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "bonjour" links to target "Qt5::SerialPort" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/boblightserver/CMakeLists.txt:22 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "boblightserver" links to target "Qt5::SerialPort" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/udplistener/CMakeLists.txt:20 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "udplistener" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/kodivideochecker/CMakeLists.txt:20 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "kodivideochecker" links to target "Qt5::SerialPort" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/effectengine/CMakeLists.txt:43 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "effectengine" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/grabber/osx/CMakeLists.txt:21 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "osx-grabber" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libsrc/webconfig/CMakeLists.txt:41 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "webconfig" links to target "Qt5::SerialPort" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/hyperiond/CMakeLists.txt:8 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hyperiond" links to target "Qt5::SerialPort" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/hyperion-remote/CMakeLists.txt:24 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hyperion-remote" links to target "Qt5::SerialPort" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at src/hyperion-osx/CMakeLists.txt:26 (add_executable):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "hyperion-osx" links to target "Qt5::SerialPort" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/jan/Desktop/hyperion/build`

I tried several ones. But all lead to the same issue with qt.
The qt is the newest version available through brew.

**Comment by brindosch** [comment]
As far as i see, no error, just warnings. Well we should get rid of them :)

**Comment by b1rdhous3** [comment]
Yes, but hyperiond is acting very strange. When I want to start it I get Segmentation Faliure: 11 in 95% of start attemps. The application won't start with this kind of error.
So my first assume was that the build is not done correct with those warinings.

**Comment by rudelm** [comment]
hi guys,

I've upgraded qt5, cmake and doxygen so I've got the newest version on Sierra. I was able to compile without errors. However, I saw a few warnings like

``-- Configuring done
CMake Warning (dev) in src/hyperion-remote/CMakeLists.txt:
  Policy CMP0043 is not set: Ignore COMPILE_DEFINITIONS_<Config> properties.
  Run "cmake --help-policy CMP0043" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.``

I did not start hyperiond with a valid config, since I don't want to mess with my current setup. However, starting hyperiond without any parameter was at least successful and asked for parameters ;)

**Comment by brindosch** [comment]
Greetings @rudelm 
i had a look at the cmake in a whole and updated some commands, the SerialPort message of @b1rdhous3  was legit, while every compiler & version behaves slightly different so it wasn't a common issue at all.
See more here: https://github.com/hyperion-project/hyperion.ng/pull/451

Thank you for your time

**Pull request merged**
