### PR TITLE
Kodi checker rework

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
kodichecker rework
- use new logger
- 'enable' flag in config
- startable, stoppable and reconfigure on runtime
- rename xbmc to kodi

**2.** If this changes affect the .conf file. Please provide the changed section
now xbmc is kodi:
```
 	"kodiVideoChecker" : 
 	{
 		"enable" : true,
 		"kodiAddress" : "127.0.0.1",
 		"kodiTcpPort" : 9090,
 		"grabVideo" : true,
 		"grabPictures" : true,
 		"grabAudio" : true,
 		"grabMenu" : false,
 		"grabPause" : false,
		"grabScreensaver" : true,
 		"enable3DDetection" : true
},
```

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
nice work!
Could you add the enable flag to our commented and default .json? Then it is complete. :) 
Don't think to hard about the json checker schema, Paulchen-Panther reworked this already.

**Comment by redPanther** [comment]
I just do that ;-)

**Comment by brindosch** [comment]
Aww what is this?
libsrc/effectengine/EffectDefinition.schema.json

A copy of the json checker schema? Delete?

**Comment by redPanther** [comment]
let us think about schema defs later. There is some work todo.

config is updated.

**Comment by brindosch** [comment]
Thank you, i just saw this schema and now i am confused why we have it 2 times ;)
But as already pointed out from Paulchen, the result of the checker is never used to output something (like a warning) so this is just another point at the long list of boring todos :)

**Comment by brindosch** [comment]
just for tracking
https://github.com/hyperion-project/hyperion.ng/issues/3

**Comment by redPanther** [comment]
and #25

**Pull request merged**
