### PR TITLE
Apa104

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Added support for apa104 LEDs. very similar to ws2812 but different timing

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by penfold42** [comment]
This might not be necessary as the ws2812 driver is reported as working with the apa104.
https://hyperion-project.org/threads/apa-104-support.2729/

**Comment by WoLpH** [comment]
As far as I can gather they are really similar (the APA104 specsheet is pretty much fully copied from the WS2812) and I don't think there is much point to this. Perhaps @RickDB can shine a light on this since he's got a few APA104s

**Comment by RickDB** [comment]
Will double check it once my APA104s arrive (next week hopefully) as I currently using the older ones which is the 2-wire AP102s.

**Comment by tpmodding** [comment]
penfold knows what he does...code should be fine :)

**Comment by RickDB** [comment]
Alrighty then 👍

**Comment by RickDB** [comment]
Always nice to have it in a different class even if the specs are similar to WS2812 so that if we need to tweak APA104 can always do so.

**Comment by tpmodding** [comment]
absolutely right

**Pull request merged**
