### PR TITLE
Initial WebUI design and structure with JSON sample function

### PR DESCRIPTION
**Pull request by b1rdhous3**
**1.** Tell us something about your changes.

Initial WebUI design and structure with JSON sample function

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
That's hot!

**Comment by b1rdhous3** [comment]
Your button has arrived! ;)

**Comment by brindosch** [comment]
Wuhu :)
Thank you

**Comment by redPanther** [comment]
thats great!!! While fixing the kodi beast, I checked out your branch, set the path in my config.json and it worked out of the box. I can set the color ... yeah.

BTW current remote control ui is only a place holder, If we/you want to replace that thingy ... I would love it.

**Comment by brindosch** [comment]
I said he could move all examples to subfolders, they are helpful for now. (At least i think).
We could remove them later.

I like the already working translation :D

**Comment by redPanther** [comment]
... yeah that's good.

**Comment by b1rdhous3** [comment]
I will take the remote example to build something like that in the WebUI. I really like that color wheel

**Comment by redPanther** [comment]
I like that one:
 http://mathias-biedert.de/wp-content/uploads/2015/11/webapp.png
https://github.com/poljvd/hyperion-webapp

I use it also on my phone and on my desktop.

**Comment by b1rdhous3** [comment]
Do we really need the option to set the prio so slightly? 
I think it would be confusing to change it that way. It would end in hundreds of prios. 
Maybe a default value?

But all in all i like that

**Comment by redPanther** [comment]
the prio thing is not needed. One value, set in config (the dashboard, not in the remote itself) and thats it ...

**Comment by redPanther** [comment]
this color picker is used
https://github.com/mattfarina/farbtastic

**Comment by brindosch** [comment]
Yes, 2014 and that way it looks like ;)
Aww you are right, clear all kills our background-effect. This is bad! This is the only way to get rid of prios you set "somewhere".

**Comment by penfold42** [comment]
Maybe we need a Clearall-mine option ?

Now that we can track the source of the priorities could we clear all that are my source ?

**Comment by redPanther** [comment]
If you have an app (web,phone), there you should set the prio in config. then we can use normal clear, to clear my channel. If the remote app let the user set multiple channels, then the app has to keep track of that.

we can switch "off" the leds by selecting the "off" source.

**Comment by redPanther** [comment]
@b1rdhous3  should I merge, or should I wait for more commits.

**Comment by b1rdhous3** [comment]
If you like to merge you can do it. 
I think this state is a good start for the webinterface.

**Pull request merged**
