### PR TITLE
Added no-change as a USB capture video standard

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Adds a "no change" option for usb web cam devices that clearly dont do "pal" or "ntsc"

NOTE! I've noticed that the usb grabber wont start automatically - it starts and then stops.
If I enable and disable it from the web UI all is good

### CODE REVIEW

**Comment by brindosch** [comment]
I added no-change already (again) in my fork. The issue that you face is related to auto disable based on current visible priority (And never wake up again)

Will be all fixed with my next pr.

**Comment by penfold42** [comment]
Cool !

**Comment by penfold42** [comment]
Not sure this made it in

**Comment by Paulchen-Panther** [comment]
Integrated in PR #523

**Comment by tpmodding** [comment]
@Paulchen-Panther this is in your PR? so we can close this, right?

**Comment by Paulchen-Panther** [comment]
Yes

**Pull request closed without merging**
