### PR TITLE
Removed PR comment job from Github Actions 

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

Now our GitHub app should ensure that the link to GitHub Actions is integrated into PR.
Unfortunately I have not yet figured out how to extract the "run_id" from the current GitHub Actions workflow under Probot in order to provide a direct link to the artifacts. Should anyone know more about this. Please report.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by brindosch** [comment]
Ein :heart: für  :robot:
Sehr schick. Kenne mich aber mit den Github Apps leider nicht aus und kann dir momentan nicht weiterhelfen.

**Comment by Paulchen-Panther** [comment]
Habe die [App](https://github.com/hyperion-project/hyperion-project.bot) in ein neues Repository exportiert. Mit Hilfe von [Glitch](https://glitch.com/).
Die grundlegende Datei ist [index.js](https://github.com/hyperion-project/hyperion-project.bot/blob/master/index.js)
Wenn du mal lange weile hast. :grimacing:

**Comment by Paulchen-Panther** [comment]
https://glitch.com/edit/#!/join/7dfc1fa8-07de-47b6-8d2a-9639b25cceee

**Comment by brindosch** [comment]
An Github Actions data wird man da nicht kommen so wie es aussieht. Der `check_run` [payload](https://developer.github.com/v3/activity/events/types/#checkrunevent-api-payload) sieht besser aus.

**Comment by Paulchen-Panther** [comment]
Danke für den Link

**Comment by brindosch** [comment]
Geht, geht nicht?
>  The Checks API only looks for pushes in the repository where the check suite or check run were created. Pushes to a branch in a forked repository are not detected and return an empty

**Comment by Paulchen-Panther** [comment]
> Pushes to a branch in a forked repository are not detected and return an empty

Ich denke "mal wieder" nicht. :disappointed:

**Comment by Paulchen-Panther** [comment]
Ich merge erst mal, dann schauen wir wie es mit der App weiter geht. Danke noch mal für deiner Hilfe. :+1:

**Comment by brindosch** [comment]
Gerne, irgendwann wird man das schon irgendwie hinbekommen.

**Pull request merged**
