### PR TITLE
Update Json Interface (Enable/Disable components during runtime)

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**1.** Tell us something about your changes.
With this code we are able to enable or disable components during runtime.
Available Components are:
SMOOTHING, BLACKBORDER, KODICHECKER, FORWARDER, UDPLISTENER, BOBLIGHT_SERVER, GRABBER

Example:
To enable the Component "Kodi Video Checker" during runtime send the JSON Object:
{"command":"componentstate","componentstate":{"component":"KODICHECKER","state":true}}
or use
hyperion-remote --enable "KODICHECKER"

To disable the Component "KodiVideoChecker" during runtime send the JSON Object:
{"command":"componentstate","componentstate":{"component":"KODICHECKER","state":false}}
or use
hyperion-remote --disable "KODICHECKER"

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference a issue (optional)
#21 

NOTES:
Currently, only the Kodichecker Component is switchable.
The remaining Components coming soon.

### CODE REVIEW

**Comment by brindosch** [comment]
unstoppable
:)

**Comment by Paulchen-Panther** [comment]
??????

**Comment by brindosch** [comment]
Great! just move forward :)

**Comment by redPanther** [comment]
Cool. Will add missing code asap

**Comment by penfold42** [comment]
Excellent work !

**Comment by Paulchen-Panther** [comment]
Thank you very much

**Comment by redPanther** [comment]
can you resolve the merge conflicts?

**Comment by brindosch** [comment]
Huh, you merged at wrong order? :)

**Comment by brindosch** [comment]
do we need a own section for v4l2? As grabber is usual the platform grabber?

**Comment by redPanther** [comment]
grrr, yeah wrong order, but thats always the problem when pull requests modify same files.

"platform grabber" is more or less "screen capture", the v4l thingy can be different video devices. 
You can have only one screen grabber (ok, wetek uses 2, but thats another story.), but in theory endless video devices.
We should think about having multiple v4l devices. And yes this need an own section. We can possibly rename the sections to make the usecase clear:
framegrabber -> screenCaptureDevice
v4l2-grabber -> videoCaptureDevice (or devices when we support multiple v4l)

(and what I wish, change "device" into "ledDevice" or similar )

**Pull request closed without merging**
