### PR TITLE
Qcommandlineparser

### PR DESCRIPTION
**Pull request by WoLpH**
**1.** Tell us something about your changes.

The `getoptplusplus` library has been replaced with the Qt `QCommandLineParser`. Since it's quite limited by default I've created a new `Parser` class which encapsulates the `QCommandLineParser` and the `Option` class does extend the `QCommandLineOption`.

**2.** If this changes affect the .conf file. N/A

**3.** Reference an issue (optional)

As discussed in https://github.com/hyperion-project/hyperion.ng/issues/39

### CODE REVIEW

**Comment by WoLpH** [comment]
Not entirely sure how or why git shows that bunch of other commits as well... I've simply merged everything back from master several times. Has anyone done a rebase which could cause this?

**Comment by WoLpH** [comment]
Looks like the travis build is failing due to a C++ feature I'm using... I suppose variadic template parameter packing is not commonly supported yet?

**Comment by penfold42** [comment]
Here's what I do from a workflow perspective:
1. git remote update
2. git checkout -b newFeatureBranch upstream/master
3. Make your changes
4. git commit
5. git push origin newFeatureBranch
6. use github web UI to create the PR

**Comment by WoLpH** [comment]
That's roughly what I did. Except for repeating steps 3 and 4 several times with a "git fetch --all; git merge origin/master" in between to make sure I didn't get too many conflicts.

**Comment by brindosch** [comment]
all changes you see for /assets are from yesterday
https://github.com/hyperion-project/hyperion.ng/pull/195

js stuff moved to /lib and removed unnecessary files

**Comment by penfold42** [comment]
I suspect your repeated merging is the cause.
Not cos I know the first thing about git, but I've done multiple change commits cycles without it this happening.

**Comment by WoLpH** [comment]
I'll see if I can rebase the changes using the current master. That should solve the issues :)

**Comment by brindosch** [comment]
So it compiles for you?
Sadly you need to find a workaround for this, as it also fails on a Pi with jessie
```
In file included from /home/pi/hyperion/libsrc/commandline/DoubleOption.cpp:2:0:
/home/pi/hyperion/include/commandline/Parser.h:38:17: error: parameter pack ‘args’ cannot have a default argument
            Args ... args=0)
                 ^
libsrc/commandline/CMakeFiles/commandline.dir/build.make:100: recipe for target 'libsrc/commandline/CMakeFiles/commandline.dir/DoubleOption.cpp.o' failed
```

**Comment by WoLpH** [comment]
@brindosch Yes, it compiles without a problem for me on Clang (LLVM) and I've checked the supported GCC versions. It should be supported on 4.3 and up, can you check which GCC you are using? Perhaps we need to enable C++11 or C++14 support but I'm not a 100% sure that's the best way to go.

I've rebased (and squashed) the changes using the current master so we have a simple update now :)

**Comment by brindosch** [comment]
gcc (Raspbian 4.9.2-10) 4.9.2
hm

**Comment by WoLpH** [comment]
It looks like the C++11 flag was not enabled. I've tried re-enabling it to see if that helps with compilation :)

If we can make CMake 3.1 a requirement we could use the CXX_STANDARD macro: https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html

**Comment by brindosch** [comment]
Sadly not
Ubuntu 14.04: cmake version 2.8.12.2
Jessie: cmake version 3.0.2

so result: 3 platforms and 1 error. I am sorry

**Comment by WoLpH** [comment]
I guess I'm a bit ahead in that case... I've got CMake 3.5.2 here. But I have some Linux VMs which I can test on. I'll see if I can make it work :)

**Comment by brindosch** [comment]
Something missing in aml?

**Comment by WoLpH** [comment]
Most of the Linux commands were not converted to the new API yet... so that didn't work. And apparently Clang and GCC disagree on whether variadic templates should support a default value

**Comment by WoLpH** [comment]
Looks like the build is working great now, finally done :)

**Comment by brindosch** [comment]
Great, but sadly you are not finished :)
Raspberry Pi dispmanx
http://pastebin.com/q5pjEyuc

As long our pi cc compile is not prepared for travis this is a black hole :)

**Comment by brindosch** [comment]
Looks like a missing include :)

**Comment by WoLpH** [comment]
It's slightly more complicated than a missing include but not all that hard.

In related note, the commands really need some refactoring. There is so much code repetition in those parts.

**Comment by WoLpH** [comment]
@brindosch can you give it another try? It's purely theoretical at this point but I hope I fixed it :)

**Comment by brindosch** [comment]
Closer :)
http://pastebin.com/fuYjSv9K

**Comment by WoLpH** [comment]
Ok, that part is fixed too now :)

**Comment by brindosch** [comment]
Yes, looks fine :)

**Comment by brindosch** [comment]
Sad news: hyperion-remote is dead
output is always:
```
root@osmc:~# hyperion-remote -l
hyperion-remote:
        Version   : 2.0.0 (qcommandlineparser (Rick van Hattem-502043f/9f8a0a1-1472179403))
        build time: Aug 26 2016 09:56:03
QCommandLineParser: option not defined: "j"
Wrong address: unable to parse address ()
```

Hyperion dispmanx ends up with
```
root@osmc:~# hyperion-dispmanx
hyperion-dispmanx:
        Version   : 2.0.0 (qcommandlineparser (Rick van Hattem-502043f/9f8a0a1-1472179403))
        build time: Aug 26 2016 09:56:04
Floating point exception
```

**Comment by brindosch** [comment]
Does hyperion-osx run as usual if you set no arguements (or with)?

**Comment by WoLpH** [comment]
One of my last fixes broke the default argument handling. I believe I've fixed that part although I'm not a 100% sure it will fix the v4l as well.

**Comment by WoLpH** [comment]
There are definitely a few bugs left, stay tuned :)

**Comment by brindosch** [comment]
yes, grabbers still exits with floating point exception and hyperion-remote -l works now, but no arguments   example: hyperion-remote --enable "KODICHECKER"
It outputs
Connected to: "localhost:19444"
Enable Component ""
so the string is not passed.

**Comment by WoLpH** [comment]
I've misunderstood how the QOptionParser handles default arguments unfortunately so I'll need to modify how I access the API a bit. Shouldn't be too hard but for now it's quite broken :)

**Comment by WoLpH** [comment]
To quote Bjarne Stroustrup:

> C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows away your whole leg.

Passing a validator by reference while the reference is being invalidated is just plain stupid but a mistake that's fairly easy to make... my C++ is definitely rusty so I'm happy to get into it again with this project ;)

Anyhow, we might still have a few broken parts but I've tested the argument parsing on os x, regular linux and the pi so I'm hoping we're mostly there now.

**Comment by brindosch** [comment]
Much better! Thank you :)
Sadly.. :)
```
hyperion-remote:
root@osmc:~# hyperion-remote -l
hyperion-remote:
        Version   : 2.0.0 (qcommandlineparser (Rick van Hattem-554e2ac/2a48eb3-1472254291))
        build time: Aug 27 2016 00:04:57
Missing value after '-l'.
```
which is wrong, the same for --list
and --schemaGet i think this should work without it. (not tested all commands)
but the color works as intended :)

v4l2 still outputs
```
 hyperion-v4l2 --device /dev/video0 --video-standard PAL --input 0 --width -1 --height -1 --crop-left 15 --crop-right 12 --crop-top 5 --crop-bottom 5 --size-decimator 1 --frame-decimator 2 --red-threshold 0.0 --green-threshold 0.0 --blue-threshold 0.0 --screenshot
hyperion-v4l2:
        Version   : 2.0.0 (qcommandlineparser (Rick van Hattem-554e2ac/2a48eb3-1472254291))
        build time: Aug 27 2016 00:04:57
QString::arg: Argument missing: The used video standard. Valid values are PAL or NTSC (optional), no-change
QString::arg: Argument missing: The use pixel format. Valid values are YUYV, UYVY, and RGB32 (optional), no-change
QString::arg: Argument missing: Input channel (optional), -1
QString::arg: Argument missing: Try to set the width of the video input (optional), -1
QString::arg: Argument missing: Try to set the height of the video input (optional), -1
Missing value after '--screenshot'.
```
Do i use it wrong now?

**Comment by WoLpH** [comment]
You're using it correctly but that's one of the things that broke with the last update.

Parameters with and without values are distinctly separate now, which means that everything by default expects an argument such as the screenshot parameter. In the case of the screenshot it would be a good option to make it specify the filename but that won't work for all cases so that will require a little bit of hunting.

**Comment by WoLpH** [comment]
Thanks so much for all of the testing @brindosch. It helps a lot!
I'm planning on adding testing code to the command line parser but just a tad too little time right now to figure out how testing is best done here :)

With a bit of luck, the last few problems have been solved now. The behaviour might not be identical to the original but everything should function as expected.

**Comment by brindosch** [comment]
Yeah no problem, brindosch testing facility :)

Regarding v4l2. Can't we keep the current behaviour? The screenshot is saved in this directory you are during command execution.

v4l2 is still the same
'''
hyperion-v4l2 --device /dev/video0 --video-standard PAL --input 0 --width -1 --height -1 --crop-left 15 --crop-right 12 --crop-top 5 --crop-bottom 5 --size-decimator 1 --frame-decimator 2 --red-threshold 0.0 --green-threshold 0.0 --blue-threshold 0.0 --screenshot
ssh in: 	hyperion-v4l2:
ssh in: 		Version   : 2.0.0 (qcommandlineparser (Rick van Hattem-554e2ac/2a48eb3-1472254291))
ssh in: 		build time: Aug 27 2016 00:04:57
ssh out: 	QString::arg: Argument missing: The used video standard. Valid values are PAL or NTSC (optional), no-change
ssh out: 	QString::arg: Argument missing: The use pixel format. Valid values are YUYV, UYVY, and RGB32 (optional), no-change
ssh out: 	QString::arg: Argument missing: Input channel (optional), -1
ssh out: 	QString::arg: Argument missing: Try to set the width of the video input (optional), -1
ssh out: 	QString::arg: Argument missing: Try to set the height of the video input (optional), -1
ssh out: 	Missing value after '--screenshot'.
'''
Looks like it won't accept values that it should.

**Comment by WoLpH** [comment]
That's not the expected output. Can you try cleaning everything and building again?

As for the current screenshot behaviour, you're right. It's better not to change the API

**Comment by WoLpH** [comment]
This is my output (I don't have a v4l device to test with):
```
# hyperion-v4l2 --device /dev/video0 --video-standard PAL --input 0 --width -1 --height -1 --crop-left 15 --crop-right 12 --crop-top 5 --crop-bottom 5 --size-decimator 1 --frame-decimator 2 --red-threshold 0.0 --green-threshold 0.0 --blue-threshold 0.0 --screenshot
hyperion-v4l2:
        Version   : 2.0.0 (qcommandlineparser (Rick van Hattem-362000b/8bed2c9-1472083189))
        build time: Aug 27 2016 13:44:47
[HYPERION-V4L2 V4L2] <INFO> Signal threshold set to: {0,0,0}
[HYPERION-V4L2 V4L2] <INFO> configured v4l device: /dev/video0
[HYPERION-V4L2 V4L2] <ERROR> V4l2 init failed (Cannot identify '/dev/video0' error code 2, No such file or directory)
```

**Comment by brindosch** [comment]
Oh, yes, it works! Great Wolph!
(No idea what really happend)

so i think this is done, it is possible that there is still somewhere a issue, but this can't be big (if so)

**Comment by WoLpH** [comment]
A few issues are indeed likely but it should work :)

The only behaviour that has changed which I can't easily fix is the way parameters such as the threshold, gamma, blacklevel and whitelevel are passed along to hyperion-remote. Previously it allowed for 3 space separated numbers and now it's been changed to be consistent with the other types of color entries which accept:
 - named colors (e.g. `red`)
 - RGB with and without # (e.g. `#F00` and `F00`)
 - RRGGBB with and without #
 - AARRGGBB with and without # (`AA` = alpha channel)
 - RRRGGGBBB with and without #
 - RRRRGGGGBBBB with and without #
 - `transparent`, black with 0 opacity

**Comment by brindosch** [comment]
@redPanther waiting for approval or suggestions :)

**Comment by redPanther** [comment]
I'm still on a longer train trip. In germany we arn't able to supply stable phone/internet connection for unknown reason ...

Will test it by my self in the next days. Do long, big thx for coding this isdue

**Comment by WoLpH** [comment]
Stable internet in the trains is a problem in the Netherlands too... you're just switching between the antennas too often :P

**Pull request merged**
