### PR TITLE
Return tan to API requests whenever possible

### LINKED ISSUE #1001: tan should be preserved as much as possible
#### What problem does this feature solve?

As it stands, it is difficult for API users to rely on the tan field to filter responses to a particular request -- as the tan is dropped in (at least) some error conditions, even when it could be preserved.

An example of an exchange with the API server:
```
Sent: {"command": "clear", "tan": 27}
Received: {"command":"clear","error":"Errors during specific message validation, please consult the Hyperion Log","success":false,"tan":0}
```

The tan value of the response should be 27, not 0.

#### What does the proposed API look like?

If a tan is passed in, it should _always_ be preserved unless that is entirely impossible (e.g. malformed JSON such that it is not parseable by (e.g.) json.loads).

#### How should this be implemented in your opinion?

No preference/opinion.

#### Are you willing to work on this yourself?

Maybe.

### PR DESCRIPTION
**Pull request by m-seker**
**Summary**

Fixes #1001 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
I'll check it out tomorrow. thank you

**Comment by dermotduffy** [comment]
Tested in a custom build! Thank you for the quick fix, this works as expected and now includes the tan:

```
{"command": "clear", "tan": 29}
{"command":"clear","error":"Errors during specific message validation, please consult the Hyperion Log","success":false,"tan":29}
{"tan": 30}
{"command":"","error":"Errors during message validation, please consult the Hyperion Log.","success":false,"tan":30}
```

This example continues to NOT include the tan, but its entirely malformed JSON, so I think that's much more reasonable/expected:

```
{"malformed", "tan": 32}
{"command":"","error":"Errors during message parsing, please consult the Hyperion Log.","success":false,"tan":0}
```

Thanks again.

**Review by Lord-Grey — APPROVED** [review]

**Comment by dermotduffy** [comment]
@m-seker Hmm. Unintended consequence:

```
{"command": "serverinfo"}
{"command":"serverinfo","error":"Errors during specific message validation, please consult the Hyperion Log","success":false,"tan":0}
{"command": "serverinfo", "tan": 1}
{"command":"serverinfo", ... lots of content ... }
```

... from the logs ...

```
 2020-09-10T05:32:52.899Z [hyperiond JSONCLIENTCONNECTION] (ERROR) While validating schema against json data of 'JsonRpc@::ffff:<IP_ADDRESS>':[root].tan: integer expected
```

=> Accidentally made tan a mandatory field?

**Comment by m-seker** [comment]
@dermotduffy You are right, I fixed it, it should be OK now.

**Comment by dermotduffy** [comment]
@m-seker Rebuilt, now works without tan, thanks.

A question: Is there an intended distinction between tan==-1 and tan==0?

```
garbage
{"command":"","error":"Errors during message parsing, please consult the Hyperion Log.","success":false,"tan":0}
```

vs

```
{"command": "clear"}
{"command":"clear","error":"Errors during specific message validation, please consult the Hyperion Log","success":false,"tan":-1}
```

**Comment by Paulchen-Panther** [comment]
@m-seker 
Would you like to look again because of @dermotduffy problem with the output of TAN 0 and TAN -1? Or can I merge this PR and you check back later?

**Review by Paulchen-Panther — APPROVED** [review]

**Comment by m-seker** [comment]
@dermotduffy I couldn't decide whether it should be initialized to 0 or -1, 0 seems better fitted. Thanks @Paulchen-Panther

**Pull request merged**
