### PR TITLE
Migrate logging and add "enable" to smoothing

### PR DESCRIPTION
**Pull request by penfold42**
**1.** Tell us something about your changes.
Migrate logging and add "enable" to smoothing

**2.** If this changes affect the .conf file. Please provide the changed section
                "smoothing" :
                {
                        "enable"          : false,
                        "type"            : "none",
                        "time_ms"         : 50,
                        "updateFrequency" : 25.0000
                }

**3.** Reference a issue (optional)
#3 #25

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Nooooo :)
https://github.com/brindosch/hyperion.ngBeta/commit/e7af215604b8e82886f29c34aa7a175be8f8516e

This section needs a rework anyway, this messages are completely useless, as the options are all mandatory. Sadly i don't undertand the code here completely to rework this properly std::transform (is this for lower case transform? if so, useless :)

the options gathering from .json should be clean like all other options does.

**Comment by penfold42** [comment]
its ok if you have.... I just added another file to the commit

**Comment by brindosch** [comment]
Thank you, will recheck this later

**Comment by redPanther** [comment]
now we have a dup. enable = false is the same as type != linear. I suggest:

libsrc/hyperion/Hyperion.cpp
replace if (type == "none" ) block. we a type = "linear"; to set type always to linear

and delete "type" from defautl config files. 
If we need it later, it well be there waiting to be used. In the meantime it doesn't harm ...

**Comment by redPanther** [comment]
my suggestion:
```
	Logger * log = Logger::getInstance("Core");
	std::string type = smoothingConfig.get("type", "none").asString();
	std::transform(type.begin(), type.end(), type.begin(), ::tolower);
	
	type = "linear"; // TODO if we have more type, then delete it
	if ( ! smoothingConfig.get("enable", true).asBool() )
	{
		Info(log,"Smoothing disabled in config");
	}
	else if (type == "linear")
	{
		if (!smoothingConfig.isMember("time_ms"))
		{
			Error(log, "Unable to create smoothing of type linear because of missing parameter 'time_ms'");
		}
		else if (!smoothingConfig.isMember("updateFrequency"))
		{
			Error(log, "Unable to create smoothing of type linear because of missing parameter 'updateFrequency'");
		}
		else
		{
			const unsigned updateDelay = smoothingConfig.get("updateDelay", Json::Value(0u)).asUInt();
			Info(log, "Creating linear smoothing");
			return new LinearColorSmoothing(
					ledDevice,
					smoothingConfig["updateFrequency"].asDouble(),
					smoothingConfig["time_ms"].asInt(),
					updateDelay);
		}
	}
	else
	{
		Error(log, "Unknown smoothing type %s.", type.c_str());
	}

	return ledDevice;
}
```

**Comment by penfold42** [comment]
agreed - will do it after my recent PR is merged

**Comment by brindosch** [comment]
Hm, why so complicated in general? (Should work?)
```
LedDevice * Hyperion::createColorSmoothing(const Json::Value & smoothingConfig, LedDevice * ledDevice)
{	
	if ( smoothingConfig.get("enable", true).asBool() )
	{
		Debug(Logger::getInstance("Core"), "Creating linear smoothing");
		return new LinearColorSmoothing
				(
				ledDevice,
				smoothingConfig.get("updateFrequency", 25.000).asDouble(),
				smoothingConfig.get("time_ms", 200).asInt(),
				smoothingConfig.get("updateDelay", Json::Value(0u)).asUInt()
				);
	}
	else
	{
		Info(Logger::getInstance("Core"), "Smoothing disabled");
	}
	
	return ledDevice;
}
```

**Comment by brindosch** [comment]
Keep in mind that options are mandatory and a config will be declined if won't pass the json checker.

**Comment by redPanther** [comment]
We should keep the type evaluation. I'm sure we will have other smoothings in future. We can skip param check and set defaults if not there

**Comment by penfold42** [comment]
I'm not sure i understand so ill leave it to you guys and work on other items on my todo list

**Comment by brindosch** [comment]
Hm?
```
 LedDevice * Hyperion::createColorSmoothing(const Json::Value & smoothingConfig, LedDevice * ledDevice)
{	   
	Logger * log = Logger::getInstance("Core");
    std::string type = smoothingConfig.get("type", "none").asString();

    type = "linear"; // TODO if we have more type, then delete it
    if ( ! smoothingConfig.get("enable", true).asBool() )
    {
        Info(log,"Smoothing disabled");
    }
    else if (type == "linear")
    {
        Info(log, "Creating linear smoothing");
        return new LinearColorSmoothing(
				(
				ledDevice,
				smoothingConfig.get("updateFrequency", 25.000).asDouble(),
				smoothingConfig.get("time_ms", 200).asInt(),
				smoothingConfig.get("updateDelay", 0).asUInt()
				);
        
    }
    else
    {
        Error(log, "Unknown smoothing type %s.", type.c_str());
    }

    return ledDevice;
}
```

**Comment by redPanther** [comment]
here a tuned version of yours:
```
LedDevice * Hyperion::createColorSmoothing(const Json::Value & smoothingConfig, LedDevice * ledDevice)
{      
    Logger * log = Logger::getInstance("Core");
    std::string type = smoothingConfig.get("type", "none").asString();

    type = "linear"; // TODO currently hardcoded type, delete it if we have more types
    if ( ! smoothingConfig.get("enable", true).asBool() )
    {
        Info(log,"Smoothing disabled");
        return ledDevice;
    }
    
    if (type == "linear")
    {
        Info(log, "Creating linear smoothing");
        return new LinearColorSmoothing(
                ledDevice,
                smoothingConfig.get("updateFrequency", 25.000).asDouble(),
                smoothingConfig.get("time_ms", 200).asInt(),
                smoothingConfig.get("updateDelay", 0).asUInt()
                );

    }
 
    Error(log, "Smoothing disabled, because of unknown type '%s'.", type.c_str());
    return ledDevice;
}
```

if you "return" in an "if" block, then an "else" doesn't make sense. If we have other types, then duplicate the "if type"  block accordingly.

**Comment by brindosch** [comment]
i tested my example and it don't output any log messages, also no message that the smoothing is created with option XYZ. But the enable bool works, and it even starts with a invalid type.

I retest with your improvement.

**Comment by brindosch** [comment]
No idea, i tested again with you snippet, I get absolutely no log output. But what is much more strange, why starts the smoothing with this config
```
			"smoothing" :
		{
			"enable"          : true,
			"type"            : "", 
			"time_ms"         : 200,
			"updateFrequency" : 25.0000,
			"updateDelay"     : 0
		}
	},
```
The bool options works like it should.

**Comment by redPanther** [comment]
did you set the right level? or start hyperion with --debug or --verbose

**Comment by brindosch** [comment]
yes, debug and verbose, it won't show anything for smoothing and as stated above the IF won't work as it should

**Comment by redPanther** [comment]
I look into it tomorow ... gn8

**Comment by brindosch** [comment]
Thank you!
gn8

**Comment by redPanther** [comment]
quick note:
with latest master + my func above, I got this in the logs:
[HYPERIOND Smoothing] <INFO> Created linear-smoothing with interval_ms: 50, settlingTime_ms: 200, updateDelay: 0

**Comment by brindosch** [comment]
I noticed that the systemd journalctl log is "incomplete".
```
[HYPERIOND MAIN] <INFO> Selected configuration file: /etc/hyperion/hyperion.config.json
[HYPERIOND Core] <INFO> ColorTransform 'default' => [0; 121]
[HYPERIOND Core] <INFO> ColorTemperature 'default' => [0; 121]
[HYPERIOND Core] <INFO> ColorAdjustment 'default' => [0; 121]
[HYPERIOND LedDevice] <INFO> configuration:
{
        "colorOrder" : "bgr",
        "name" : "MyPi",
        "output" : "/dev/spidev0.0",
        "rate" : 1000000,
        "type" : "apa102"
}

[HYPERIOND Core] <INFO> Creating linear smoothing
[HYPERIOND Smoothing] <INFO> Created linear-smoothing with interval_ms: 40, settlingTime_ms: 0, updateDelay: 200
[HYPERIOND EFFECTENGINE] <INFO> 27 effects loaded from directory /usr/share/hyperion/effects
[HYPERIOND LOGGER] <WARNING> Logger settings overriden by command line argument
```
The (always) first message that is visible in journalctl is the following, everything above is never written to this db.

[HYPERIOND MAIN] <INFO> Hyperion started and initialised

**Pull request merged**
