### PR TITLE
add vero4k support

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
... according to https://hyperion-project.org/threads/adding-support-for-vero-4k.715/#post-5459

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Lacks of "does it work" test regarding capture?

**Comment by redPanther** [comment]
but without this nobody can test it ... :-)

**Comment by samnazarko** [comment]
Hi

Thanks for this -- please let me know what I can do to help you. Is there a simple way for our users to test this?

I see you've added the check for the CMake build system but I believe a tarball is still required. 

Vero 4K is an AML device so the usual grabbing techniques should work fine.

Cheers

Sam

**Comment by PuckStar** [comment]
As Sam says, please let us know how we (I'm a user) can test this.

**Comment by redPanther** [comment]
I cannot provide a binary, because I have no arm64 compiler chain. Usually I don't make/publish binaries for hyperion.ng. We will have binaries, when we go into public testing.
But if you can test now, it would be nice.

In short: you have to compile it on your own. Compilation is easy on any debian like distro (e.g. rasbian, ubuntu,..)
You can find the compile howto here: https://github.com/hyperion-project/hyperion.ng/blob/master/CompileHowto.md#the-general-quick-way-without-big-comments
 
Please note we taking about hyperion.ng - lots of things changed! Some important:
No hypercon, but a web ui for config. Config file is incompatible to old config ...

**Comment by samnazarko** [comment]
OSMC uses AArch64 kernel but an ARMv7 userland.

sudo apt-get install armv7-toolchain-osmc on any OSMC system will get you the necessary toolchain. On other systems, you can also add this but need to add ```deb http://apt.osmc.tv jessie main``` to /etc/apt/sources.list. OSMC's toolchain will automatically resolve necessary dependencies to build armv7 under x86_64 if you are building on PC.

Happy to assist anyone that wants to try building Hyperion-ng for now

**Comment by samnazarko** [comment]
We're looking forward to packaging Hyperion-ng in OSMC's App Store.

Cheers

Sam

**Comment by drjohannspector** [comment]
> We're looking forward to packaging Hyperion-ng in OSMC's App Store.
> 
> Cheers
> 
> Sam

I can't wait!!!


Noah

**Comment by quintz** [comment]
> 
> 
> We're looking forward to packaging Hyperion-ng in OSMC's App Store.
> 
> Cheers
> 
> Sam

This would be AWESOME

**Pull request merged**
