### PR TITLE
RGB24 and BGR24 cleanup

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

- RGB24 / BGR24 / BGR16 on top of #1748 

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Thinner77** [comment]
Great! Can you also complete support for BGR16 and BGR32? Pixelformat.h and ImageResampler already know about these formats, so it's only adding some more "if"s 😄.
wbr

**Comment by Lord-Grey** [comment]
> Can you also complete support for BGR16 and BGR32?

Done. 

It stepped away from BGR16, as I do not think a grey-scale format is too relevant and ImageResampler does not have a implementation yet.

Windows MF is now fixed, too.
Was a good opportunity to get my Windows dev environment up and running again 😀

**Comment by Thinner77** [comment]
Hi @Lord-Grey,

you are great, and fast 😄 .
But BGR16 isn't a grayscale format and ImageResampler already knows it, i'm confused: https://github.com/hyperion-project/hyperion.ng/blob/76fff98f5cc1f20c2c3e059bf9ded9ee73d564e1/libsrc/utils/ImageResampler.cpp#L120

wbr

**Comment by Lord-Grey** [comment]
> ImageResampler already knows it

I am sorry, I confused myself. I was referring to RGB16… :(
I will add it

**Comment by Thinner77** [comment]
Hi,

the other option would be to remove support for BGR16 completely because it hasn't been usable so far and nobody seems to have needed it. I dont't know, it's your decision. ;-)

wbr

**Comment by Lord-Grey** [comment]
> the other option would be to remove support for BGR16 completely because it hasn't been usable so far and nobody seems to have needed it.

I do not know the side effects on other grabbers. 
As the "if" are only during initialisation on V42L, I added BRG16.

**Pull request merged**
