### PR TITLE
Hue Wizard, ui adjustments

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
-  JSON-RPC: nothing
-  A new Hue Wizard, packed with enough features to enjoy the configuration.
-  bootstrap alerts removed, callouts added
- a global webconfig warning, when Hyperion has been disabled
- remote page adjusted to comp pr, color and effects selects have now a repeat button
- report uploads are now possible without log
- initial wiki links creation
- i18n tunings
- editor delete buttons are now red

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

### CODE REVIEW

**Comment by redPanther** [comment]
cool stuff! does it help on this #429 issue?

**Comment by brindosch** [comment]
It lists available ids that are registered on that bridge. So if you already understood how to configure Hyperion, it won't help.
Therefore philipshue is broken for @birdhouse and me since @ntim pr. We need to wait for @ntim here.

**Comment by redPanther** [comment]
ok understood ...

**Comment by ntim** [comment]
See #427: seems not all commits have been merged?!

**Pull request merged**
