### PR TITLE
new frame grabber handling

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
current state is, that the grabbers dispmanx (raspi/videocore), framebuffer and osx screen capture shares the same config block "framegrabber".
The config block "framegrabber" is a synonym for screen capture device. We have 2 other screen grabbers in hyperion available - x11 and amlogic.
Those 2 uses a separate config block.
This PR makes x11 grabber available through hyperiond and x11 and amlogic uses now the common screencapture config block "framegrabber".
This prohibits usage of e.g. amlogic and e.g. framebuffer at the same time.

The framegrabber block has a new option named "type" If type is "auto" the best available grabber for current platform is choosen. If you want manual select, use type variable with values:
- osx
- dispmanx
- amlogic
- x11
- framebuffer

To make it perfect we need to solve issue  #122. Currently we need 2 builds for arm platform (raspi and other arm systems) Later on we can reduce it to one build for raspi that works on other arm systems too.

For x86 builds it is now easier to grab the screen, because x11 grabber works directly from inside hyperiond.

For wetek/amlogic people it is now easier to get it working. Just start hyperiond. The amlogic grabber is automaticly choosen, if started on systems with aml device available.

Extension for v4l:
display list of available devices:
```
[HYPERIOND V4L2GRABBER] <INFO> available V4L2 devices:
        /dev/video0     USB2.0 Camera
        /dev/video1     usbtv
        /dev/video2     BT878 video (Hauppauge (bt878))

```

add ability to use v4l name instead of device name or 'auto'.
example: (suitable for my device list above)
```
	"grabber-v4l2" : 
	{
		"enable" : true,
		"device" : "usbtv",
		....
	}
```
this selects always the "usbtv" device (my lightberry kit), regardless which /dev/videoX it is.
this is the output printed when device found:
`[HYPERIOND V4L2GRABBER] <INFO> found v4l2 device with configured name: usbtv (/dev/video1)`

**2.** If this changes affect the .conf file. Please provide the changed section
yes, mainly "type" in framegrabber. see commented config for more details
all screen capture grabbers (means all except v4l) now uses only section "framegrabber"

**3.** Reference a issue (optional)
#1 #117 (preparation for #122 )

### CODE REVIEW

**Comment by penfold42** [comment]
Great work - I was considering including the X11 grabber in hyperiond but you've gone even further!

**Comment by brindosch** [comment]
yes, great! It was not very inconsequent to include everything but no x11

**Comment by redPanther** [comment]
Problem with x11 was you cant set height/width, because resolution is theoreticly dynamic. I've made it possible, when x11 grabber detect resolution change, it resizes the buffer image and send new size to image processor.

Now get the runtime binding work ....

**Comment by redPanther** [comment]
.. add a new v4l feature, see my updated issue description

**Comment by stefansaraev** [comment]
@redPanther yep. works as expected

when setting type: auto in framegrabber, amlogic is auto selected and it works fine.
when setting type: framebuffer and device: /dev/fb0 - framebuffer grabber is selected, and it also works.

with amlgrabber, there is still a logger crash somewhere, so --debug or --verbose didnt work, sadly, I can not get usable backtrace (corrupt stacks everywhere, need to rebuild more stuff with debugging enabled), http://sprunge.us/KKNd
does not crash with --debug and framebuffer is in use. only amlgrabber is crashing

my only problem with this is, that I always needed two grabbers enabled and working - amlgrabber and framebuffer, because half of my content I play in kodi is software decoded. 

if only one active grabber is the future of hyperion, I hope one day kodi can use ionvideo to hw decode on aml devices. there was an attempt to rework it once, but it was too slow :(

if kodi can use ionvideo, this would effectively make amlgrabber obsolete and fb grabber would always work.

**Comment by redPanther** [comment]
i will investigate logger crash in aml...

**Comment by stefansaraev** [comment]
here, better one: http://sprunge.us/EfCP
https://github.com/hyperion-project/hyperion.ng/blob/master/libsrc/grabber/amlogic/AmlogicGrabber.cpp#L33

**Comment by redPanther** [comment]
Thats odd, disn't know how bad situation on wetek is.
Can you give me some more info what content use fb and what aml?

**Comment by stefansaraev** [comment]
in kodi v16, there is an option to disable amcodec. once you disable it, everything is decoded in software. if enabled (almost) everything is decoded in hardware

some codecs like h263, rmvb are always decoded in software. h265 is decoded in software on older boxes that can't hardware decode it (wetek play)

in kodi v17, there are (3) options to choose whether to enable hw decoding of mpeg2, mpeg4 and h264 depending on video dimensions. as amcodec does not play well with (interlaced) SD mpeg2 and some mpeg-4 videos, I do the following:

mpeg-2: hw decode only "hd and up" (width > 800). sw decode SD content (mostly live tv)
mpeg-4: same as mpeg-2
h264: always hw decode

with HW decoder active, you get nothing out of /dev/fb0, amcodec renders the picture behind kodi's back, so there amlgrabber is used.
with HW decoder not active, you get nothing out of /dev/amvideocap0, picture is rendered by kodi, amlgraber does not work. framebuffer grabber works.

**Comment by redPanther** [comment]
Ok then I start in aml case the aml and fb grabber.

**Comment by brindosch** [comment]
That also means that currently the grabber that get "no signal" stops automatically and unregister from prio?

**Comment by Paulchen-Panther** [comment]
@redPanther: Super sache.
Nur leider muss ich jetzt warten mit meinem PR. Hab schon einiges in der hyperiond in QTJson umgeschrieben. Das würde sich jetzt wieder beißen mit deinem PR.
Kein Problem. Ich kann warten. :-)

**Comment by brindosch** [comment]
If @redPanther give it a go we could merge it immediately :)

**Comment by Paulchen-Panther** [comment]
@redPanther:
Also funktionieren tut das schon mal super.
Ohne Debug Ausgabe wüsste ich aber nicht das der X11 grabber läuft.
Angeblich läuft ja keiner weil alle aus dem Build ausgeschlossen wurden.

`[HYPERIOND MAIN] <ERROR> No grabber can be instantiated, because all grabbers have been left out from the build`

**Comment by redPanther** [comment]
ich merge mal und den kleinram + wetek kommt dann später ...

**Pull request merged**
