### PR TITLE
LEDDevices - WLED enhancements and minor fixes

### LINKED ISSUE #1101: Uses WLED brightness settings instead of full range set in Hyperion settings
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce
- Set brightness at boot in WLED the WLED LED settings to a low value (10) or enable “turn off at boot”, then reboot.
- Start Hyperion, connect it to WLED.
- Or set brightness in WLED UI

#### What is expected?
Hyperion uses the maximum brightness setting which is defined in its config (100%) and takes full control of the LEDs independent of the WLED brightness settings.

#### What is actually happening?
Hyperion uses only 10/255 of the maximum brightness (basically the WLED boot brightness) or in case WLED is turned of after boot it stays completely dark.
The WLED UI confirms that Hyperion has control.

#### System

WLED: version 0.10.2 on Wemos D1 mini with WS2812b LEDs

Hyperion Server: 
- Build:           (HEAD detached at 83338dc3) (Paulchen Panther-ca50487e/83338dc3-1605733041)
- Build time:      Nov 18 2020 21:32:08
- Git Remote:      https://github.com/hyperion-project/hyperion.ng
- Version:         2.0.0-alpha.9
- UI Lang:         auto (BrowserLang: en-gb)
- UI Access:       default
- Avail Capt:      dispmanx,v4l2,framebuffer,qt
- Database:        read/write

Hyperion Server OS: 
- Distribution:   Raspbian GNU/Linux 10 (buster)
- Architecture:   arm
- CPU Model:      ARMv6-compatible processor rev 7 (v6l)
- CPU Type:       Raspberry Pi Zero W Rev 1.1
- CPU Revision:   9000c1
- CPU Hardware:   BCM2835
- Kernel:         linux (5.4.72+ (WS: 32))
- Qt Version:     5.7.1
- Python Version: 3.5.3
- Browser:        Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605

### PR DESCRIPTION
**Pull request by Lord-Grey**
**Summary**

### Added

- WLED: Support of ["live" property] (https://github.com/Aircoookie/WLED/issues/1308), addresses #1095
- WLED: Support storing/restoring state, fixes #1101 
- LED-Devices: Allow to get properties for Atmo and Karatedevices to limit LED numbers configurable
- LED-Devices: Add timeouts for REST-API calls

### Changed

- Nanoleaf: Consider Nanoleaf-Shape Controlers
- LED-Devices: Show HW-Ledcount in all setting levels

### Fixed

- LED-Hue: Minor fix of setColor command
- Nanoleaf: Fix,if external control mode cannot be set

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [X] Feature
- [ ] Code style update
- [X] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [X] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [X] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [X] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

Fixes #1101, #1095

### CODE REVIEW

**Comment by schwatter** [comment]
@Lord-Grey 

I compiled new with the last changes for WLED. The bri in LedDeviceWled.cpp is fixed at 255.

`const int BRI_MAX = 255;`

 I use most of the time just half bri around 120-150. So i changed it. I think, the best would be some inputbox to set the value.

cheers schwatter

**Comment by Lord-Grey** [comment]
@schwatter Thanks for the feedback. I will consider it. 
I only set it per default to full brightness, as there were complaints before that WLED triggered by Hyperion was not using the full range of brightness....

What configuration scenarios are required from your perspective?
a) Overwrite WLED brightness when start streaming yes/no (default=yes)
b) Set maximum WLED brightness to x (255 is default)
c) both above
d) something else....

Thank you.

**Comment by Lord-Grey** [comment]
@schwatter Please see the last update to PR #1164 . I made the brightness setting/overwrite configurable for WELD.
Please have a look, if it works as expected.

image

**Comment by schwatter** [comment]
Wow, fast response :)
Compiled and work as aspected. 

Indeed, i think another setup must be added. In Enigmalight, i send the following cmd's to interact with WLED.

`def wledOn(self):
.... r = http.request('GET', 'http://' + ip + '/win&T=1&RD=1&SN=0&RN=0')
`
`def wledOff(self):
.... r = http.request('GET', 'http://' + ip + '/win&T=0&RD=1&SN=1&RN=1')
`
&T= | 0, 1, or 2 | Master Off/On/Toggle
&RD= | 0 or 1 | Toggle realtime UDP
&SN= | 0 or 1 | Send UDP Notifications
&RN= | 0 or 1 | Receive UDP Notifications

Say, we have more then one WLED-Device and all are syned in one group. We start with all lights off. Now we want just the main device behind tv to act for ambilight and switch it on. Because of sync the rest from the group will also switch on.

I ask aircoookie for enhancement in a time i was new at all of this stuff, but the way i described here is a better way. (Pclin gave me that hint).

Here is my question:
https://github.com/Aircoookie/WLED/issues/1641

Cheers schwatter

**Comment by Lord-Grey** [comment]
@schwatter Do get you right that for your standard WLED setup you habe a group that syncs themselves using an WLED feature.
Now, you would like to break the group temporarily when streaming to the TV WLED device via Hyperion... When stopping streaming, I expect you would like to restore the state before streaming. Is my understanding correct?
If you would have only Hyperion, you could have multiple instances...

**Comment by schwatter** [comment]
Yes, you understand me right. Breaking the group, that the right words.
I know that hyperion can handle multiple instances. But that is not the point.
Say you have some open room (kitchen, dining room, living room) and you want only activate the living room lights for
ambilight. In this case i would be good to set the ambilights to &SN=0&RN=0, so that they can not make trouble.

**Comment by Lord-Grey** [comment]
Let me have a look any try myself.

**Comment by Lord-Grey** [comment]
@schwatter Have a look at PR #1164. 
I have implemented the ability to disable WLED synchronization when streaming via hyperion (and restoring the state when disabling the device via remote control or stopping hyperion)

image

Please test and report back.
You can easily test the behaviour, if you disable/enable the WLED device via the Remonte Control.
Just toggle the switch. 

image

If you want to monitor the WLED's, state just put

http://_wled-ip_/json/state

into the browser and check for `"udpn":{"send":false,"recv":true}`

**Comment by schwatter** [comment]
Sorry,

was busy the last days with other stuff. Now fresh compiled and tested.
Great improvement, it works as designed. Time for merge.


cheers schwatter

**Pull request merged**
