### PR TITLE
Update SSDPDiscover, Nanoleaf Device & CrossCompile Instructions

### PR DESCRIPTION
**Pull request by Lord-Grey**
1. Reapply changes overwritten by #602 to have SSDPDiscovery functionality generic and not for hyperion only. Change Info- to Debug logs given the technical nature of messages (as per PR discussion)
2. Fix NanoLeaf behaviour when switching on device
3. Update CrossComplie instructions after introduction of config-DB

### CODE REVIEW

**Comment by brindosch** [comment]
I removed it because of the log spam which is probably irritating to a user, in consider the specific search target more as debug.
You can rename it to just 'server'
This does not affect custom search targets as implementation.
Q: This is part of Hyperion, what do you mean by "other" search targets? For LedDevices?

**Comment by brindosch** [comment]
Or a custom log string is possible to modify output more user friendly

**Comment by Lord-Grey** [comment]
> Q: This is part of Hyperion, what do you mean by "other" search targets? For LedDevices?

Yes, I reused the SSDPDiscover functionality to discover a network LedDevice (here Nanoleaf) and therefore made it more generic. 

```
[hyperiond SSDPDISCOVER] <INFO> Search for Service [nanoleaf:nl29]
...
[hyperiond SSDPDISCOVER] <INFO> Found service [nanoleaf:nl29] at: 192.168.2.151:16021
[hyperiond LEDDEVICE] <INFO> Nanoleaf device discovered at [192.168.2.151:16021]
```

I agree to your point that a ssdp service name is not necessarily too user friendly for a standard INFO log.. Shouldn't we change the INFO message to DEBUG messages, as the discovery is quite technical?
The calling function may then decide, if an INFO message is relevant or not (see above).

**Comment by Paulchen-Panther** [comment]
Ready to merge?

**Comment by Lord-Grey** [comment]
Yes. Please go ahead.

**Pull request merged**
