### PR TITLE
refresh time for all devices + schema fixes

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
as the title said ...

**2.** If this changes affect the .conf file. Please provide the changed section
new general led device opt: rewriteTime

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Ouh thats weird for me now hehe.
https://github.com/brindosch/hyperion.ngBeta/commit/c5cb3ab56a0e5f4d9efb876b1d8eacbffdb8bb9f

**Comment by redPanther** [comment]
hmmm so we have to merge .... but now leddevice config is more complete. There were some device options missing due to misspelling

**Comment by brindosch** [comment]
Should this setting be hidden?

**Comment by penfold42** [comment]
I don't think so.

What would be cool tho is "advanced" and "expert" level options that the web up could selectively expose

**Comment by b1rdhous3** [comment]
We could add levels to the schema so we can hide and show some options and activate them on webui with a button ("advanced" and "expert")

**Comment by brindosch** [comment]
yeah of course, should be no problem
We need to discuss the settings storing, easiest would be inside our .json. But i don't like the idea because:
 - a level option/language setting and so on are not bound to a single config.json.

These should be stored and (json rpc) updated immediately. Could be also used in applications to setting up a language

**Comment by brindosch** [comment]
It's done. How many levels do we need (2? 3?) And if so, which editor input should be just available at a higher level. I need a list :)

**Comment by redPanther** [comment]
for my taste: 2 levels like VLC - "simple" / "all"

**Comment by penfold42** [comment]
Agree - just 1 set of hidden advanced options.

**Pull request merged**
