### PR TITLE
LED Layouts, Delete Effect, Colorpicker for EC

### PR DESCRIPTION
**Pull request by brindosch**
**1.** Tell us something about your changes.
 - Implements classic led layout with following options (top leds, bottom leds, left leds, right leds, gap length, gap position (360°), input start and direction reverse. Advanced: led depth horiz and vertical - more is on the way.
- Implements matrix layout - thanks to @RanzQ for the node.js script. One option for matrix layout is missing
- Implements led preview for matrix, classic and texfield. The led preview scales up and down with your browser width. So it works also fine on smartphones. Matrix uses a 1:1 ratio and classic/textfield 16:9. The first led is black and the second/third is greyish so see better the direction of data flow.
- Update schemas with "format:colorpicker" and implements colorpicker for effectsconfigurator color fields
- Implements "delete effect" on effects configurator page https://github.com/hyperion-project/hyperion.ng/pull/289

Issue: Need a proper onChange detection between colorpicker and editor. Help is appreciated @WoLpH  :)

ledframecreation

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

### CODE REVIEW

**Comment by penfold42** [comment]
Sweet !

**Comment by WoLpH** [comment]
Wow, nice :D

Great ipadte ;)
j/k, great work @brindosch!
ps: I'm still working on the kodi addon but just very busy right now :(

**Comment by brindosch** [comment]
Forgot to say: the colorpicker imp comes from @Paulchen-Panther. *throw credits*
Thanks at all

@WoLpH That damn addon :)

**Comment by b1rdhous3** [comment]
Wow nice work there! :)

**Pull request merged**
