### PR TITLE
Amendments to descriptions & spelling corrections

### PR DESCRIPTION
**Pull request by Joeboyc2**
**1.** Tell us something about your changes.
Made amendments to some of the descriptions and fixed some spelling mistakes

**2.** If this changes affect the .conf file. Please provide the changed section
No effect on .conf files 

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by Joeboyc2** [comment]
Not sure why the complies failed,  how do I restart them?

**Comment by brindosch** [comment]
Thank you for your contribution. Travis is sometimes a little bit weird, just ignore it.

**Comment by Joeboyc2** [comment]
Every test bar travis passed, happy to answer any questions before merge

**Comment by Paulchen-Panther** [comment]
Thank you for your work. 👍

**Pull request merged**
