### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by JeffResc**
**Summary**
I have ImgBot set up to automatically run on my repositories and when I made a fork of this repo, it automatically ran on that one too. I noticed that ImgBot was able to reduce the size by ~21% so I figured I would just forward its PR to here. It's automatically setup to do lossless compression, so there should be no image quality degradation, either.
```
*Total -- 6,709.46kb -> 5,286.86kb (21.2%)
```

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [X] Other, please describe: Image optimization

If changing the UI of web configuration, please provide the **before/after** screenshot: N/A

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [X] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
Hey @JeffResc .
Thank you for your submitted PR. Should we use the ImgBot ourselves on the Hyperion.ng repo?

As I saw, you know about JS. Are you interested in supporting us? You can find more details here:
https://hyperion-project.org/threads/web-devs-needed.10716/

**Comment by JeffResc** [comment]
@Paulchen-Panther I think it would be great if Hyperion adopted ImgBot. [It supports lossless compression](https://imgbot.net/docs/#compression) so there's nothing to worry about in terms of image quality, so I don't see any downsides into using it.

As the the web developer position, I'd be happy to help, but freely in my own time. If you had a project board or todo list of things that needed to be done, I'd love to pitch in every once and a while to solve things.

**Comment by Paulchen-Panther** [comment]
> As the the web developer position, I'd be happy to help, but freely in my own time. If you had a project board or todo list of things that needed to be done, I'd love to pitch in every once and a while to solve things.

We will discuss internally which topics will be included in the project board. Then we will get back to you. Thanks again for your help. 👍

**Comment by JeffResc** [comment]
> 
> 
> > As the the web developer position, I'd be happy to help, but freely in my own time. If you had a project board or todo list of things that needed to be done, I'd love to pitch in every once and a while to solve things.
> 
> We will discuss internally which topics will be included in the project board. Then we will get back to you. Thanks again for your help. 👍

Thank you, please keep me updated.

**Comment by Paulchen-Panther** [comment]
After we have agreed that we will integrate the ImgBot into the Hyperion repo, can I close your PR? Because PR # 1040 contains new icons.

**Comment by JeffResc** [comment]
Sounds good 👍

**Pull request closed without merging**
