### PR TITLE
FIX: display argument in hyperion-qt

### PR DESCRIPTION
**Pull request by Denrage**
**Summary**
This fixes the display argument in hyperion-qt, so it actually uses the display given to the program through argument.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@Denrage Thanks for your contribution!

If Display can always be an integer only, then this fix should be applied to other grabbers with "Display" too,
Could you also fix hyperion-osx.cpp?

**Comment by Denrage** [comment]
I fixed it for osx too. Am i able to test it without a mac?

**Comment by Lord-Grey** [comment]
@tpmodding Could you Test the fix on MacOS?

**Comment by tpmodding** [comment]
Bildschirmfoto 2020-10-09 um 18 39 34

**Review by tpmodding — APPROVED** [review]

**Comment by Paulchen-Panther** [comment]
I thank you on behalf of everyone for your help.

**Review by Paulchen-Panther — APPROVED** [review]

**Pull request merged**
