### PR TITLE
compile fix

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
... fix compile. if somebody can conform that it cmpiles on rpi-pwm, this would be nice.

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
```
/home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp: In member function ‘void* LedDeviceWS2812b::map_peripheral(uint32_t, uint32_t)’:
/home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:585:34: error: no matching function for call to ‘LedDeviceWS2812b::open(const char [9], int)’
  int fd = open("/dev/mem", O_RDWR);
                                  ^
/home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:585:34: note: candidate is:
In file included from /home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.h:102:0,
                 from /home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:23:
/home/pi/hyperion/include/leddevice/LedDevice.h:41:6: note: int LedDevice::open()
  int open();
      ^
/home/pi/hyperion/include/leddevice/LedDevice.h:41:6: note:   candidate expects 0 arguments, 2 provided
/home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp: In member function ‘void LedDeviceWS2812b::initHardware()’:
/home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:694:32: error: no matching function for call to ‘LedDeviceWS2812b::open(char [64], int)’
  fd = open(pagemap_fn, O_RDONLY);
                                ^
/home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:694:32: note: candidate is:
In file included from /home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.h:102:0,
                 from /home/pi/hyperion/libsrc/leddevice/LedDeviceWS2812b.cpp:23:
/home/pi/hyperion/include/leddevice/LedDevice.h:41:6: note: int LedDevice::open()
  int open();
      ^
/home/pi/hyperion/include/leddevice/LedDevice.h:41:6: note:   candidate expects 0 arguments, 2 provided
libsrc/leddevice/CMakeFiles/leddevice.dir/build.make:968: recipe for target 'libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWS2812b.cpp.o' failed
make[2]: *** [libsrc/leddevice/CMakeFiles/leddevice.dir/LedDeviceWS2812b.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by penfold42** [comment]
You guys Need me to look at this on my pi ?

**Comment by redPanther** [comment]
forgot to commit a file

**Comment by redPanther** [comment]
forgot to commit a file

**Comment by brindosch** [comment]
build success, i wait for merge until @penfold42 signal a go :)

**Comment by penfold42** [comment]
It'll be a few hours - it's only 25% done and in off to bed

**Comment by penfold42** [comment]
I suggest you merge it for now

**Comment by penfold42** [comment]
The 2812b driver fails with white LEDs.
The 281x works fine.

I suspect it's had this issue for a while - I don't think it's this patch that broke it
Pa, I'm using raspbian + noobs

**Comment by redPanther** [comment]
Did we need the 2812b driver? 

Btw I can compile ws281x on x86 ... (for compile test)

**Comment by penfold42** [comment]
Possibly not - we have 2 options instead - the rpi_281x and my SPI based driver

**Pull request merged**
