### PR TITLE
chore: Add Azure Github release title

### PR DESCRIPTION
**Pull request by brindosch**
**Summary**

Add a title to Github Release

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [x] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by Paulchen-Panther** [comment]
Bis jetzt beinhaltet die variable 'semver' nur den status alpha oder beta.
Damit wollte ich ermitteln ob es sich um ein pre-release handelt.
Habe es jetzt abgeändert.

**Comment by brindosch** [comment]
Oh, ganz übersehen!
Danke

**Comment by Paulchen-Panther** [comment]
Wir sollten an die changelog datei denken. Die können wir dann [hier](https://github.com/hyperion-project/hyperion.ng/blob/master/.azure.yml#L71) mit anhängen.
Details: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops

**Comment by brindosch** [comment]
Absolut!

**Pull request merged**
