### PR TITLE
V4L2 Grabber fix

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

This fixes the behavior of Issue #749 #754 

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [n] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**
Fixes: #749 , #754

### CODE REVIEW

**Comment by Thinner77** [comment]
Please don't remove call to IOCTL VIDIOC_ENUMSTD, it's used to check if device supports setting video standard, This is true for grabbers but not for other input devices such like cameras. Instead, fix current implementation, VIDIOC_ENUMSTD expects pointer to struct v4l2_standard not v4l2_std_id, this should solve issue too.

wbr

**Comment by Thinner77** [comment]
@Paulchen-Panther Thanks for your attention. May i ask you one more question?
Why did you remove lines 637-661? It looks like good written and working code following the API (https://linuxtv.org/downloads/v4l-dvb-apis/uapi/v4l/vidioc-g-parm.html) and the rule read-modify-write, to make sure all non modified parameters in struct v4l2_streamparm are set to driver defaults. Your stripped code may work today, but if API ever changes clearing all values in struct v4l2_streamparm and only setting struct v4l2_fract in struct v4l2_captureparm may result in undefined behavior, because all other values are reset. Just my 2cents. Full respect for your work.

wbr

**Comment by Thinner77** [comment]
Hi @Paulchen-Panther, i would really like to understand and discuss some code changes. Should i do this in forum, or are you not interested?

wbr

**Comment by Paulchen-Panther** [comment]
> Hi @Paulchen-Panther, i would really like to understand and discuss some code changes. Should i do this in forum, or are you not interested?

You can write to me in the forum via PM

**Comment by Thinner77** [comment]
Hi,

I'm not allowed to write you in the forum:

"You may not start a conversation with the following recipients: Paulchen-Panther."

wbr

**Comment by Paulchen-Panther** [comment]
I will close this PR and create a new one so that my new changes can be incorporated.

**Pull request closed without merging**
