### PR TITLE
NSIS/Systray option to launch Hyperion on Windows start [HKCU]

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
**Summary**

The title actually says it all.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

NSIS

Systray

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by tihoangyeudau** [comment]
applicationFilePath(): this function returned in regedit:
"C:/Program Files/Hyperion/bin/hyperiond.exe"  instead of "C:\Program Files\Hyperion\bin\hyperiond.exe" in String value "Hyperion", so i cant disable/enable autostart.

**Comment by Paulchen-Panther** [comment]
Thank you for the feedback. Corrected it. 👍

**Comment by Paulchen-Panther** [comment]
https://github.com/actions/virtual-environments/issues/841

**Comment by brindosch** [comment]
Tested and works as intended
Win10
- NSIS autostart link
- Systray enable
- Systray disable

**Comment by brindosch** [comment]
The icon option might be another issue/pr. As we need to decide about a icon theme (if so)

**Comment by Paulchen-Panther** [comment]
You're right. We should use the same symbols on all patforms.

**Comment by Paulchen-Panther** [comment]
Dann würde ich diesen PR jetzt mergen.
Vielen Dank an alle Tester.

**Pull request merged**
