### PR TITLE
Change confusing logic

### PR DESCRIPTION
**Pull request by Thinner77**
**Summary**

This PR will simply invert logic of variable _noSignalDetected in V4L2Grabber.cpp and MFGrabber.cpp, as current logic is IMHO very confusing.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Code style update
- [ ] Refactor
- [ ] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

If changing the UI of web configuration, please provide the **before/after** screenshot:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing setups:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's body (e.g. `Fixes: #xxx[,#xxx]`, where "xxx" is the issue number)

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature
- [ ] Related documents have been updated (docs/docs/en)
- [ ] Related tests have been updated

**PLEASE DON'T FORGET TO ADD YOUR CHANGES TO CHANGELOG.MD**
- [ ] Yes, CHANGELOG.md is also updated

To avoid wasting your time, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

This is my first PR ever, i'm still trying to understand git, so please be patient.

### CODE REVIEW

**Comment by Lord-Grey** [comment]
@Thinner77 Thanks for your contribution! 
Just looking at the current code, I agree that it is confusing.
Nevertheless, I am wondering why not renaming the variable to "isSignalDetected".
That would even more readable than having a noSignal and false combination. Two time negative to express a positive is hard to read from my perspective...
What do you think?

**Comment by Thinner77** [comment]
@Lord-Grey Great idea, let's do it. wbr

**Review by Lord-Grey — APPROVED** [review]

**Comment by Lord-Grey** [comment]
@Thinner77 could you have a try updating the indents, please?
I guess in your IDE you have configured tabs displayed as 8 spaces rather than 4 spaces why that happened.

**Comment by Lord-Grey** [comment]
> in my editor (PSPad) i see tabs

My comment was not that tab are replaced by spaces, but how tabs are visualised as spaces.

You should have tabs represented as 4 spaces, as in:

image

**Pull request merged**
