### PR TITLE
webui: add read/write for all editors

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
as the title said .. add read/write for all editors in webui.
Now you we can write all values (except log and webui - I decided that are 'nerd' settings and they can only be set in config manually)

when trying out, please backup your config before!!! (just some precautions ... )

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
... a side note layout and beautiful eye candy wasn't the goal of this PR - just the basics of loading and writing the config

**Comment by b1rdhous3** [comment]
Nice! But how about a "nerd"-Mode on webui?

**Comment by redPanther** [comment]
of course, but  the json editor needs some extension.
I want something like "settings level". Then we can add a settings level in json schema and set the level on editor ....

**Comment by brindosch** [comment]
and a title catcher(compare) for translations? the only idea i have how we could integrate them?

**Pull request merged**
