### PR TITLE
implement hyperion restart via webui

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
... as the title said. here a screencast
output3

the function itself is good, but It needs some refactoring ....

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by b1rdhous3** [comment]
Wow! nice!

**Comment by brindosch** [comment]
Amazing!

**Comment by Paulchen-Panther** [comment]
Wow. Das doch mal super. Vielen Dank für das Feature.

**Comment by Paulchen-Panther** [comment]
Fehlt nur noch eine shutdown Funktion. :-)

**Comment by redPanther** [comment]
Kommt noch. Werd das dann in ein neues json command packen

**Pull request merged**
