### PR TITLE
fix/refactor backlight stuff

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- fix colors dont turn off when backlight 0 and black is set (#391)
- add option to use not colored backlight (set threshold to lower value as used for colored backlight for best results)
- fix colored backlight not colored on very low color values
- various code style tunings

(this pr is a preparation for more tunings on brightness settings)

**2.** If this changes affect the .conf file. Please provide the changed section
yes:
brighnessMin -> backlightThreshold
new option: backlightColored

**3.** Reference an issue (optional)
#391

### CODE REVIEW

**Comment by brindosch** [comment]
Great!

Could i request something regarding minimum brightness?
Do not apply if (activePriority->compId color or effect)
Effects look weird with minimum brightness. I think it is more a support for ambient light than colors and effects
Is there a signal/slot that could be triggered to mod adjustments to and from a temp value or such.

Thank you :)

- Good that the ui scaling with it! Oh wait, remote page adjust has no bool filter - bad :)
You could update the wiz cc if you like https://github.com/hyperion-project/hyperion.ng/blob/master/assets/webconfig/js/wizard.js#L350 add your keys to the array :)

**Comment by redPanther** [comment]
it's possible, sad thing is, after implemention I loose a good tool to test backlight. I used setting a color to test it.

**Comment by penfold42** [comment]
Make it optional ?

BacklightEnableForEffects : "false"

**Comment by b1rdhous3** [comment]
Sadly no changes in the backlight topic for me after first testing. I will log the data send to LEDs

**Comment by redPanther** [comment]
This means your screen isnt black. That are the values from grabber. Please add gamma try 1.5 I use 2.5

**Comment by b1rdhous3** [comment]
Oh in my old config there were other values. I must overseen that, sorry. 
Working now with 2,5 on all channels.
0 0 0 => 0 0 0 0
:)

**Comment by redPanther** [comment]
> @brindosch : Do not apply if (activePriority->compId color or effect)

done ...

**Comment by oberstmueller** [comment]
Hi,
Ich bekomme beim Compilen auf dem Pi 3 im diesen Fehler.


/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1b58): undefined reference to `sd_listen_fds'
/usr/lib/gcc/arm-linux-gnueabihf/4.9/../../../arm-linux-gnueabihf/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1b98): undefined reference to `sd_is_socket'
collect2: error: ld returned 1 exit status
src/hyperiond/CMakeFiles/hyperiond.dir/build.make:231: recipe for target 'bin/hyperiond' failed
make[2]: *** [bin/hyperiond] Error 1
CMakeFiles/Makefile2:1573: recipe for target 'src/hyperiond/CMakeFiles/hyperiond.dir/all' failed
make[1]: *** [src/hyperiond/CMakeFiles/hyperiond.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by redPanther** [comment]
das gleiche hatten wir hier #279 schon. bitte dort weiter diskutieren

**Comment by brindosch** [comment]
So, after some tests i have to say. Very good!
As you fixed the color on low levels, i switched to white backlight. For me it is too distracting now

**Comment by redPanther** [comment]
glad you like it :-) now we have to master the brightness stuff ....

**Pull request merged**
