### PR TITLE
Webui: view led configuration + lights

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
add view of ledconfig and live led colors (update every 2 seconds)

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by b1rdhous3** [comment]
Nice!
Wouldn't it be good to have the option to change the refreshrate via config? For example in webconfig schema part. So you can change it directly in the webUI

**Comment by redPanther** [comment]
After thinking about led color update I realized that current way of getting the data (request-response) is not the good modern way to do.
I will change this that we send a request to start led data transfer (with interval in ms) and then hyperion pushes constantly leddata messages to webui until stop request recieved or websocket closed. Same thing I will do with the serverinfo.

**Comment by brindosch** [comment]
one word: amazing!
Could you change height to 450px which will then fit 16:9 ;)

**Comment by redPanther** [comment]
... change to 16:9 and prepare for realtime leds + other enhancements

**Comment by redPanther** [comment]
Rework of push messages for serverinfo and led streaming comes in next pr

**Pull request merged**
