### PR TITLE
Adjustment merge + new brightness settings

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- merge gamma from color transform to color adjust
- create new methods for brightness adjustments (aka backlight and upper brightness limit) in color adjust
- when source "off" selected, leds are off, regardless of minimal brightness
- full json support for new adjustment settings introduced by @Funatiq 
- remove colorTransform completly (and hope we don't have to bring it back)

**2.** If this changes affect the .conf file. Please provide the changed section
**this pr breaks compat with prior config.** Please see details in default config.
Just in short: color transform section is removed and new settings for gamma and brightness are added.
Also hyperion-remote options and capabilities has chenged - cconsider this if you use it in custom scripts!

**3.** Reference an issue (optional)
#338 #59 
Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by Funatiq** [comment]
Looking really good. Thank you for the effort. I don't have much time to test atm. Did you test the backlight? A problem with the old backlight was that it had too much color, so we changed it to always be gray (r=g=b).
Additionally, maybe you could add a brightness multiplier to increase overall brightness? I don't know if we really need this with all the other changes, but I think a lot of users are used to the value/luminace gain.

**Comment by brindosch** [comment]
Great changes!
Could you auto-adjust the brightness if (brightness <= minBrightness). As Hyperion quits currently, a log warning should be enough. How behaves this if you set a invalid brightness via jsonrpc?

**Comment by redPanther** [comment]
now invalids brighness values leads to warning with no exception

brighness curve is now exponential. optimal setting is 0.5 (the mid), <0.5 it goes darker, but with equal brighness through the channels. > 0.5 it goes brighter, but channels are now not at equal brighness.

**Comment by brindosch** [comment]
Ahh nice, will let you know how it performs.

**Comment by redPanther** [comment]
the value curve:
hyperion_brightness
horizontal input value from config, vertical resulting sum(r+g+b) threshold

**Comment by redPanther** [comment]
Backlight was the motivation, because old method annoyed me. For me its perfect now.

I think we dont need yet another brightness param. We have brightness nd white adjust, this should fit all needs.

**Comment by Funatiq** [comment]
I agree on keeping the amount of parameters low.
What I don't get is why you set 0.5 as default. With this _sumBrightnessHigh defaults to 255, right? So everything with r+g+b > 255 gets darker per default. Wouldn't it make more sense to keep 1.0 as default to get the full color spectrum?

**Comment by brindosch** [comment]
Well, the default could be changed. We  need more  feedback if a linear brightness (0,5) is better  than 1.0.    (which is on white 3x brighter than r/g/b).

**Comment by Funatiq** [comment]
You are right when you think about the 3 different leds. My problem with this approach is that many colors above the threshold are the same.
Example:

image color | output color | my suggestion
---|---|---
255,255,0 | 127,127,0 |  127,127,0 
200,200,0 | 127,127,0 |  100,100,0 
150,150,0 | 127,127,0 |  75,75,0 

If we want to use this approach, the easiest solution would be to scale down the color calibrations.
black, red, green, blue -> no problem
cyan, magenta, yellow -> divide by 2 ~> something like (127,127,0)
white -> divide by 3 ~> something like (85,85,85)
And the interpolation would take care of all colors in between.

**Comment by brindosch** [comment]
So i tested a little bit.
I notice the lost color values if i compare it. Your proposal is more accurate @Funatiq. This needs to be implemented in a way the user won't notice it (white: 255/(3*Linearfaktor, 255/(3*Linearfaktor), 255/(3*Linearfaktor)

On top i want to suggest to split maxBrightness and linearization. Which means you could control the brightness without the lost of linearization (you could also apply a different linearization to different brightness values)
@redPanther slack msg

**Comment by oberstmueller** [comment]
Hi,
will there be no Saturation Setting in the new hyperion?

**Comment by redPanther** [comment]
I hope we havn't bring it back. We want to simplify settings and save cpu time. Currently we tune color adjustment a bit.

For what you need saturation?

**Comment by redPanther** [comment]
I hope we havn't bring it back. We want to simplify settings and save cpu time. Currently we tune color adjustment a bit.

For what you need saturation?

**Comment by oberstmueller** [comment]
In some Scenes the Color is to strong for me. For example brown is oversaturated and looks like red.

**Pull request merged**
