### PR TITLE
implement origin for effects 

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- implement "origin" for effects
- fix/add origin for network services
- fix log buffer QT signaling
- add experimental adalight  firmware for arduino mega (with upto 5 rgb pwm channles + 1 addressable led stripe)
- more conversion of STL types to QT types (mainly std::string to QString)

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference an issue (optional)
#349 
Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
protocomp - yeah!

socket->peerAddress()
Do we get always the current information of the peer who requested it?
--> Pass IP to prio register too :+1:

Very nice

**Comment by redPanther** [comment]
yes we always get the client ip - otherwise we can't communicate. If you have a client socket, then you always have ip, mac and via dns the hostname of your connection client. (you get the client port to, but this is in most cases not interesting)

**Comment by brindosch** [comment]
Amazing!
/prio improve done

**Comment by redPanther** [comment]
BTW there is a chance that we automaticly support IPv6. I already get ipv6 as address for localhost (that's why I add dns lookup - ipv6 is not nice to display, read and remember ;-) )

**Pull request merged**
