### PR TITLE
move write config from json api to http post 

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
- use http post to transmit the config from webui to hyperion
- update webserver code
- remove obsolete code for multicoloradjustment

now saving config should work as expected. A todo is the connection lost detection, this can lead to false connection lost messages (e.g. when network/device is slow)

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference an issue (optional)

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
You mean the reload of the ui?
You loose more than 2 packages in 4 trys?

**Comment by redPanther** [comment]
Currently it checks if serverinfo could retrieved in 8 seconds for 3 trys.

My phone is sometimes slow, especially on loading. Once loaded ui is fast. I will move keep alive check to http. Websockets and retrieving serverinfo is to heavy

**Comment by brindosch** [comment]
Hm, we should lower the amount of libs. I think jquery ui is nearly unused and could be replaced with css3 animations.

**Comment by redPanther** [comment]
just found an issue (right after merge ...) spaces are replaced wit '+'. This is anoying in e.g. the back and foreground effect ... "rainbow+swirl+fast" instead of "rainbow swirl fast" will fix it asap

**Comment by redPanther** [comment]
Now webui is stable on my slow phone. Besides webui is quite fast and also led/video preview works

**Pull request merged**
