### PR TITLE
fix uncatched exception in json message handling

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
fix uncatched exception in json message handling

**2.** If this changes affect the .conf file. Please provide the changed section

**3.** Reference a issue (optional)
#148 

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by redPanther** [comment]
@WoLpH please test

**Comment by WoLpH** [comment]
The change looks good but I think it would be better to remove this block entirely: (https://github.com/hyperion-project/hyperion.ng/pull/164/files?w=1#diff-517591e3d8a9057c992935a4b65e68fbR222)
```
if (!reader.parse(messageString, message, false))
{
	sendErrorReply("Error while parsing json: " + reader.getFormattedErrorMessages());
	return;
}
```

The `checkJson` function does a `reader.parse` internally so it's a bit redundant now.

**Comment by redPanther** [comment]
both blocks needed. first one is for the message, second one is for the schema file

**Comment by WoLpH** [comment]
Ah, you're right. I didn't look thoroughly enough. In that case simply a 👍  from me :)

**Pull request merged**
