### PR TITLE
updated pull request template to remove mention of the beta branch

### PR DESCRIPTION
**Pull request by penfold42**
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
**1.** Tell us something about your changes.
updated pull request template to remove mention of the beta branch

**2.** If this changes affect the .conf file. Please provide the changed section
no

**3.** Reference a issue (optional)
beta removal discussed in #8 

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
:)

**Comment by brindosch** [comment]
OT: does some has a list of the qt5 libs we need? If not i will work on this
https://github.com/hyperion-project/hyperion.ng/blob/master/README.md

**Comment by penfold42** [comment]
dpkg -S `ldd bin/hyperiond | sed -e 's/.*=>//'  | tr "    " " " | tr -s " "  | cut -d " " -f 2`

**Comment by penfold42** [comment]
even better...
 dpkg -S `ldd bin/hyperiond | sed -e 's/.*=>//'  | tr "    " " " | tr -s " "  | cut -d " " -f 2` | cut -d : -f 1 | uniq

**Comment by redPanther** [comment]
Lets start the shell dojo :-)

**Comment by brindosch** [comment]
completely OT now, but i don´t want to open a issue for every little issue.
@penfold42 
i got yesterday this error during compile
```
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1c9c): undefined ref to `sd_listen_fds'
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libdbus-1.a(libdbus_1_la-dbus-sysdeps-unix.o): In function `_dbus_listen_systemd_sockets':
(.text+0x1cdc): undefined ref to `sd_is_socket'
collect2: error: ld returned 1 exit status
```
any idea?

**Pull request merged**
