### PR TITLE
Fix #676

### LINKED ISSUE #676: WS281x led device fails to start with "Device '' was not ready! Trying to re-open."
The changes from #654 have unfortunately broken the WS281x Led Device (and presumably other led devices, although I haven't tested any others). On attempting to start hyperion, I see the following messages in the log:

> [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:68:setEnable()) Device '' was not ready! Trying to re-open.
> [hyperiond LEDDEVICE] (DEBUG) (LedDevice.cpp:68:setEnable()) Previous line repeats 200 times

The _deviceReady flag is set in the LedDevice::start function, which calls LedDevice::open and sets the flag depending on the result. However, in the LedDevice::open function, LedDevice::setEnable is called, which checks _deviceReady and throws an error if it isn't. This will always fail because _deviceReady hasn't be set to true until LedDevice::open returns.

In a related note, if _deviceReady is false when LedDevice::setEnable is called, LedDevice::open is called again (which in turn calls LedDevice::setEnable and so on and so forth).

I agree with the type of check that was intended here, but the logic needs some tweaks.

### PR DESCRIPTION
**Pull request by Lord-Grey**
Fix issue #676
LedDevice Open() did not initialised the device correctly.

### CODE REVIEW

**Comment by Lord-Grey** [comment]
The Fix is ready for merge and was tested by @TheAndi

**Comment by Lord-Grey** [comment]
@Paulchen-Panther, @brindosch 
How can I close an issue? Or are you going to do it?

**Comment by Paulchen-Panther** [comment]
which issue?

**Comment by Lord-Grey** [comment]
> which issue?

Sorry, das im PR hier angegebene - > #676

**Comment by Lord-Grey** [comment]
Danke!

**Pull request merged**
