### PR TITLE
move 'name' to new config section general.

### PR DESCRIPTION
**Pull request by redPanther**
**1.** Tell us something about your changes.
Move name to new section general.
Add version number to config to describe the schema version.
Prepare structure for config migration feature

**2.** If this changes affect the .conf file. Please provide the changed section
New section general and and a version number for config

**3.** Reference an issue (optional)
#328 

Note: For further discussions use our forum: forum.hyperion-project.org

### CODE REVIEW

**Comment by brindosch** [comment]
Nice one.
Do you want to compare schema 1 against schema 2 for migration?
In case - you skip a version you can't migrate and you could never go back?
Isn't it possible to delete keys and add keys from config file of they are in schema/not in schema?

To hide the version we could add new access level that is always removed. "system" or such

**Comment by redPanther** [comment]
Good idea. Can you pr the new settings level. I will integrate it.

**Comment by redPanther** [comment]
Migration:
- Load and validate current cfg
- get current version of config
- if this is what hyperiond needs, exit
- otherwise start function to migrate from current to next higher version
- do this again, until we reach needed version, then exit

Everytime we increase the version number we have to write a function to migrate from prior version to the new.
This is the savest way.

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion.ng/commit/be909813880de33a16eddb2448234d69c1b29510

**Pull request merged**
