### PR TITLE
Improvements ...

### PR DESCRIPTION
**Pull request by Paulchen-Panther**
The following changes have been made:

- General:
	- The auto-correction of the configuration file has been reactivated
	- Fixed failed QWidget linking for Systray without QT Grabber (Issue: #491)
	- Fixed Amlogic framebuffer pixel format ([Issue](https://hyperion-project.org/threads/coreelec-hyperion-ng.3286/#post-13727))
- ProtoBuffer
	- Re-implemented to receive image data from third-party apps (eg. HyperionScreenCap, Android Screen Grabber, ...)
	- Compilation errors in AMLogic build fixed (Thanks to @Portisch )
- Submodules:
	- Updated rpi_ws281x submodule version to latest commit
- WebUI:
	- The status of the component "UDPListener" is now displayed correctly in WebUI ([Bug Report](https://hyperion-project.org/threads/udp-listener-not-working.3384/))
	- Global signal names for WebUI added
- Travis:
	- RPi tests were split into ARM architectures
	- i386 and ARMv8 (aarch64) docker test added
	- Docker container moved to [hyperionproject/hyperion-ci](https://hub.docker.com/r/hyperionproject/hyperion-ci) (dockerfiles: [Paulchen-Panther/docker-ci](https://github.com/Paulchen-Panther/docker-ci))
	- Base images updated to balenalib

Notes: After some users expressed a desire to re-implement the Protocol Buffer Server
to receive image data from third-party apps, I reintegrated it.
All other changes in this PR are described in the overview. It does not really need a big explanation

Testers are always welcome.

### CODE REVIEW

**Comment by Joeboyc2** [comment]
Happy to test this @Paulchen-Panther, are there travis builds in your repo I can use like before? Compiling take ages on my pi zero w :-p

**Comment by Portisch** [comment]
This will be needed to compile on Amlogic:
https://gist.github.com/Portisch/6a25daae58c7b0e54d6fafd11a3cd9c1

**Comment by Paulchen-Panther** [comment]
@Portisch 
The correction of the config has been reactivated and I have also taken over your amlogic changes.
Thank you again for that.

**Comment by Paulchen-Panther** [comment]
@Joeboyc2 I'll see how fast I get this done.

**Comment by RickDB** [comment]
Nice 👍 

Want to wait for user testing before merging?

**Comment by Paulchen-Panther** [comment]
Yes, please.

**Comment by b1rdhous3** [comment]
Compiling right now. Will inform you with test results asap.

**Comment by b1rdhous3** [comment]
Getting this error when trying to make on PPi0
`cmake -DCMAKE_BUILD_TYPE=Release ..-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- PLATFORM is not defined, evaluated platform: rpi
-- PLATFORM: rpi
-- ENABLE_AMLOGIC = OFF
-- ENABLE_DISPMANX = ON
-- ENABLE_FB = ON
-- ENABLE_OSX = OFF
-- ENABLE_SPIDEV   = ON
-- ENABLE_TINKERFORGE = ON
-- ENABLE_V4L2 = ON
-- ENABLE_WS281XPWM = ON
-- ENABLE_USB_HID = ON
-- ENABLE_X11 = OFF
-- ENABLE_QT = ON
-- ENABLE_TESTS = OFF
-- ENABLE_PROFILER = OFF
-- validate json files
   checked files: 76 success: 76 errors: 0
-- validate json effect files
   checked effect files: 36 success: 36 errors: 0
-- validate json file
-- Current Version: BugFixes2 (Paulchen-Panther-a406fef1/2ae692de-1550520990) Git Remote: https://github.com/hyperion-project/hyperion.ng.git
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Found Qt Version: 5.7.1
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/arm-linux-gnueabihf/libusb-1.0.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Looking for strtof_l
-- Looking for strtof_l - found
-- Using flatbuffers compiler: /home/pi/hyperionpr/hyperion/build/bin/flatc
CMake Error at dependencies/CMakeLists.txt:86 (add_subdirectory):
  The source directory

    /home/pi/hyperionpr/hyperion/dependencies/external/protobuf

  does not contain a CMakeLists.txt file.


CMake Error at dependencies/CMakeLists.txt:94 (export):
  export given target "protoc_compiler" which is not built by this project.


CMake Error at dependencies/CMakeLists.txt:102 (get_property):
  get_property could not find TARGET protoc_compiler.  Perhaps it has not yet
  been created.


-- Using protobuf compiler:
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.5m.so (found suitable version "3.5.3", minimum required is "3.5")
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.5m.so (found suitable version "3.5.3", minimum required is "3.4")
CPACK: Found DEB builder
-- Configuring incomplete, errors occurred!
See also "/home/pi/hyperionpr/hyperion/build/CMakeFiles/CMakeOutput.log".
See also "/home/pi/hyperionpr/hyperion/build/CMakeFiles/CMakeError.log".
`

**Comment by Paulchen-Panther** [comment]
Are you sure that you are using "clone --recursive" BRANCH
or "git submodule init && git submodule update" started?

**Comment by b1rdhous3** [comment]
Yes i did "clone --recursive". Anyway did now "git submodule init && git submodule update". Bin's are now compiled and i will test. 
As far I can already confirm, that Protobuff is working (again).

**Comment by jonty-comp** [comment]
I have rebuilt my crusty old Hyperion setup on my Nanopi NEO (a perfect little device for this sort of thing) and it seems to be working mostly perfectly on this branch, so thanks for your work.

After a few hours either `hyperion-x11` or `hyperiond` seem to get stuck and I have to restart both to get my lighting back, but I will have to do some more digging to find out which in particular is causing the problem.

**Comment by Paulchen-Panther** [comment]
@RickDB I am ready to merge.

**Pull request merged**
